(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Record Firework_record : Type :=
  {
    Firework_f_strength : t_i32;
  }.


#[export] Instance settable_Firework_record : Settable _ :=
  settable! (Build_Firework_record) <Firework_f_strength>.

Instance t_Drop_974857416 : t_Drop ((t_Firework)) :=
  {
    implaabbcc_t_Drop_f_drop := fun  (self : t_Firework)=>
      let args := (f_strength self) in
      let args := [impl__new_display (args)] in
      let _ := e_print (impl_1__new_v1 ([("BOOM times "%string : string); ("!!!
"%string : string)]) (args)) in
      let _ := tt in
      self;
  }.

Definition main '(_ : unit) : t_Result ((unit)) ((t_u8)) :=
  run (let e_firecracker := Firework ((1 : t_i32)) in
  let e_tnt := Firework ((100 : t_i32)) in
  let _ := if
    (true : bool)
  then
    let _ := e_print (impl_1__new_const ([("Exiting with error...
"%string : string)])) in
    let _ := tt in
    let hoist1 := ControlFlow_Break (Result_Err ((1 : t_u8))) in
    ControlFlow_Continue (never_to_any (hoist1))
  else
    ControlFlow_Continue (tt) in
  ControlFlow_Continue (let _ := Firework ((1000 : t_i32)) in
  Result_Ok (tt))).
