(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Equations say (message : both chString) : both 'unit :=
  say message  :=
    letb _ := black_box message in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations mcdc_check_neither (a : both 'bool) (b : both 'bool) : both 'unit :=
  mcdc_check_neither a b  :=
    ifb andb a b
    then letb _ := say (ret_both (a and b : chString)) in
    ret_both (tt : 'unit)
    else letb _ := say (ret_both (not both : chString)) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations mcdc_check_a (a : both 'bool) (b : both 'bool) : both 'unit :=
  mcdc_check_a a b  :=
    ifb andb a b
    then letb _ := say (ret_both (a and b : chString)) in
    ret_both (tt : 'unit)
    else letb _ := say (ret_both (not both : chString)) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations mcdc_check_b (a : both 'bool) (b : both 'bool) : both 'unit :=
  mcdc_check_b a b  :=
    ifb andb a b
    then letb _ := say (ret_both (a and b : chString)) in
    ret_both (tt : 'unit)
    else letb _ := say (ret_both (not both : chString)) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations mcdc_check_both (a : both 'bool) (b : both 'bool) : both 'unit :=
  mcdc_check_both a b  :=
    ifb andb a b
    then letb _ := say (ret_both (a and b : chString)) in
    ret_both (tt : 'unit)
    else letb _ := say (ret_both (not both : chString)) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations mcdc_check_tree_decision (a : both 'bool) (b : both 'bool) (c : both 'bool) : both 'unit :=
  mcdc_check_tree_decision a b c  :=
    ifb andb a (orb b c)
    then letb _ := say (ret_both (pass : chString)) in
    ret_both (tt : 'unit)
    else letb _ := say (ret_both (reject : chString)) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations mcdc_check_not_tree_decision (a : both 'bool) (b : both 'bool) (c : both 'bool) : both 'unit :=
  mcdc_check_not_tree_decision a b c  :=
    ifb andb (orb a b) c
    then letb _ := say (ret_both (pass : chString)) in
    ret_both (tt : 'unit)
    else letb _ := say (ret_both (reject : chString)) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations mcdc_nested_if (a : both 'bool) (b : both 'bool) (c : both 'bool) : both 'unit :=
  mcdc_nested_if a b c  :=
    ifb orb a b
    then letb _ := say (ret_both (a or b : chString)) in
    ifb andb b c
    then letb _ := say (ret_both (b and c : chString)) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit)
    else letb _ := say (ret_both (neither a nor b : chString)) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations main (_ : both 'unit) : both 'unit :=
  main _  :=
    letb _ := mcdc_check_neither (ret_both (false : 'bool)) (ret_both (false : 'bool)) in
    letb _ := mcdc_check_neither (ret_both (false : 'bool)) (ret_both (true : 'bool)) in
    letb _ := mcdc_check_a (ret_both (true : 'bool)) (ret_both (true : 'bool)) in
    letb _ := mcdc_check_a (ret_both (false : 'bool)) (ret_both (true : 'bool)) in
    letb _ := mcdc_check_b (ret_both (true : 'bool)) (ret_both (true : 'bool)) in
    letb _ := mcdc_check_b (ret_both (true : 'bool)) (ret_both (false : 'bool)) in
    letb _ := mcdc_check_both (ret_both (false : 'bool)) (ret_both (true : 'bool)) in
    letb _ := mcdc_check_both (ret_both (true : 'bool)) (ret_both (true : 'bool)) in
    letb _ := mcdc_check_both (ret_both (true : 'bool)) (ret_both (false : 'bool)) in
    letb _ := mcdc_check_tree_decision (ret_both (false : 'bool)) (ret_both (true : 'bool)) (ret_both (true : 'bool)) in
    letb _ := mcdc_check_tree_decision (ret_both (true : 'bool)) (ret_both (true : 'bool)) (ret_both (false : 'bool)) in
    letb _ := mcdc_check_tree_decision (ret_both (true : 'bool)) (ret_both (false : 'bool)) (ret_both (false : 'bool)) in
    letb _ := mcdc_check_tree_decision (ret_both (true : 'bool)) (ret_both (false : 'bool)) (ret_both (true : 'bool)) in
    letb _ := mcdc_check_not_tree_decision (ret_both (false : 'bool)) (ret_both (true : 'bool)) (ret_both (true : 'bool)) in
    letb _ := mcdc_check_not_tree_decision (ret_both (true : 'bool)) (ret_both (true : 'bool)) (ret_both (false : 'bool)) in
    letb _ := mcdc_check_not_tree_decision (ret_both (true : 'bool)) (ret_both (false : 'bool)) (ret_both (false : 'bool)) in
    letb _ := mcdc_check_not_tree_decision (ret_both (true : 'bool)) (ret_both (false : 'bool)) (ret_both (true : 'bool)) in
    letb _ := mcdc_nested_if (ret_both (true : 'bool)) (ret_both (false : 'bool)) (ret_both (true : 'bool)) in
    letb _ := mcdc_nested_if (ret_both (true : 'bool)) (ret_both (true : 'bool)) (ret_both (true : 'bool)) in
    letb _ := mcdc_nested_if (ret_both (true : 'bool)) (ret_both (true : 'bool)) (ret_both (false : 'bool)) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.
