(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Equations c (_ : both 'unit) : both 'unit :=
  c _  :=
    a : both 'unit.
Fail Next Obligation.

Equations a (_ : both 'unit) : both 'unit :=
  a _  :=
    c : both 'unit.
Fail Next Obligation.

Equations d (_ : both 'unit) : both 'unit :=
  d _  :=
    b : both 'unit.
Fail Next Obligation.

Equations b (_ : both 'unit) : both 'unit :=
  b _  :=
    d : both 'unit.
Fail Next Obligation.
