(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

TODO: please implement the method `item'_HaxError`

Record S_record : Type :=
  {
  }.

#[export]
Notation "'S_S_record'" := Build_S_record.

Instance t_T_954244439 : t_T ((t_S)) :=
  {
    implaabbcc_t_T_f_f := fun  (self : t_S)=>
      let _ := e_print (impl_1__new_const ([("impl S
"%string : string)])) in
      let _ := tt in
      tt;
  }.

Definition main '(_ : unit) : unit :=
  let _ := f_f (S) in
  tt.
