(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition main '(_ : unit) : unit :=
  let is_true := f_eq (f_len (args (tt))) ((1 : t_usize)) in
  let countdown := (0 : t_i32) in
  if
    is_true
  then
    let countdown := (10 : t_i32) in
    tt
  else
    tt.
