(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Equations do_stuff (_ : both 'unit) : both 'unit :=
  do_stuff _  :=
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations dense_a__dense_b__dense_c (_ : both 'unit) : both 'unit :=
  dense_a__dense_b__dense_c _  :=
    letb _ := do_stuff in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations dense_a__dense_b (_ : both 'unit) : both 'unit :=
  dense_a__dense_b _  :=
    letb _ := dense_a__dense_b__dense_c in
    letb _ := dense_a__dense_b__dense_c in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations dense_a (_ : both 'unit) : both 'unit :=
  dense_a _  :=
    letb _ := dense_a__dense_b in
    letb _ := dense_a__dense_b in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations sparse_a__sparse_b__sparse_c__sparse_d__sparse_e (_ : both 'unit) : both 'unit :=
  sparse_a__sparse_b__sparse_c__sparse_d__sparse_e _  :=
    letb _ := do_stuff in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations sparse_a__sparse_b__sparse_c__sparse_d (_ : both 'unit) : both 'unit :=
  sparse_a__sparse_b__sparse_c__sparse_d _  :=
    letb _ := sparse_a__sparse_b__sparse_c__sparse_d__sparse_e in
    letb _ := sparse_a__sparse_b__sparse_c__sparse_d__sparse_e in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations sparse_a__sparse_b__sparse_c (_ : both 'unit) : both 'unit :=
  sparse_a__sparse_b__sparse_c _  :=
    letb _ := sparse_a__sparse_b__sparse_c__sparse_d in
    letb _ := sparse_a__sparse_b__sparse_c__sparse_d in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations sparse_a__sparse_b (_ : both 'unit) : both 'unit :=
  sparse_a__sparse_b _  :=
    letb _ := sparse_a__sparse_b__sparse_c in
    letb _ := sparse_a__sparse_b__sparse_c in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations sparse_a (_ : both 'unit) : both 'unit :=
  sparse_a _  :=
    letb _ := sparse_a__sparse_b in
    letb _ := sparse_a__sparse_b in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations main (_ : both 'unit) : both 'unit :=
  main _  :=
    letb _ := dense_a in
    letb _ := sparse_a in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.
