(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition no_dependency_1_ '(_ : unit) : unit :=
  tt.

Definition no_dependency_2_ '(_ : unit) : unit :=
  tt.

Inductive t_Foo : Type :=
| Foo_A
| Foo_B.



Definition f '(_ : t_u32) : t_Foo :=
  Foo_A.

Record Bar_record : Type :=
  {
    Bar_0 : t_Foo;
  }.


#[export] Instance settable_Bar_record : Settable _ :=
  settable! (Build_Bar_record) <Bar_0>.
Notation "'Bar_Bar_record'" := Build_Bar_record.

Definition g '(_ : unit) : t_Bar :=
  Bar (f ((32 : t_u32))).

Definition t_Foo_cast_to_repr (x : t_Foo) : t_isize :=
  match x with
  | Foo_A =>
    (0 : t_isize)
  | Foo_B =>
    (1 : t_isize)
  end.
