(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Definition t_Foo : choice_type :=
  (int32).
Equations 0 (s : both t_Foo) : both int32 :=
  0 s  :=
    bind_both s (fun x =>
      ret_both (x : int32)) : both int32.
Fail Next Obligation.
Equations Build_t_Foo {0 : both int32} : both (t_Foo) :=
  Build_t_Foo  :=
    bind_both 0 (fun 0 =>
      ret_both ((0) : (t_Foo))) : both (t_Foo).
Fail Next Obligation.
Notation "'Build_t_Foo' '[' x ']' '(' '0' ':=' y ')'" := (Build_t_Foo (0 := y)).

#[global] Program Instance t_Foo_t_StructuralPartialEq : t_StructuralPartialEq t_Foo :=
  _.
Fail Next Obligation.
Hint Unfold t_Foo_t_StructuralPartialEq.

#[global] Program Instance t_Foo_t_PartialEq : t_PartialEq t_Foo t_Foo :=
  _.
Fail Next Obligation.
Hint Unfold t_Foo_t_PartialEq.

#[global] Program Instance t_Foo_t_Eq : t_Eq t_Foo :=
  _.
Fail Next Obligation.
Hint Unfold t_Foo_t_Eq.

#[global] Program Instance t_Foo_t_Debug : t_Debug t_Foo :=
  let f_fmt := fun  (self : both t_Foo) (f : both t_Formatter) => run (letb '(tmp0,out) := impl_11__write_fmt f (impl_1__new_const (array_from_list [ret_both (try and succeed : chString)])) in
  letb f := tmp0 in
  letb hoist2 := out in
  letb hoist3 := f_branch hoist2 in
  letm[choice_typeMonad.result_bind_code (t_Formatter × t_Result 'unit t_Error)] _ := matchb hoist3 with
  | ControlFlow_Break_case residual =>
    letb residual := ret_both ((residual) : (t_Result t_Infallible t_Error)) in
    letm[choice_typeMonad.result_bind_code (t_Formatter × t_Result 'unit t_Error)] hoist1 := ControlFlow_Break (prod_b (f,f_from_residual residual)) in
    ControlFlow_Continue (never_to_any hoist1)
  | ControlFlow_Continue_case val =>
    letb val := ret_both ((val) : ('unit)) in
    ControlFlow_Continue val
  end in
  ControlFlow_Continue (letb hax_temp_output := Result_Ok (ret_both (tt : 'unit)) in
  prod_b (f,hax_temp_output))) : both (t_Formatter × t_Result 'unit t_Error) in
  {| f_fmt := (@f_fmt)|}.
Fail Next Obligation.
Hint Unfold t_Foo_t_Debug.

(*item error backend*)

(*something is not implemented yet.
Mutable static items are not supported.

This is discussed in issue https://github.com/hacspec/hax/issues/1343.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `AST import`.
 todo(item)*)

(*Not implemented yet? todo(item)*)

Equations test1 (_ : both 'unit) : both 'unit :=
  test1 _  :=
    letb _ := ifb failure (ret_both (Explicit rejection by a phase in the Hax engine:
a node of kind [Unsafe] have been found in the AST

Note: the error was labeled with context `reject_Unsafe`.
 : chString)) (ret_both (unsafe { deref(new_tests::rustc_coverage__issue_84561_::v_DEBUG_LEVEL_ENABLED) } : chString))
    then letb _ := e_print (impl_1__new_const (array_from_list [ret_both (debug is enabled
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    letb _ := ifb failure (ret_both (Explicit rejection by a phase in the Hax engine:
a node of kind [Unsafe] have been found in the AST

Note: the error was labeled with context `reject_Unsafe`.
 : chString)) (ret_both (unsafe { deref(new_tests::rustc_coverage__issue_84561_::v_DEBUG_LEVEL_ENABLED) } : chString))
    then letb _ := e_print (impl_1__new_const (array_from_list [ret_both (debug is enabled
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    letb _ := ret_both (0 : int32) in
    letb _ := ifb failure (ret_both (Explicit rejection by a phase in the Hax engine:
a node of kind [Unsafe] have been found in the AST

Note: the error was labeled with context `reject_Unsafe`.
 : chString)) (ret_both (unsafe { deref(new_tests::rustc_coverage__issue_84561_::v_DEBUG_LEVEL_ENABLED) } : chString))
    then letb _ := e_print (impl_1__new_const (array_from_list [ret_both (debug is enabled
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    letb _ := failure (ret_both (Explicit rejection by a phase in the Hax engine:
a node of kind [Arbitrary_lhs] have been found in the AST

Note: the error was labeled with context `reject_ArbitraryLhs`.
 : chString)) (ret_both ((rust_primitives::hax::failure(
 "Fatal error: something we considered as impossible occurred! Please report this by submitting an issue on GitHub!\nDetails: expected an arrow type here\n\nNote: the e... : chString)) in
    letb _ := ret_both (tt : 'unit) in
    letb _ := ifb failure (ret_both (Explicit rejection by a phase in the Hax engine:
a node of kind [Unsafe] have been found in the AST

Note: the error was labeled with context `reject_Unsafe`.
 : chString)) (ret_both (unsafe { deref(new_tests::rustc_coverage__issue_84561_::v_DEBUG_LEVEL_ENABLED) } : chString))
    then letb _ := e_print (impl_1__new_const (array_from_list [ret_both (debug is enabled
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

(*Not implemented yet? todo(item)*)

(*item error backend*)

Equations test2 (_ : both 'unit) : both 'unit :=
  test2 _  :=
    letb _ := test2__call_print (ret_both (called from call_debug:  : chString)) in
    letb _ := ifb failure (ret_both (Explicit rejection by a phase in the Hax engine:
a node of kind [Unsafe] have been found in the AST

Note: the error was labeled with context `reject_Unsafe`.
 : chString)) (ret_both (unsafe { deref(new_tests::rustc_coverage__issue_84561_::v_DEBUG_LEVEL_ENABLED) } : chString))
    then letb _ := e_print (impl_1__new_const (array_from_list [ret_both (debug is enabled
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations main (_ : both 'unit) : both 'unit :=
  main _  :=
    letb _ := test1 in
    letb _ := test2 in
    letb _ := test3 in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.
