name = "Sha3"
version = "0.1.0"
defaultTargets = ["Sha3"]

[[lean_lib]]
name = "Sha3"

[[require]]
name = "aeneas"
git = "https://github.com/cryspen/aeneas"
rev = "8d2077c"
subDir = "backends/lean"

[[require]]
name = "Hax"
git = "https://github.com/cryspen/hax-evit"
rev = "ffdf432705d409b62ec025d253a340234b59766f"
subDir = "hax-lib/proof-libs/aeneas-lean"
