(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition main '(_ : unit) : t_Result ((unit)) ((t_u8)) :=
  let countdown := (10 : t_i32) in
  let countdown := failure (("something is not implemented yet.
Unhandled loop kind

This is discussed in issue https://github.com/hacspec/hax/issues/933.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `FunctionalizeLoops`.
"%string : string)) (("{
 (loop {
 |countdown| {
 (if core_models::cmp::f_gt(countdown, 0) {
 {
 #[note(
 "rhs.typ=core_models::ops::control_flow::t_ControlFlow<core_models::result::t_Result<tuple0, int>, tuple0>"
 )]
 #[mo..."%string : string)) in
  Result_Ok (tt).
