(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)



Definition main '(_ : unit) : unit :=
  failure (("something is not implemented yet.
Got type `Coroutine`: coroutines are not supported by hax

This is discussed in issue https://github.com/hacspec/hax/issues/924.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `AST import`.
"%string : string)) ((""%string : string)).

Definition main__v_MY_STATIC : unit :=
  tt.

Definition main__v_MY_CONST : unit :=
  tt.

Definition main__e_unused_fn '(_ : unit) : unit :=
  tt.

Record C_main__MyStruct_record : Type :=
  {
    C_main__MyStruct_main__f_e_x : t_u32;
    C_main__MyStruct_main__f_e_y : t_u32;
  }.



#[export] Instance settable_C_main__MyStruct_record : Settable _ :=
  settable! (Build_C_main__MyStruct_record) <C_main__MyStruct_main__f_e_x; C_main__MyStruct_main__f_e_y>.

Definition main__impl__e_method (self : main__t_MyStruct) : unit :=
  tt.

Class main__t_MyTrait (v_Self : Type) : Type :=
  {
  }.
Arguments main__t_MyTrait (_).

Instance main__t_MyTrait_1048613526 : main__t_MyTrait ((main__t_MyStruct)) :=
  {
  }.

(* NotImplementedYet *)
