(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Equations simple_assign (a : both 'bool) : both 'unit :=
  simple_assign a  :=
    letb x := a in
    letb _ := black_box x in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations assign_and (a : both 'bool) (b : both 'bool) : both 'unit :=
  assign_and a b  :=
    letb x := andb a b in
    letb _ := black_box x in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations assign_or (a : both 'bool) (b : both 'bool) : both 'unit :=
  assign_or a b  :=
    letb x := orb a b in
    letb _ := black_box x in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations assign_3_or_and (a : both 'bool) (b : both 'bool) (c : both 'bool) : both 'unit :=
  assign_3_or_and a b c  :=
    letb x := orb a (andb b c) in
    letb _ := black_box x in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations assign_3_and_or (a : both 'bool) (b : both 'bool) (c : both 'bool) : both 'unit :=
  assign_3_and_or a b c  :=
    letb x := orb (andb a b) c in
    letb _ := black_box x in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations foo (a : both 'bool) : both 'bool :=
  foo a  :=
    black_box a : both 'bool.
Fail Next Obligation.

Equations func_call (a : both 'bool) (b : both 'bool) : both 'unit :=
  func_call a b  :=
    letb _ := foo (andb a b) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations main (_ : both 'unit) : both 'unit :=
  main _  :=
    letb _ := simple_assign (ret_both (true : 'bool)) in
    letb _ := simple_assign (ret_both (false : 'bool)) in
    letb _ := assign_and (ret_both (true : 'bool)) (ret_both (false : 'bool)) in
    letb _ := assign_and (ret_both (true : 'bool)) (ret_both (true : 'bool)) in
    letb _ := assign_and (ret_both (false : 'bool)) (ret_both (false : 'bool)) in
    letb _ := assign_or (ret_both (true : 'bool)) (ret_both (false : 'bool)) in
    letb _ := assign_or (ret_both (true : 'bool)) (ret_both (true : 'bool)) in
    letb _ := assign_or (ret_both (false : 'bool)) (ret_both (false : 'bool)) in
    letb _ := assign_3_or_and (ret_both (true : 'bool)) (ret_both (false : 'bool)) (ret_both (false : 'bool)) in
    letb _ := assign_3_or_and (ret_both (true : 'bool)) (ret_both (true : 'bool)) (ret_both (false : 'bool)) in
    letb _ := assign_3_or_and (ret_both (false : 'bool)) (ret_both (false : 'bool)) (ret_both (true : 'bool)) in
    letb _ := assign_3_or_and (ret_both (false : 'bool)) (ret_both (true : 'bool)) (ret_both (true : 'bool)) in
    letb _ := assign_3_and_or (ret_both (true : 'bool)) (ret_both (false : 'bool)) (ret_both (false : 'bool)) in
    letb _ := assign_3_and_or (ret_both (true : 'bool)) (ret_both (true : 'bool)) (ret_both (false : 'bool)) in
    letb _ := assign_3_and_or (ret_both (false : 'bool)) (ret_both (false : 'bool)) (ret_both (true : 'bool)) in
    letb _ := assign_3_and_or (ret_both (false : 'bool)) (ret_both (true : 'bool)) (ret_both (true : 'bool)) in
    letb _ := func_call (ret_both (true : 'bool)) (ret_both (false : 'bool)) in
    letb _ := func_call (ret_both (true : 'bool)) (ret_both (true : 'bool)) in
    letb _ := func_call (ret_both (false : 'bool)) (ret_both (false : 'bool)) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.
