(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition doing_nothing '(_ : unit) `{(true : bool) = true} : unit :=
  tt.
Lemma doing_nothing_ensures '(_ : unit) :
  forall (H_requires : (true : bool) = true),
  let e_x := @doing_nothing '(_ : unit) H_requires in
  (true : bool) = true.
Proof. Admitted.

Definition basically_a_constant '(_ : unit) `{(true : bool) = true} : t_u8 :=
  (127 : t_u8).
Lemma basically_a_constant_ensures '(_ : unit) :
  forall (H_requires : (true : bool) = true),
  let x := @basically_a_constant '(_ : unit) H_requires in
  f_gt (x) ((100 : t_u8)) = true.
Proof. Admitted.
