(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

(Fatal error: something we considered as impossible occurred! Please report this by submitting an issue on GitHub!
Details: Could not find item with UID (Attr_payloads.UId.T.UId "dac5fbd4eb4b4dfcaf746f33ce85c082")

Note: the error was labeled with context `Coq backend`.
(* ERROR_ITEM *))


(Fatal error: something we considered as impossible occurred! Please report this by submitting an issue on GitHub!
Details: Could not find item with UID (Attr_payloads.UId.T.UId "53fb134b17604eaa91e4f234db013ad9")

Note: the error was labeled with context `Coq backend`.
(* ERROR_ITEM *))