(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Class t_Super (v_Self : Type) : Type :=
  {
    f_B : Type;
  }.
Arguments t_Super (_).

Record S_record : Type :=
  {
  }.

#[export]
Notation "'S_S_record'" := Build_S_record.

Instance t_Super_414377144 : t_Super ((t_S)) :=
  {
    implaabbcc_t_Super_f_B := t_u8;
  }.

Class t_T (v_Self : Type) (v_X : Type) `{t_Super (v_Self)} : Type :=
  {
    f_A : Type;
    f_C : t_u8;
    f_f : f_A -> t_u8;
    f_g : v_Self -> f_A -> f_A;
    f_h v_Y : Type `{t_Into (v_Y) (f_A)} : f_B -> v_Y -> v_X -> f_A;
  }.
Arguments t_T (_) (_) {_}.

Instance t_T_538662565 : t_T ((t_S)) ((t_u16)) :=
  {
    implaabbcc_t_T_f_A := t_u32;
    implaabbcc_t_T_f_C := (1 : t_u8);
    implaabbcc_t_T_f_f := fun  (x : t_u32)=>
      (0 : t_u8);
    implaabbcc_t_T_f_g := fun  (self : t_S) (x : t_u32)=>
      x;
    implaabbcc_t_T_f_h := fun  (x : t_u8) (y : v_Y) (z : t_u16)=>
      f_into (y);
  }.
