(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)



Record Int_record : Type :=
  {
    Int_0 : t_u128;
  }.


#[export] Instance settable_Int_record : Settable _ :=
  settable! (Build_Int_record) <Int_0>.
Notation "'Int_Int_record'" := Build_Int_record.





Definition Add_f_add (x : t_Int) (y : t_Int) : t_Int :=
  Int (f_add (0 x) (0 y)).



Instance t_Sub_406089482 : t_Sub ((t_Int)) ((t_Int)) :=
  {
    implaabbcc_t_Sub_f_Output := t_Int;
    implaabbcc_t_Sub_f_sub := fun  (self : t_Int) (other : t_Int)=>
      Int (f_add (0 self) (0 other));
  }.
