(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

(Fatal error: something we considered as impossible occurred! Please report this by submitting an issue on GitHub!
Details: Could not find item with UID (Attr_payloads.UId.T.UId "327c0679346242c897728e8fc662b5c0")

Note: the error was labeled with context `Coq backend`.
(* ERROR_ITEM *))


(Fatal error: something we considered as impossible occurred! Please report this by submitting an issue on GitHub!
Details: Could not find item with UID (Attr_payloads.UId.T.UId "d680445d1e264592af1940ad7b96f1eb")

Note: the error was labeled with context `Coq backend`.
(* ERROR_ITEM *))