(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)



Definition f (x : t_Prop) (y : bool) : t_Prop :=
  let xprop : t_Prop := f_into (y) in
  let p := f_bitand (f_bitand (f_bitand (f_lift (y)) (xprop)) (y)) (f_to_prop (y)) in
  f_not (impl_Prop__implies (f_bitor (p) (y)) (f_bitand (forall (fun x =>
    f_le (x) (impl_u8__MAX))) (exists (fun x =>
    f_gt (x) ((300 : t_u16)))))).
