(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition main '(_ : unit) : unit :=
  failure (("The bindings ["countdown"] cannot be mutated here: they don't belong to the closure scope, and this is not allowed.

This is discussed in issue https://github.com/hacspec/hax/issues/1060.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `LocalMutation`.
"%string : string)) (("{
 let is_true: bool = {
 core_models::cmp::f_eq(
 core_models::iter::traits::exact_size::f_len(std::env::args(Tuple0)),
 1,
 )
 };
 {
 let is_false: bool = { core_models::ops::bit::f_not(is_true) };
..."%string : string)).
