(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition do_stuff '(_ : unit) : unit :=
  tt.

Definition outer_fn '(_ : unit) : unit :=
  let _ := do_stuff (tt) in
  tt.

Definition outer_fn__middle_fn '(_ : unit) : unit :=
  let _ := do_stuff (tt) in
  tt.

Definition outer_fn__middle_fn__inner_fn '(_ : unit) : unit :=
  let _ := do_stuff (tt) in
  tt.

Record MyOuter_record : Type :=
  {
  }.

#[export]
Notation "'MyOuter_MyOuter_record'" := Build_MyOuter_record.

Definition impl_MyOuter__outer_method (self : t_MyOuter) : unit :=
  let _ := do_stuff (tt) in
  tt.

Record C_impl_MyOuter__outer_method__MyMiddle_record : Type :=
  {
  }.

#[export]
Notation "'Build_t__impl_MyOuter__outer_method__MyMiddle_MyMiddle_record'" := Build_C_impl_MyOuter__outer_method__MyMiddle_record.

Definition impl_MyOuter__outer_method__impl__middle_method (self : impl_MyOuter__outer_method__t_MyMiddle) : unit :=
  let _ := do_stuff (tt) in
  tt.

Record C_impl_MyOuter__outer_method__impl__middle_method__MyInner_record : Type :=
  {
  }.

#[export]
Notation "'Build_t__impl_MyOuter__outer_method__impl__middle_method__MyInner_MyInner_record'" := Build_C_impl_MyOuter__outer_method__impl__middle_method__MyInner_record.

Definition impl_MyOuter__outer_method__impl__middle_method__impl__inner_method (self : impl_MyOuter__outer_method__impl__middle_method__t_MyInner) : unit :=
  let _ := do_stuff (tt) in
  tt.

Class t_MyTrait (v_Self : Type) : Type :=
  {
    f_trait_method : v_Self -> unit;
  }.
Arguments t_MyTrait (_).

Instance t_MyTrait_825111665 : t_MyTrait ((t_MyOuter)) :=
  {
    implaabbcc_t_MyTrait_f_trait_method := fun  (self : t_MyOuter)=>
      let _ := do_stuff (tt) in
      tt;
  }.

Record C_f_trait_method__impl_MyTrait_for_MyOuter__MyMiddle_record : Type :=
  {
  }.

#[export]
Notation "'Build_t__f_trait_method__impl_MyTrait_for_MyOuter__MyMiddle_MyMiddle_record'" := Build_C_f_trait_method__impl_MyTrait_for_MyOuter__MyMiddle_record.

Instance t_MyTrait_881370855 : t_MyTrait ((f_trait_method__impl_MyTrait_for_MyOuter__t_MyMiddle)) :=
  {
    implaabbcc_t_MyTrait_f_trait_method__impl_MyTrait_for_MyOuter__f_trait_method := fun  (self : f_trait_method__impl_MyTrait_for_MyOuter__t_MyMiddle)=>
      let _ := do_stuff (tt) in
      tt;
  }.

Record C_f_trait_method__impl_MyTrait_for_MyOuter__f_trait_method__impl__MyInner_record : Type :=
  {
  }.

#[export]
Notation "'Build_t__f_trait_method__impl_MyTrait_for_MyOuter__f_trait_method__impl__MyInner_MyInner_record'" := Build_C_f_trait_method__impl_MyTrait_for_MyOuter__f_trait_method__impl__MyInner_record.

Instance t_MyTrait_796639778 : t_MyTrait ((f_trait_method__impl_MyTrait_for_MyOuter__f_trait_method__impl__t_MyInner)) :=
  {
    implaabbcc_t_MyTrait_f_trait_method__impl_MyTrait_for_MyOuter__f_trait_method__impl__f_trait_method := fun  (self : f_trait_method__impl_MyTrait_for_MyOuter__f_trait_method__impl__t_MyInner)=>
      let _ := do_stuff (tt) in
      tt;
  }.

Definition cclosure_expr '(_ : unit) : unit :=
  let e_outer := fun _ =>
    let e_middle := fun _ =>
      let e_inner := fun _ =>
        let _ := do_stuff (tt) in
        tt in
      let _ := do_stuff (tt) in
      tt in
    let _ := do_stuff (tt) in
    tt in
  let _ := do_stuff (tt) in
  tt.

Definition cclosure_tail '(_ : unit) : unit :=
  let e_outer := fun _ =>
    let e_middle := fun _ =>
      let e_inner := fun _ =>
        let _ := do_stuff (tt) in
        tt in
      let _ := do_stuff (tt) in
      tt in
    let _ := do_stuff (tt) in
    tt in
  let _ := do_stuff (tt) in
  tt.

Definition main '(_ : unit) : unit :=
  let _ := outer_fn (tt) in
  let _ := impl_MyOuter__outer_method (MyOuter) in
  let _ := f_trait_method (MyOuter) in
  let _ := cclosure_expr (tt) in
  let _ := cclosure_tail (tt) in
  tt.
