(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition say (message : string) : unit :=
  let _ := black_box (message) in
  tt.

Definition mcdc_check_neither (a : bool) (b : bool) : unit :=
  if
    andb (a) (b)
  then
    let _ := say (("a and b"%string : string)) in
    tt
  else
    let _ := say (("not both"%string : string)) in
    tt.

Definition mcdc_check_a (a : bool) (b : bool) : unit :=
  if
    andb (a) (b)
  then
    let _ := say (("a and b"%string : string)) in
    tt
  else
    let _ := say (("not both"%string : string)) in
    tt.

Definition mcdc_check_b (a : bool) (b : bool) : unit :=
  if
    andb (a) (b)
  then
    let _ := say (("a and b"%string : string)) in
    tt
  else
    let _ := say (("not both"%string : string)) in
    tt.

Definition mcdc_check_both (a : bool) (b : bool) : unit :=
  if
    andb (a) (b)
  then
    let _ := say (("a and b"%string : string)) in
    tt
  else
    let _ := say (("not both"%string : string)) in
    tt.

Definition mcdc_check_tree_decision (a : bool) (b : bool) (c : bool) : unit :=
  if
    andb (a) (orb (b) (c))
  then
    let _ := say (("pass"%string : string)) in
    tt
  else
    let _ := say (("reject"%string : string)) in
    tt.

Definition mcdc_check_not_tree_decision (a : bool) (b : bool) (c : bool) : unit :=
  if
    andb (orb (a) (b)) (c)
  then
    let _ := say (("pass"%string : string)) in
    tt
  else
    let _ := say (("reject"%string : string)) in
    tt.

Definition mcdc_nested_if (a : bool) (b : bool) (c : bool) : unit :=
  if
    orb (a) (b)
  then
    let _ := say (("a or b"%string : string)) in
    if
      andb (b) (c)
    then
      let _ := say (("b and c"%string : string)) in
      tt
    else
      tt
  else
    let _ := say (("neither a nor b"%string : string)) in
    tt.

Definition main '(_ : unit) : unit :=
  let _ := mcdc_check_neither ((false : bool)) ((false : bool)) in
  let _ := mcdc_check_neither ((false : bool)) ((true : bool)) in
  let _ := mcdc_check_a ((true : bool)) ((true : bool)) in
  let _ := mcdc_check_a ((false : bool)) ((true : bool)) in
  let _ := mcdc_check_b ((true : bool)) ((true : bool)) in
  let _ := mcdc_check_b ((true : bool)) ((false : bool)) in
  let _ := mcdc_check_both ((false : bool)) ((true : bool)) in
  let _ := mcdc_check_both ((true : bool)) ((true : bool)) in
  let _ := mcdc_check_both ((true : bool)) ((false : bool)) in
  let _ := mcdc_check_tree_decision ((false : bool)) ((true : bool)) ((true : bool)) in
  let _ := mcdc_check_tree_decision ((true : bool)) ((true : bool)) ((false : bool)) in
  let _ := mcdc_check_tree_decision ((true : bool)) ((false : bool)) ((false : bool)) in
  let _ := mcdc_check_tree_decision ((true : bool)) ((false : bool)) ((true : bool)) in
  let _ := mcdc_check_not_tree_decision ((false : bool)) ((true : bool)) ((true : bool)) in
  let _ := mcdc_check_not_tree_decision ((true : bool)) ((true : bool)) ((false : bool)) in
  let _ := mcdc_check_not_tree_decision ((true : bool)) ((false : bool)) ((false : bool)) in
  let _ := mcdc_check_not_tree_decision ((true : bool)) ((false : bool)) ((true : bool)) in
  let _ := mcdc_nested_if ((true : bool)) ((false : bool)) ((true : bool)) in
  let _ := mcdc_nested_if ((true : bool)) ((true : bool)) ((true : bool)) in
  let _ := mcdc_nested_if ((true : bool)) ((true : bool)) ((false : bool)) in
  tt.
