(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Inductive t_T : Type :=
| T_t1
| T_t2.



Definition t_T_cast_to_repr (x : t_T) : t_isize :=
  match x with
  | T_t1 =>
    (0 : t_isize)
  | T_t2 =>
    (1 : t_isize)
  end.

Fixpoint hf (x : t_T) : t_T :=
  match x with
  | T_t1 =>
    hf (T_t2)
  | T_t2 =>
    x
  end.

Definition g2 (x : t_T) : t_T :=
  match x with
  | T_t1 =>
    g1 (x)
  | T_t2 =>
    hf (x)
  end.

Definition g1 (x : t_T) : t_T :=
  match x with
  | T_t1 =>
    g2 (x)
  | T_t2 =>
    T_t1
  end.
