(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

Definition d1 '(_ : unit) : unit :=
  tt.

Definition e1 '(_ : unit) : unit :=
  d1 (tt).

Definition de1 '(_ : unit) : unit :=
  e1 (tt).

Definition d2 '(_ : unit) : unit :=
  de1 (tt).
