(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

Definition a '(_ : unit) : unit :=
  tt.

Definition call_a '(_ : unit) : unit :=
  a (tt).

Definition b '(_ : unit) : unit :=
  tt.

Definition call_b '(_ : unit) : unit :=
  b (tt).
