(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

Definition f '(_ : unit) : unit :=
  tt.

Definition h2 '(_ : unit) : unit :=
  i (tt).

Definition g '(_ : unit) : unit :=
  f (tt).

Definition h '(_ : unit) : unit :=
  let _ := g (tt) in
  i (tt).
