(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

Inductive t_Context : Type :=
| Context_A : t_i32 -> _
| Context_B : t_i32 -> _.



Definition impl__test (x : t_Option ((t_i32))) : t_Option ((t_Context)) :=
  impl__map (x) (Context_A).

Definition h '(_ : unit) : t_Context :=
  Context_A ((1 : t_i32)).

Definition f '(_ : unit) : t_Context :=
  h (tt).
