(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Equations v_UNREACHABLE_CLOSURE : both 'unit :=
  v_UNREACHABLE_CLOSURE  :=
    fun _ =>
      failure (ret_both (Explicit rejection by a phase in the Hax engine:
a node of kind [Unsafe] have been found in the AST

Note: the error was labeled with context `reject_Unsafe`.
 : chString)) (ret_both (unsafe {
 rust_primitives::hax::never_to_any(
 core_models::hint::unreachable_unchecked(Tuple0),
 )
 } : chString)) : both 'unit.
Fail Next Obligation.

Equations unreachable_function (_ : both 'unit) : both 'unit :=
  unreachable_function _  :=
    failure (ret_both (Explicit rejection by a phase in the Hax engine:
a node of kind [Unsafe] have been found in the AST

Note: the error was labeled with context `reject_Unsafe`.
 : chString)) (ret_both (unsafe {
 rust_primitives::hax::never_to_any(
 core_models::hint::unreachable_unchecked(Tuple0),
 )
 } : chString)) : both 'unit.
Fail Next Obligation.

Equations unreachable_intrinsic (_ : both 'unit) : both 'unit :=
  unreachable_intrinsic _  :=
    failure (ret_both (Explicit rejection by a phase in the Hax engine:
a node of kind [Unsafe] have been found in the AST

Note: the error was labeled with context `reject_Unsafe`.
 : chString)) (ret_both (unsafe {
 rust_primitives::hax::never_to_any(core_models::intrinsics::unreachable(Tuple0))
 } : chString)) : both 'unit.
Fail Next Obligation.

Equations main (_ : both 'unit) : both 'unit :=
  main _  :=
    letb _ := ifb black_box (ret_both (false : 'bool))
    then letb _ := v_UNREACHABLE_CLOSURE in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    letb _ := ifb black_box (ret_both (false : 'bool))
    then letb _ := unreachable_function in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    ifb black_box (ret_both (false : 'bool))
    then letb _ := unreachable_intrinsic in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.
