(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Class t_Foo (Self : choice_type) (v_Self : v_Self) := {
}.

Definition t_Bar {v_F : v_F} `{ t_Foo v_F} : choice_type :=
  (t_PhantomData v_F).
Equations f_e_phantom {v_F : v_F} `{ t_Foo v_F} (s : both t_Bar) : both (t_PhantomData v_F) :=
  f_e_phantom s  :=
    bind_both s (fun x =>
      ret_both (x : (t_PhantomData v_F))) : both (t_PhantomData v_F).
Fail Next Obligation.
Equations Build_t_Bar {v_F : v_F} `{ t_Foo v_F} {f_e_phantom : both (t_PhantomData v_F)} : both (t_Bar) :=
  Build_t_Bar  :=
    bind_both f_e_phantom (fun f_e_phantom =>
      ret_both ((f_e_phantom) : (t_Bar))) : both (t_Bar).
Fail Next Obligation.
Notation "'Build_t_Bar' '[' x ']' '(' 'f_e_phantom' ':=' y ')'" := (Build_t_Bar (f_e_phantom := y)).

Equations impl__new {v_F : v_F} `{ t_Foo v_F} (_ : both 'unit) : both (t_Bar v_F) :=
  impl__new _  :=
    Build_t_Bar (f_e_phantom := PhantomData) : both (t_Bar v_F).
Fail Next Obligation.
