(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Definition t_S : choice_type :=
  (int32).
Equations f_f1 (s : both t_S) : both int32 :=
  f_f1 s  :=
    bind_both s (fun x =>
      ret_both (x : int32)) : both int32.
Fail Next Obligation.
Equations Build_t_S {f_f1 : both int32} : both (t_S) :=
  Build_t_S  :=
    bind_both f_f1 (fun f_f1 =>
      ret_both ((f_f1) : (t_S))) : both (t_S).
Fail Next Obligation.
Notation "'Build_t_S' '[' x ']' '(' 'f_f1' ':=' y ')'" := (Build_t_S (f_f1 := y)).

Definition t_E : choice_type :=
  (int32).
Notation "'E_C_case' x" := x (at level 100).
Equations E_C (x : both int32) : both t_E :=
  E_C x  :=
    bind_both x (fun x =>
      ret_both (x : t_E)) : both t_E.
Fail Next Obligation.

#[global] Program Instance t_S_t_Default : t_Default t_S :=
  let f_default := fun  (_ : both 'unit) => Build_t_S (f_f1 := ret_both (42 : int32)) : both t_S in
  {| f_default := (@f_default)|}.
Fail Next Obligation.
Hint Unfold t_S_t_Default.

Equations test (_ : both 'unit) : both 'unit :=
  test _  :=
    letb o1 := Option_Some (ret_both (4 : int32)) in
    letb (o2 : t_Option int32) := Option_None in
    letb o3 := impl__is_some_and (f_clone o1) (fun x =>
      x =.? (ret_both (0 : int32))) in
    letb o3 := impl__is_none_or (f_clone o1) (fun x =>
      x =.? (ret_both (0 : int32))) in
    letb o4 := impl__unwrap (Option_Some (ret_both (0 : int32))) in
    letb o5 := impl__unwrap_or (Option_Some (ret_both (0 : int32))) (ret_both (9 : int32)) in
    letb o6 := impl__unwrap_or_else (Option_Some (ret_both (0 : int32))) (fun _ =>
      ret_both (9 : int32)) in
    letb o7 := impl__unwrap_or_default Option_None in
    letb o8 := impl__map (Option_Some (ret_both (0 : int32))) (fun x =>
      x .+ (ret_both (1 : int32))) in
    letb o9 := impl__map_or (Option_Some (ret_both (1 : int32))) (ret_both (9 : int32)) (fun x =>
      x .+ (ret_both (1 : int32))) in
    letb o10 := impl__map_or_else (Option_Some (ret_both (2 : int32))) (fun _ =>
      ret_both (9 : int32)) (fun x =>
      x .+ (ret_both (1 : int32))) in
    letb o11 := impl__ok_or (Option_Some (ret_both (3 : int32))) (E_C (ret_both (0 : int32))) in
    letb o12 := impl__ok_or_else (Option_Some (ret_both (1 : int32))) (fun _ =>
      E_C (ret_both (1 : int32))) in
    letb o13 := impl__and_then Option_None (fun x =>
      Option_Some x) in
    letb '(_,out) := impl__take (Option_Some (Build_t_S (f_f1 := ret_both (9 : int32)))) in
    letb o14 := out in
    letb o15 := impl__is_some (Option_Some (ret_both (1 : int32))) in
    letb o16 := impl__is_none (Option_Some (ret_both (2 : int32))) in
    letb o17 := impl__expect (Option_Some (ret_both (3 : int32))) (ret_both (Should be Some : chString)) in
    letb o18 := impl__unwrap (Option_Some (ret_both (4 : int32))) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.
