(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Equations test (_ : both 'unit) : both int32 :=
  test _  :=
    letb ff_1_ := fun _ =>
      ret_both (9 : int32) in
    letb ff_2_ := fun x => fun y =>
      x .+ y in
    letb ff_2_tuple := fun '(x,y) =>
      x .+ y in
    ((f_call ff_1_ (ret_both (0 : int32))) .+ (f_call ff_2_ (prod_b (ret_both (1 : int32),ret_both (2 : int32))))) .+ (f_call ff_2_tuple (prod_b (ret_both (1 : int32),ret_both (2 : int32)))) : both int32.
Fail Next Obligation.
