(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition foo `{v_T : Type} (x : v_T) : (t_i32*unit) :=
  let i := (0 : t_i32) in
  (failure (("something is not implemented yet.
Unhandled loop kind

This is discussed in issue https://github.com/hacspec/hax/issues/933.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `FunctionalizeLoops`.
"%string : string)) (("{
 (loop {
 |i| {
 (if core_models::cmp::f_lt(i, 10) {
 {
 let _: bool = {
 BinOp::Ast
 .Or(
 core_models::cmp::f_ne(i, 0),
 core_models::cmp::f_ne(i, 0),
 )
 };
 {
 let i: int = { core_models::ops::a..."%string : string)),tt).

Definition unused_template_func `{v_T : Type} (x : v_T) : (t_i32*unit) :=
  let i := (0 : t_i32) in
  (failure (("something is not implemented yet.
Unhandled loop kind

This is discussed in issue https://github.com/hacspec/hax/issues/933.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `FunctionalizeLoops`.
"%string : string)) (("{
 (loop {
 |i| {
 (if core_models::cmp::f_lt(i, 10) {
 {
 let _: bool = {
 BinOp::Ast
 .Or(
 core_models::cmp::f_ne(i, 0),
 core_models::cmp::f_ne(i, 0),
 )
 };
 {
 let i: int = { core_models::ops::a..."%string : string)),tt).

Definition unused_func (a : t_u32) : unit :=
  if
    f_ne (a) ((0 : t_u32))
  then
    let a := f_add (a) ((1 : t_u32)) in
    tt
  else
    tt.

Definition unused_func2 (a : t_u32) : unit :=
  if
    f_ne (a) ((0 : t_u32))
  then
    let a := f_add (a) ((1 : t_u32)) in
    tt
  else
    tt.

Definition unused_func3 (a : t_u32) : unit :=
  if
    f_ne (a) ((0 : t_u32))
  then
    let a := f_add (a) ((1 : t_u32)) in
    tt
  else
    tt.

Definition main '(_ : unit) : t_Result ((unit)) ((t_u8)) :=
  let _ := foo ((0 : t_u32)) in
  let _ := foo ((0.0%float : float)) in
  Result_Ok (tt).
