(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

Equations branch_and (a : both 'bool) (b : both 'bool) : both 'unit :=
  branch_and a b  :=
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (1 : int32)))) (fun _ =>
      ssp (fun _ =>
        ret_both (tt : 'unit) : (both 'unit))) (ret_both (tt : 'unit)) in
    letb c := andb a b in
    letb _ := black_box c in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations branch_or (a : both 'bool) (b : both 'bool) : both 'unit :=
  branch_or a b  :=
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (1 : int32)))) (fun _ =>
      ssp (fun _ =>
        ret_both (tt : 'unit) : (both 'unit))) (ret_both (tt : 'unit)) in
    letb c := orb a b in
    letb _ := black_box c in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations chain (x : both int32) : both 'unit :=
  chain x  :=
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (1 : int32)))) (fun _ =>
      ssp (fun _ =>
        ret_both (tt : 'unit) : (both 'unit))) (ret_both (tt : 'unit)) in
    letb c := andb (andb (andb (x >.? (ret_both (1 : int32))) (x >.? (ret_both (2 : int32)))) (x >.? (ret_both (4 : int32)))) (x >.? (ret_both (8 : int32))) in
    letb _ := black_box c in
    letb d := orb (orb (orb (x <.? (ret_both (1 : int32))) (x <.? (ret_both (2 : int32)))) (x <.? (ret_both (4 : int32)))) (x <.? (ret_both (8 : int32))) in
    letb _ := black_box d in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations nested_mixed (x : both int32) : both 'unit :=
  nested_mixed x  :=
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (1 : int32)))) (fun _ =>
      ssp (fun _ =>
        ret_both (tt : 'unit) : (both 'unit))) (ret_both (tt : 'unit)) in
    letb c := andb (orb (x <.? (ret_both (4 : int32))) (x >=.? (ret_both (9 : int32)))) (orb (x <.? (ret_both (2 : int32))) (x >=.? (ret_both (10 : int32)))) in
    letb _ := black_box c in
    letb d := orb (andb (x <.? (ret_both (4 : int32))) (x <.? (ret_both (1 : int32)))) (andb (x >=.? (ret_both (8 : int32))) (x >=.? (ret_both (10 : int32)))) in
    letb _ := black_box d in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations main (_ : both 'unit) : both ('unit × 'unit) :=
  main _  :=
    letb _ := foldi_both_list (f_into_iter (array_from_list [ret_both (false : 'bool);
      ret_both (true : 'bool);
      ret_both (true : 'bool);
      ret_both (true : 'bool);
      ret_both (true : 'bool)])) (fun a =>
      ssp (fun _ =>
        foldi_both_list (f_into_iter (array_from_list [ret_both (false : 'bool);
          ret_both (true : 'bool);
          ret_both (true : 'bool)])) (fun b =>
          ssp (fun _ =>
            letb _ := branch_and a b in
            letb _ := branch_or a b in
            ret_both (tt : 'unit) : (both 'unit))) (ret_both (tt : 'unit)) : (both 'unit))) (ret_both (tt : 'unit)) in
    prod_b (foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (16 : int32)))) (fun x =>
        ssp (fun _ =>
          letb _ := chain x in
          letb _ := nested_mixed x in
          ret_both (tt : 'unit) : (both 'unit))) (ret_both (tt : 'unit)),ret_both (tt : 'unit)) : both ('unit × 'unit).
Fail Next Obligation.
