(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

Equations say (message : both chString) : both 'unit :=
  say message  :=
    letb _ := black_box message in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations branch_not (a : both 'bool) : both 'unit :=
  branch_not a  :=
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (1 : int32)))) (fun _ =>
      ssp (fun _ =>
        ret_both (tt : 'unit) : (both 'unit))) (ret_both (tt : 'unit)) in
    letb _ := ifb a
    then say (ret_both (a : chString))
    else ret_both (tt : 'unit) in
    letb _ := ifb f_not a
    then letb _ := say (ret_both (not a : chString)) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    letb _ := ifb f_not (f_not a)
    then letb _ := say (ret_both (not not a : chString)) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    ifb f_not (f_not (f_not a))
    then letb _ := say (ret_both (not not not a : chString)) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations branch_not_as (a : both 'bool) : both 'unit :=
  branch_not_as a  :=
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (1 : int32)))) (fun _ =>
      ssp (fun _ =>
        ret_both (tt : 'unit) : (both 'unit))) (ret_both (tt : 'unit)) in
    letb _ := ifb f_not a
    then letb _ := say (ret_both (not (a as bool) : chString)) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    letb _ := ifb f_not (f_not a)
    then letb _ := say (ret_both (not not (a as bool) : chString)) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    ifb f_not (f_not (f_not a))
    then letb _ := say (ret_both (not not (a as bool) : chString)) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations branch_and (a : both 'bool) (b : both 'bool) : both 'unit :=
  branch_and a b  :=
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (1 : int32)))) (fun _ =>
      ssp (fun _ =>
        ret_both (tt : 'unit) : (both 'unit))) (ret_both (tt : 'unit)) in
    ifb andb a b
    then letb _ := say (ret_both (both : chString)) in
    ret_both (tt : 'unit)
    else letb _ := say (ret_both (not both : chString)) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations branch_or (a : both 'bool) (b : both 'bool) : both 'unit :=
  branch_or a b  :=
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (1 : int32)))) (fun _ =>
      ssp (fun _ =>
        ret_both (tt : 'unit) : (both 'unit))) (ret_both (tt : 'unit)) in
    ifb orb a b
    then letb _ := say (ret_both (either : chString)) in
    ret_both (tt : 'unit)
    else letb _ := say (ret_both (neither : chString)) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations main (_ : both 'unit) : both ('unit × 'unit) :=
  main _  :=
    letb _ := foldi_both_list (f_into_iter (array_from_list [ret_both (false : 'bool);
      ret_both (true : 'bool);
      ret_both (true : 'bool)])) (fun a =>
      ssp (fun _ =>
        letb _ := branch_not a in
        letb _ := branch_not_as a in
        ret_both (tt : 'unit) : (both 'unit))) (ret_both (tt : 'unit)) in
    prod_b (foldi_both_list (f_into_iter (array_from_list [ret_both (false : 'bool);
        ret_both (true : 'bool);
        ret_both (true : 'bool);
        ret_both (true : 'bool);
        ret_both (true : 'bool)])) (fun a =>
        ssp (fun _ =>
          foldi_both_list (f_into_iter (array_from_list [ret_both (false : 'bool);
            ret_both (true : 'bool);
            ret_both (true : 'bool)])) (fun b =>
            ssp (fun _ =>
              letb _ := branch_and a b in
              letb _ := branch_or a b in
              ret_both (tt : 'unit) : (both 'unit))) (ret_both (tt : 'unit)) : (both 'unit))) (ret_both (tt : 'unit)),ret_both (tt : 'unit)) : both ('unit × 'unit).
Fail Next Obligation.
