(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition test (x : t_Option ((t_i32))) (y : t_Option ((t_i32))) : t_Option ((t_i32)) :=
  run (impl__map (x) (fun i =>
    let hoist38 := y in
    Option_Some (let hoist39 := f_add (i) (hoist38) in
    Option_Some (hoist39)))).
