name = "hax"
defaultTargets = ["Hax", "CoreModels"]

[[lean_lib]]
name = "Hax"

[[lean_lib]]
name = "CoreModels"

[[require]]
name = "aeneas"
git = { url = "https://github.com/cryspen/aeneas", subDir = "backends/lean" }
rev = "48f6fb4b57e13b95bd45899501239a7167dd8b02"
