(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

(* NotImplementedYet *)

Definition while_cond '(_ : unit) : (t_i32*unit) :=
  let _ := fold_range ((0 : t_i32)) ((1 : t_i32)) (fun _ _ =>
    (true : bool)) (tt) (fun _ _ =>
    tt) in
  let a := (8 : t_i32) in
  (failure (("something is not implemented yet.
Unhandled loop kind

This is discussed in issue https://github.com/hacspec/hax/issues/933.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `FunctionalizeLoops`.
"%string : string)) (("{
 (loop {
 |a| {
 (if core_models::cmp::f_gt(a, 0) {
 {
 let a: int = { core_models::ops::arith::f_sub(a, 1) };
 a
 }
 } else {
 {
 let hoist1: int = {
 rust_primitives::hax::failure(
 "something is ..."%string : string)),tt).

Definition while_cond_not '(_ : unit) : (t_i32*unit) :=
  let _ := fold_range ((0 : t_i32)) ((1 : t_i32)) (fun _ _ =>
    (true : bool)) (tt) (fun _ _ =>
    tt) in
  let a := (8 : t_i32) in
  (failure (("something is not implemented yet.
Unhandled loop kind

This is discussed in issue https://github.com/hacspec/hax/issues/933.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `FunctionalizeLoops`.
"%string : string)) (("{
 (loop {
 |a| {
 (if core_models::ops::bit::f_not(core_models::cmp::f_eq(a, 0)) {
 {
 let a: int = { core_models::ops::arith::f_sub(a, 1) };
 a
 }
 } else {
 {
 let hoist3: int = {
 rust_primitives:..."%string : string)),tt).

Definition while_op_and '(_ : unit) : ((t_i32*t_i32)*unit) :=
  let _ := fold_range ((0 : t_i32)) ((1 : t_i32)) (fun _ _ =>
    (true : bool)) (tt) (fun _ _ =>
    tt) in
  let a := (8 : t_i32) in
  let b := (4 : t_i32) in
  (failure (("something is not implemented yet.
Unhandled loop kind

This is discussed in issue https://github.com/hacspec/hax/issues/933.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `FunctionalizeLoops`.
"%string : string)) (("{
 (loop {
 |Tuple2(a, b)| {
 (if BinOp::Ast
 .And(core_models::cmp::f_gt(a, 0), core_models::cmp::f_gt(b, 0))
 {
 {
 let a: int = { core_models::ops::arith::f_sub(a, 1) };
 {
 let b: int = { core_mod..."%string : string)),tt).

Definition while_op_or '(_ : unit) : ((t_i32*t_i32)*unit) :=
  let _ := fold_range ((0 : t_i32)) ((1 : t_i32)) (fun _ _ =>
    (true : bool)) (tt) (fun _ _ =>
    tt) in
  let a := (4 : t_i32) in
  let b := (8 : t_i32) in
  (failure (("something is not implemented yet.
Unhandled loop kind

This is discussed in issue https://github.com/hacspec/hax/issues/933.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `FunctionalizeLoops`.
"%string : string)) (("{
 (loop {
 |Tuple2(a, b)| {
 (if BinOp::Ast
 .Or(core_models::cmp::f_gt(a, 0), core_models::cmp::f_gt(b, 0))
 {
 {
 let a: int = { core_models::ops::arith::f_sub(a, 1) };
 {
 let b: int = { core_mode..."%string : string)),tt).

Definition main '(_ : unit) : unit :=
  let _ := while_cond (tt) in
  let _ := while_cond_not (tt) in
  let _ := while_op_and (tt) in
  let _ := while_op_or (tt) in
  tt.
