(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Equations main (_ : both 'unit) : both 'unit :=
  main _  :=
    letb truthy := (f_len args) =.? (ret_both (1 : uint_size)) in
    letb a := fun _ =>
      ifb truthy
      then ret_both (true : 'bool)
      else ret_both (false : 'bool) in
    letb _ := f_call a (ret_both (tt : 'unit)) in
    letb _ := ifb truthy
    then letb _ := f_call a (ret_both (tt : 'unit)) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    letb b := fun _ =>
      ifb truthy
      then ret_both (true : 'bool)
      else ret_both (false : 'bool) in
    letb _ := f_call b (ret_both (tt : 'unit)) in
    letb _ := ifb truthy
    then letb _ := f_call b (ret_both (tt : 'unit)) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    letb c := fun _ =>
      ifb truthy
      then ret_both (true : 'bool)
      else ret_both (false : 'bool) in
    letb _ := f_call c (ret_both (tt : 'unit)) in
    letb _ := ifb truthy
    then letb _ := f_call c (ret_both (tt : 'unit)) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) in
    letb d := fun _ =>
      ifb truthy
      then ret_both (true : 'bool)
      else ret_both (false : 'bool) in
    letb _ := f_call d (ret_both (tt : 'unit)) in
    ifb truthy
    then letb _ := f_call d (ret_both (tt : 'unit)) in
    ret_both (tt : 'unit)
    else ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.
