(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Fixpoint f (n : t_u8) : t_u8 :=
  if
    f_eq (n) ((0 : t_u8))
  then
    (0 : t_u8)
  else
    f_add (n) (f (f_sub (n) ((1 : t_u8)))).
