(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Definition t_Foo : choice_type :=
  (int32).
Equations 0 (s : both t_Foo) : both int32 :=
  0 s  :=
    bind_both s (fun x =>
      ret_both (x : int32)) : both int32.
Fail Next Obligation.
Equations Build_t_Foo {0 : both int32} : both (t_Foo) :=
  Build_t_Foo  :=
    bind_both 0 (fun 0 =>
      ret_both ((0) : (t_Foo))) : both (t_Foo).
Fail Next Obligation.
Notation "'Build_t_Foo' '[' x ']' '(' '0' ':=' y ')'" := (Build_t_Foo (0 := y)).

#[global] Program Instance t_Foo_t_Debug : t_Debug t_Foo :=
  _.
Fail Next Obligation.
Hint Unfold t_Foo_t_Debug.

#[global] Program Instance t_Foo_t_StructuralPartialEq : t_StructuralPartialEq t_Foo :=
  _.
Fail Next Obligation.
Hint Unfold t_Foo_t_StructuralPartialEq.

#[global] Program Instance t_Foo_t_PartialEq : t_PartialEq t_Foo t_Foo :=
  _.
Fail Next Obligation.
Hint Unfold t_Foo_t_PartialEq.

#[global] Program Instance t_Foo_t_Eq : t_Eq t_Foo :=
  _.
Fail Next Obligation.
Hint Unfold t_Foo_t_Eq.

Equations eq_good (_ : both 'unit) : both 'unit :=
  eq_good _  :=
    letb _ := e_print (impl_1__new_const (array_from_list [ret_both (a
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    letb _ := matchb prod_b (Foo (ret_both (1 : int32)),Foo (ret_both (1 : int32))) with
    | '(left_val,right_val) =>
      assert (left_val =.? right_val)
    end in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations eq_good_message (_ : both 'unit) : both 'unit :=
  eq_good_message _  :=
    letb _ := e_print (impl_1__new_const (array_from_list [ret_both (b
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    letb _ := matchb prod_b (Foo (ret_both (1 : int32)),Foo (ret_both (1 : int32))) with
    | '(left_val,right_val) =>
      assert (left_val =.? right_val)
    end in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations ne_good (_ : both 'unit) : both 'unit :=
  ne_good _  :=
    letb _ := e_print (impl_1__new_const (array_from_list [ret_both (c
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    letb _ := matchb prod_b (Foo (ret_both (1 : int32)),Foo (ret_both (3 : int32))) with
    | '(left_val,right_val) =>
      assert (f_not (left_val =.? right_val))
    end in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations ne_good_message (_ : both 'unit) : both 'unit :=
  ne_good_message _  :=
    letb _ := e_print (impl_1__new_const (array_from_list [ret_both (d
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    letb _ := matchb prod_b (Foo (ret_both (1 : int32)),Foo (ret_both (3 : int32))) with
    | '(left_val,right_val) =>
      assert (f_not (left_val =.? right_val))
    end in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations eq_bad (_ : both 'unit) : both 'unit :=
  eq_bad _  :=
    letb _ := e_print (impl_1__new_const (array_from_list [ret_both (e
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    letb _ := matchb prod_b (Foo (ret_both (1 : int32)),Foo (ret_both (3 : int32))) with
    | '(left_val,right_val) =>
      assert (left_val =.? right_val)
    end in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations eq_bad_message (_ : both 'unit) : both 'unit :=
  eq_bad_message _  :=
    letb _ := e_print (impl_1__new_const (array_from_list [ret_both (f
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    letb _ := matchb prod_b (Foo (ret_both (1 : int32)),Foo (ret_both (3 : int32))) with
    | '(left_val,right_val) =>
      assert (left_val =.? right_val)
    end in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations ne_bad (_ : both 'unit) : both 'unit :=
  ne_bad _  :=
    letb _ := e_print (impl_1__new_const (array_from_list [ret_both (g
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    letb _ := matchb prod_b (Foo (ret_both (1 : int32)),Foo (ret_both (1 : int32))) with
    | '(left_val,right_val) =>
      assert (f_not (left_val =.? right_val))
    end in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations ne_bad_message (_ : both 'unit) : both 'unit :=
  ne_bad_message _  :=
    letb _ := e_print (impl_1__new_const (array_from_list [ret_both (h
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    letb _ := matchb prod_b (Foo (ret_both (1 : int32)),Foo (ret_both (1 : int32))) with
    | '(left_val,right_val) =>
      assert (f_not (left_val =.? right_val))
    end in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations main (_ : both 'unit) : both 'unit :=
  main _  :=
    letb _ := eq_good in
    letb _ := eq_good_message in
    letb _ := ne_good in
    letb _ := ne_good_message in
    letb _ := assert (failure (ret_both (Explicit rejection by a phase in the Hax engine:
a node of kind [Dyn] have been found in the AST

Note: the error was labeled with context `reject_Dyn`.
 : chString)) (ret_both (core_models::result::impl__is_err::<tuple0,dyn(core_models::any::t_Any + core_models::marker::t_Send)>(std::panic::catch_unwind::<arrow!(tuple0 -> tuple0),tuple0>(new_tests::rustc_coverage__bad_counte... : chString))) in
    letb _ := assert (failure (ret_both (Explicit rejection by a phase in the Hax engine:
a node of kind [Dyn] have been found in the AST

Note: the error was labeled with context `reject_Dyn`.
 : chString)) (ret_both (core_models::result::impl__is_err::<tuple0,dyn(core_models::any::t_Any + core_models::marker::t_Send)>(std::panic::catch_unwind::<arrow!(tuple0 -> tuple0),tuple0>(new_tests::rustc_coverage__bad_counte... : chString))) in
    letb _ := assert (failure (ret_both (Explicit rejection by a phase in the Hax engine:
a node of kind [Dyn] have been found in the AST

Note: the error was labeled with context `reject_Dyn`.
 : chString)) (ret_both (core_models::result::impl__is_err::<tuple0,dyn(core_models::any::t_Any + core_models::marker::t_Send)>(std::panic::catch_unwind::<arrow!(tuple0 -> tuple0),tuple0>(new_tests::rustc_coverage__bad_counte... : chString))) in
    letb _ := assert (failure (ret_both (Explicit rejection by a phase in the Hax engine:
a node of kind [Dyn] have been found in the AST

Note: the error was labeled with context `reject_Dyn`.
 : chString)) (ret_both (core_models::result::impl__is_err::<tuple0,dyn(core_models::any::t_Any + core_models::marker::t_Send)>(std::panic::catch_unwind::<arrow!(tuple0 -> tuple0),tuple0>(new_tests::rustc_coverage__bad_counte... : chString))) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.
