(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

TODO: please implement the method `item'_HaxError`

Instance t_Easy_451154370 : t_Easy ((t_usize)) :=
  {
    implaabbcc_t_Easy_f_dft := fun  (self : t_usize)=>
      f_add (self) ((1 : t_usize));
  }.

Instance t_Easy_105475532 : t_Easy ((t_u32)) :=
  {
  }.

TODO: please implement the method `item'_HaxError`

Record S_record (v_A : Type) : Type :=
  {
    S_0 : t_usize;
    S_1 : v_A;
  }.
Arguments Build_S_record {_}.
Arguments S_0 {_}.
Arguments S_1 {_}.
#[export] Instance settable_S_record `{v_A : Type} : Settable _ :=
  settable! (Build_S_record (v_A := v_A)) <S_0; S_1>.
Notation "'S_S_record'" := Build_S_record.

Instance t_T1_61176507 : t_T1 ((t_S ((t_usize)))) :=
  {
    implaabbcc_t_T1_f_f1 := fun  (self : t_S ((t_usize)))=>
      f_add (0 self) (1 self);
    implaabbcc_t_T1_f_f2 := fun  (self : t_S ((t_usize)))=>
      1 self;
  }.

Instance t_T1_542696254 : t_T1 ((t_S ((bool)))) :=
  {
    implaabbcc_t_T1_f_f1 := fun  (self : t_S ((bool)))=>
      if
        1 self
      then
        0 self
      else
        (9 : t_usize);
    implaabbcc_t_T1_f_f2 := fun  (self : t_S ((bool)))=>
      f_add (0 self) ((1 : t_usize));
  }.

Instance t_T1_179125381 : t_T1 ((t_S ((t_String)))) :=
  {
    implaabbcc_t_T1_f_f1 := fun  (self : t_S ((t_String)))=>
      (0 : t_usize);
  }.
