(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition nested_control_flow '(_ : unit) : unit :=
  let x1 := f_add ((1 : t_i32)) (if
    (true : bool)
  then
    (0 : t_i32)
  else
    (1 : t_i32)) in
  let x2 := f_add ((1 : t_i32)) (match ((1 : t_i32),(2 : t_i32)) with
  | _ =>
    (0 : t_i32)
  end) in
  let x := (9 : t_i32) in
  let x3 := f_add ((1 : t_i32)) (f_add (x) ((1 : t_i32))) in
  tt.

Definition explicit_hoisting '(_ : unit) : unit :=
  let x1_tmp := if
    (true : bool)
  then
    (0 : t_i32)
  else
    (1 : t_i32) in
  let x1 := f_add ((1 : t_i32)) (x1_tmp) in
  let x2_tmp := match ((1 : t_i32),(2 : t_i32)) with
  | _ =>
    (0 : t_i32)
  end in
  let x2 := f_add ((1 : t_i32)) (x2_tmp) in
  let x3_tmp_x := (9 : t_i32) in
  let x3_tmp := f_add (x3_tmp_x) ((1 : t_i32)) in
  let x3 := f_add ((1 : t_i32)) (x3_tmp) in
  tt.

Definition complex_nesting '(_ : unit) : (unit*unit) :=
  let x1 := if
    (true : bool)
  then
    let y := if
      (false : bool)
    then
      let z := match tt with
      | _ =>
        (9 : t_i32)
      end in
      let z := f_add ((1 : t_i32)) (z) in
      f_add (z) ((1 : t_i32))
    else
      let z := (9 : t_i32) in
      let z := f_add (z) ((1 : t_i32)) in
      z in
    let y := f_add (y) ((1 : t_i32)) in
    f_add (y) ((1 : t_i32))
  else
    (0 : t_i32) in
  let x1 := f_add (x1) ((1 : t_i32)) in
  let x2 := match Option_Some ((89 : t_i32)) with
  | Option_Some (a) =>
    let y := f_add ((1 : t_i32)) (a) in
    let y := f_add (y) ((1 : t_i32)) in
    if
      f_eq (y) ((0 : t_i32))
    then
      let z := (9 : t_i32) in
      let z := f_add (f_add (z) (y)) ((1 : t_i32)) in
      z
    else
      (10 : t_i32)
  | Option_None =>
    let y := if
      (false : bool)
    then
      (9 : t_i32)
    else
      let z := (9 : t_i32) in
      let z := f_add (z) ((1 : t_i32)) in
      f_add (z) ((9 : t_i32)) in
    let y := f_add (y) ((1 : t_i32)) in
    y
  end in
  (tt,tt).
