(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Record S_record : Type :=
  {
    S_f_f : t_u32;
  }.


#[export] Instance settable_S_record : Settable _ :=
  settable! (Build_S_record) <S_f_f>.

Definition test '(_ : unit) : unit :=
  let _ := (9 : t_i32) in
  let _ := f_add ((9 : t_i32)) ((9 : t_i32)) in
  let _ := S ((9 : t_u32)) in
  let _ := S (f_add ((9 : t_u32)) ((9 : t_u32))) in
  let _ := f_f S (f_add ((9 : t_u32)) ((9 : t_u32))) in
  let _ := f_add (f_f S (f_add ((9 : t_u32)) ((9 : t_u32)))) ((9 : t_u32)) in
  let _ := if
    (true : bool)
  then
    f_add ((3 : t_i32)) ((4 : t_i32))
  else
    f_sub ((3 : t_i32)) ((4 : t_i32)) in
  let _ := if
    f_eq (f_add ((9 : t_i32)) ((9 : t_i32))) ((0 : t_i32))
  then
    f_add ((3 : t_i32)) ((4 : t_i32))
  else
    f_sub ((3 : t_i32)) ((4 : t_i32)) in
  let _ := if
    (true : bool)
  then
    let x := (9 : t_i32) in
    let _ := f_add ((3 : t_i32)) (x) in
    tt
  else
    let y := (19 : t_i32) in
    let _ := f_sub (f_add ((3 : t_i32)) (y)) ((4 : t_i32)) in
    tt in
  tt.
