(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Class t_FnOnce (v_Self : Type) (v_T : Type) : Type :=
  {
    f_Output : Type;
  }.
Arguments t_FnOnce (_) (_).

Definition func `{v_T : Type} `{v_U : Type} `{v_D : Type} `{v_F : Type} `{t_FnOnce (v_F) (v_T)} `{_.(f_Output) = v_U} `{t_FnOnce (v_D) (v_T)} `{_.(f_Output) = v_U} (d : v_D) (f : v_F) (u : v_U) : unit :=
  tt.
