(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition test_const_matching (x : t_u32) (c : ascii) (s : string) (b : bool) : t_u32 :=
  run (let x := match x with
  | 0 =>
    (42 : t_u32)
  | _ =>
    (0 : t_u32)
  end in
  let c := match c with
  | "a"%char =>
    (42 : t_u32)
  | _ =>
    (0 : t_u32)
  end in
  let s := match s with
  | "Hello"%string =>
    (42 : t_u32)
  | _ =>
    (0 : t_u32)
  end in
  let b := match b with
  | true =>
    (42 : t_u32)
  | false =>
    (0 : t_u32)
  end in
  let hoist6 := ControlFlow_Break (f_add (f_add (f_add (x) (c)) (s)) (b)) in
  ControlFlow_Continue (never_to_any (hoist6))).

Definition test_binding_subpattern_matching (x : (t_u8*(t_u8*t_u8))) : t_u8 :=
  failure (("Explicit rejection by a phase in the Hax engine:
a node of kind [As_pattern] have been found in the AST

Note: the error was labeled with context `reject_AsPattern`.
"%string : string)) (("(match (x) {
 Tuple2(0, pair @ Tuple2(a, b)) => {
 core_models::ops::arith::f_add(
 core_models::ops::arith::f_add(
 core_models::ops::arith::f_add(a, b),
 proj_proj_tuple0(pair),
 ),
 proj_proj_tuple..."%string : string)).
