(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition loop1 '(_ : unit) : t_u32 :=
  let x : t_u32 := (0 : t_u32) in
  let x := fold_range ((1 : t_u32)) ((10 : t_u32)) (fun x _ =>
    (true : bool)) (x) (fun x i =>
    f_add (x) (i)) in
  x.

Definition loop2 '(_ : unit) : t_u32 :=
  let x : t_u32 := (0 : t_u32) in
  let x := fold_range ((1 : t_u32)) ((10 : t_u32)) (fun x _ =>
    (true : bool)) (x) (fun x i =>
    let _ := if
      f_eq (i) ((5 : t_u32))
    then
      let hoist1 := ControlFlow_Break (x) in
      ControlFlow_Continue (never_to_any (hoist1))
    else
      ControlFlow_Continue (tt) in
    ControlFlow_Continue (let x := f_add (x) (i) in
    x)) in
  x.

Definition while_loop1 (s : t_u32) : t_u32 :=
  let x : t_u32 := s in
  let x := failure (("something is not implemented yet.
Unhandled loop kind

This is discussed in issue https://github.com/hacspec/hax/issues/933.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `FunctionalizeLoops`.
"%string : string)) (("{
 (loop {
 |x| {
 (if core_models::cmp::f_gt(x, 0) {
 {
 let _: tuple0 = {
 hax_lib::e_internal_loop_decreases(hax_lib::int::f_to_int(x))
 };
 {
 let x: int = { core_models::ops::arith::f_sub(x, 1) }..."%string : string)) in
  x.
Lemma while_loop1_ensures (s : t_u32) :
  let r := @while_loop1 (s : t_u32) in
  (true : bool) = true.
Proof. Admitted.










