(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition test (x : t_u8) `{f_gt (x) ((0 : t_u8)) = true} : t_u8 :=
  x.
Lemma test_ensures (x : t_u8) :
  forall (H_requires : f_gt (x) ((0 : t_u8)) = true),
  let r := @test (x : t_u8) H_requires in
  f_eq (r) (x) = true.
Proof. Admitted.

Definition test_proof (x : t_u8) `{f_gt (x) ((0 : t_u8)) = true} : t_u8 :=
  x.
Lemma test_proof_ensures (x : t_u8) :
  forall (H_requires : f_gt (x) ((0 : t_u8)) = true),
  let r := @test_proof (x : t_u8) H_requires in
  f_eq (r) (x) = true.
Proof. Admitted.
