(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition v_FORTYTWO : t_usize :=
  (42 : t_usize).

Definition v_MINUS_FORTYTWO : t_isize :=
  (-42 : t_isize).

Definition returns42 '(_ : unit) : t_usize :=
  v_FORTYTWO.

Definition add_two_numbers (x : t_usize) (y : t_usize) : t_usize :=
  f_add (x) (y).

Definition letBinding (x : t_usize) (y : t_usize) : t_usize :=
  let useless := tt in
  let result1 := f_add (x) (y) in
  let result2 := f_add (result1) ((2 : t_usize)) in
  f_add (result2) ((1 : t_usize)).

Definition closure '(_ : unit) : t_i32 :=
  let x := (41 : t_i32) in
  let f1 := fun y =>
    f_add (y) (x) in
  let f2 := fun y z =>
    f_add (f_add (y) (x)) (z) in
  let res1 := f_call (f1) (((1 : t_i32))) in
  let res2 := f_call (f2) (((2 : t_i32),(3 : t_i32))) in
  f_add (res1) (res2).

(Fatal error: something we considered as impossible occurred! Please report this by submitting an issue on GitHub!
Details: Could not find item with UID (Attr_payloads.UId.T.UId "6bb470a53f4a4e17badf402f7fffa8f4")


Note: the error was labeled with context `Coq backend`.
(* ERROR_ITEM *))
(Fatal error: something we considered as impossible occurred! Please report this by submitting an issue on GitHub!
Details: Could not find item with UID (Attr_payloads.UId.T.UId "07975eaf462a4b639ab3724308a46d46")


Note: the error was labeled with context `Coq backend`.
(* ERROR_ITEM *))
Definition binop_resugarings (x : t_u32) : t_u32 :=
  let add := f_add (x) ((1 : t_u32)) in
  let sub := f_sub (add) ((2 : t_u32)) in
  let mul := f_mul (sub) ((3 : t_u32)) in
  let rem := f_rem (mul) ((4 : t_u32)) in
  let div := f_div (rem) ((5 : t_u32)) in
  let rshift := f_shr (div) (x) in
  x.
