(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Definition t_Version : choice_type :=
  (uint_size × uint_size × uint_size).
Equations f_major (s : both t_Version) : both uint_size :=
  f_major s  :=
    bind_both s (fun x =>
      ret_both (fst (fst x) : uint_size)) : both uint_size.
Fail Next Obligation.
Equations f_minor (s : both t_Version) : both uint_size :=
  f_minor s  :=
    bind_both s (fun x =>
      ret_both (snd (fst x) : uint_size)) : both uint_size.
Fail Next Obligation.
Equations f_patch (s : both t_Version) : both uint_size :=
  f_patch s  :=
    bind_both s (fun x =>
      ret_both (snd x : uint_size)) : both uint_size.
Fail Next Obligation.
Equations Build_t_Version {f_major : both uint_size} {f_minor : both uint_size} {f_patch : both uint_size} : both (t_Version) :=
  Build_t_Version  :=
    bind_both f_patch (fun f_patch =>
      bind_both f_minor (fun f_minor =>
        bind_both f_major (fun f_major =>
          ret_both ((f_major,f_minor,f_patch) : (t_Version))))) : both (t_Version).
Fail Next Obligation.
Notation "'Build_t_Version' '[' x ']' '(' 'f_major' ':=' y ')'" := (Build_t_Version (f_major := y) (f_minor := f_minor x) (f_patch := f_patch x)).
Notation "'Build_t_Version' '[' x ']' '(' 'f_minor' ':=' y ')'" := (Build_t_Version (f_major := f_major x) (f_minor := y) (f_patch := f_patch x)).
Notation "'Build_t_Version' '[' x ']' '(' 'f_patch' ':=' y ')'" := (Build_t_Version (f_major := f_major x) (f_minor := f_minor x) (f_patch := y)).

#[global] Program Instance t_Version_t_Clone : t_Clone t_Version :=
  _.
Fail Next Obligation.
Hint Unfold t_Version_t_Clone.

#[global] Program Instance t_Version_t_Debug : t_Debug t_Version :=
  _.
Fail Next Obligation.
Hint Unfold t_Version_t_Debug.

#[global] Program Instance t_Version_t_StructuralPartialEq : t_StructuralPartialEq t_Version :=
  _.
Fail Next Obligation.
Hint Unfold t_Version_t_StructuralPartialEq.

#[global] Program Instance t_Version_t_PartialEq : t_PartialEq t_Version t_Version :=
  _.
Fail Next Obligation.
Hint Unfold t_Version_t_PartialEq.

#[global] Program Instance t_Version_t_Eq : t_Eq t_Version :=
  _.
Fail Next Obligation.
Hint Unfold t_Version_t_Eq.

#[global] Program Instance t_Version_t_PartialOrd : t_PartialOrd t_Version t_Version :=
  _.
Fail Next Obligation.
Hint Unfold t_Version_t_PartialOrd.

#[global] Program Instance t_Version_t_Ord : t_Ord t_Version :=
  _.
Fail Next Obligation.
Hint Unfold t_Version_t_Ord.

Equations impl_Version__new (major : both uint_size) (minor : both uint_size) (patch : both uint_size) : both t_Version :=
  impl_Version__new major minor patch  :=
    Build_t_Version (f_major := major) (f_minor := minor) (f_patch := patch) : both t_Version.
Fail Next Obligation.

(*item error backend*)
