(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)



Definition simple_assign (a : bool) : unit :=
  let x := a in
  let _ := black_box (x) in
  tt.

Definition assign_and (a : bool) (b : bool) : unit :=
  let x := andb (a) (b) in
  let _ := black_box (x) in
  tt.

Definition assign_or (a : bool) (b : bool) : unit :=
  let x := orb (a) (b) in
  let _ := black_box (x) in
  tt.

Definition assign_3_or_and (a : bool) (b : bool) (c : bool) : unit :=
  let x := orb (a) (andb (b) (c)) in
  let _ := black_box (x) in
  tt.

Definition assign_3_and_or (a : bool) (b : bool) (c : bool) : unit :=
  let x := orb (andb (a) (b)) (c) in
  let _ := black_box (x) in
  tt.

Definition foo (a : bool) : bool :=
  black_box (a).

Definition func_call (a : bool) (b : bool) : unit :=
  let _ := foo (andb (a) (b)) in
  tt.

Definition main '(_ : unit) : unit :=
  let _ := simple_assign ((true : bool)) in
  let _ := simple_assign ((false : bool)) in
  let _ := assign_and ((true : bool)) ((false : bool)) in
  let _ := assign_and ((true : bool)) ((true : bool)) in
  let _ := assign_and ((false : bool)) ((false : bool)) in
  let _ := assign_or ((true : bool)) ((false : bool)) in
  let _ := assign_or ((true : bool)) ((true : bool)) in
  let _ := assign_or ((false : bool)) ((false : bool)) in
  let _ := assign_3_or_and ((true : bool)) ((false : bool)) ((false : bool)) in
  let _ := assign_3_or_and ((true : bool)) ((true : bool)) ((false : bool)) in
  let _ := assign_3_or_and ((false : bool)) ((false : bool)) ((true : bool)) in
  let _ := assign_3_or_and ((false : bool)) ((true : bool)) ((true : bool)) in
  let _ := assign_3_and_or ((true : bool)) ((false : bool)) ((false : bool)) in
  let _ := assign_3_and_or ((true : bool)) ((true : bool)) ((false : bool)) in
  let _ := assign_3_and_or ((false : bool)) ((false : bool)) ((true : bool)) in
  let _ := assign_3_and_or ((false : bool)) ((true : bool)) ((true : bool)) in
  let _ := func_call ((true : bool)) ((false : bool)) in
  let _ := func_call ((true : bool)) ((true : bool)) in
  let _ := func_call ((false : bool)) ((false : bool)) in
  tt.
