(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

Equations say (message : both chString) : both 'unit :=
  say message  :=
    letb _ := black_box message in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations if_let (input : both (t_Option chString)) : both 'unit :=
  if_let input  :=
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (1 : int32)))) (fun _ =>
      ssp (fun _ =>
        ret_both (tt : 'unit) : (both 'unit))) (ret_both (tt : 'unit)) in
    letb _ := matchb input with
    | Option_Some_case x =>
      letb x := ret_both ((x) : (chString)) in
      letb _ := say x in
      ret_both (tt : 'unit)
    | _ =>
      letb _ := say (ret_both (none : chString)) in
      ret_both (tt : 'unit)
    end in
    letb _ := say (ret_both (done : chString)) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations if_let_chain (a : both (t_Option chString)) (b : both (t_Option chString)) : both 'unit :=
  if_let_chain a b  :=
    letb _ := ifb andb (failure (ret_both (something is not implemented yet.
Let-chains (e.g. `if let .. && let ..`) are not supported.

This is discussed in issue https://github.com/hacspec/hax/issues/2018.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `AST import`.
 : chString)) (ret_both ( : chString))) (failure (ret_both (something is not implemented yet.
Let-chains (e.g. `if let .. && let ..`) are not supported.

This is discussed in issue https://github.com/hacspec/hax/issues/2018.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `AST import`.
 : chString)) (ret_both ( : chString)))
    then letb _ := say x in
    letb _ := say y in
    ret_both (tt : 'unit)
    else letb _ := say (ret_both (not both : chString)) in
    ret_both (tt : 'unit) in
    letb _ := say (ret_both (done : chString)) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.

Equations main (_ : both 'unit) : both 'unit :=
  main _  :=
    letb _ := if_let (Option_Some (ret_both (x : chString))) in
    letb _ := if_let (Option_Some (ret_both (x : chString))) in
    letb _ := if_let Option_None in
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (8 : int32)))) (fun _ =>
      ssp (fun _ =>
        if_let_chain (Option_Some (ret_both (a : chString))) (Option_Some (ret_both (b : chString))) : (both 'unit))) (ret_both (tt : 'unit)) in
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (4 : int32)))) (fun _ =>
      ssp (fun _ =>
        if_let_chain (Option_Some (ret_both (a : chString))) Option_None : (both 'unit))) (ret_both (tt : 'unit)) in
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (2 : int32)))) (fun _ =>
      ssp (fun _ =>
        if_let_chain Option_None (Option_Some (ret_both (b : chString))) : (both 'unit))) (ret_both (tt : 'unit)) in
    letb _ := if_let_chain Option_None Option_None in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.
