(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)



Definition v_MAX : t_usize :=
  (10 : t_usize).

Record SafeIndex_record : Type :=
  {
    SafeIndex_f_i : t_usize;
  }.


#[export] Instance settable_SafeIndex_record : Settable _ :=
  settable! (Build_SafeIndex_record) <SafeIndex_f_i>.

Definition impl_SafeIndex__new (i : t_usize) : t_Option ((t_SafeIndex)) :=
  if
    f_lt (i) (v_MAX)
  then
    Option_Some (SafeIndex (i))
  else
    Option_None.

Definition impl_SafeIndex__as_usize (self : t_SafeIndex) : t_usize :=
  f_i self.

Instance t_Index_1057675040 `{v_T : Type} : t_Index ((t_Array (v_T) ((10 : t_usize)))) ((t_SafeIndex)) :=
  {
    implaabbcc_t_Index_f_Output := v_T;
    implaabbcc_t_Index_f_index := fun  (self : t_Array (v_T) ((10 : t_usize))) (index : t_SafeIndex)=>
      f_index (self) (f_i index);
  }.
