(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Record Dummy_record : Type :=
  {
  }.

#[export]
Notation "'Dummy_Dummy_record'" := Build_Dummy_record.







Definition impl_Dummy__f (self : t_Dummy) : t_Dummy :=
  self.
Lemma impl_Dummy__f_ensures (self : t_Dummy) :
  let self_e_future := @impl_Dummy__f (self : t_Dummy) in
  f_eq (self_e_future) (self_) = true.
Proof. Admitted.
