(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition f (x : t_u8) (y : t_u8) : t_u8 :=
  f_add ((1 : t_u8)) ((2 : t_u8)).

Record Foo_record : Type :=
  {
  }.

#[export]
Notation "'Foo_Foo_record'" := Build_Foo_record.

Definition impl_Foo__assoc_fn (self : t_Foo) (x : t_u8) : unit :=
  tt.

Instance t_ToString_470856928 : t_ToString ((t_Foo)) :=
  {
    implaabbcc_t_ToString_(* f_to_string *) := fun  (self : t_Foo)=>
      f_into (("Hello"%string : string));
  }.
