(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Record S_record : Type :=
  {
    S_f_f1 : t_usize;
  }.


#[export] Instance settable_S_record : Settable _ :=
  settable! (Build_S_record) <S_f_f1>.

Instance t_Default_737668931 : t_Default ((t_S)) :=
  {
    implaabbcc_t_Default_f_default := fun  (_ : unit)=>
      S ((0 : t_usize));
  }.

Definition test '(_ : unit) : t_S :=
  f_default (tt).
