(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Inductive t_E (v_T : Type) : Type :=
| E_C1 : t_u32 -> _
| E_C2 : v_T -> _.
Arguments E_C1 {_}.
Arguments E_C2 {_}.

Instance t_Default_720676046 `{v_T : Type} `{t_Default (v_T)} : t_Default ((t_E ((v_T)))) :=
  {
    implaabbcc_t_Default_f_default := fun  (_ : unit)=>
      E_C2 (f_default (tt));
  }.
