ADMIT_MODULES ?= Chacha20.Hacspec_helper.fst
FSTAR_INCLUDE_DIRS_EXTRA ?=
FSTAR_FLAGS_EXTRA ?=
HAX_EXTRACT_COMMAND ?= cargo hax extract -p chacha20 chacha20
HAX_EXTRACT_DIR ?= ../../../..

include Makefile.hax
