(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Equations main__v_B : both int32 :=
  main__v_B  :=
    ret_both (100 : int32) : both int32.
Fail Next Obligation.

Equations main (_ : both 'unit) : both 'unit :=
  main _  :=
    run (letb countdown := ret_both (0 : int32) in
    letb countdown := ifb ret_both (true : 'bool)
    then letb countdown := ret_both (10 : int32) in
    countdown
    else countdown in
    letm[choice_typeMonad.result_bind_code 'unit] '(countdown,x) := ifb countdown >.? (ret_both (7 : int32))
    then ControlFlow_Continue (letb countdown := countdown .- (ret_both (4 : int32)) in
    prod_b (countdown,main__v_B))
    else ifb countdown >.? (ret_both (2 : int32))
    then ControlFlow_Continue (letb countdown := ifb orb (orb (countdown <.? (ret_both (1 : int32))) (countdown >.? (ret_both (5 : int32)))) (countdown <> (ret_both (9 : int32)))
    then letb countdown := ret_both (0 : int32) in
    countdown
    else countdown in
    letb countdown := countdown .- (ret_both (5 : int32)) in
    prod_b (countdown,countdown))
    else letm[choice_typeMonad.result_bind_code 'unit] hoist1 := ControlFlow_Break (ret_both (tt : 'unit)) in
    ControlFlow_Continue (prod_b (countdown,never_to_any hoist1)) in
    letb countdown := ret_both (0 : int32) in
    letb countdown := ifb ret_both (true : 'bool)
    then letb countdown := ret_both (10 : int32) in
    countdown
    else countdown in
    letm[choice_typeMonad.result_bind_code 'unit] countdown := ifb countdown >.? (ret_both (7 : int32))
    then ControlFlow_Continue (letb countdown := countdown .- (ret_both (4 : int32)) in
    countdown)
    else ifb countdown >.? (ret_both (2 : int32))
    then ControlFlow_Continue (letb countdown := ifb orb (orb (countdown <.? (ret_both (1 : int32))) (countdown >.? (ret_both (5 : int32)))) (countdown <> (ret_both (9 : int32)))
    then letb countdown := ret_both (0 : int32) in
    countdown
    else countdown in
    letb countdown := countdown .- (ret_both (5 : int32)) in
    countdown)
    else letm[choice_typeMonad.result_bind_code 'unit] hoist2 := ControlFlow_Break (ret_both (tt : 'unit)) in
    ControlFlow_Continue countdown in
    letm[choice_typeMonad.result_bind_code 'unit] _ := ifb ret_both (true : 'bool)
    then letb countdown := ret_both (0 : int32) in
    letb countdown := ifb ret_both (true : 'bool)
    then letb countdown := ret_both (10 : int32) in
    countdown
    else countdown in
    ifb countdown >.? (ret_both (7 : int32))
    then ControlFlow_Continue (letb countdown := countdown .- (ret_both (4 : int32)) in
    ret_both (tt : 'unit))
    else ifb countdown >.? (ret_both (2 : int32))
    then ControlFlow_Continue (letb countdown := ifb orb (orb (countdown <.? (ret_both (1 : int32))) (countdown >.? (ret_both (5 : int32)))) (countdown <> (ret_both (9 : int32)))
    then letb countdown := ret_both (0 : int32) in
    countdown
    else countdown in
    letb countdown := countdown .- (ret_both (5 : int32)) in
    ret_both (tt : 'unit))
    else letm[choice_typeMonad.result_bind_code 'unit] hoist3 := ControlFlow_Break (ret_both (tt : 'unit)) in
    ControlFlow_Continue (never_to_any hoist3)
    else ControlFlow_Continue (ret_both (tt : 'unit)) in
    letb countdown := ret_both (0 : int32) in
    letb countdown := ifb ret_both (true : 'bool)
    then letb countdown := ret_both (1 : int32) in
    countdown
    else countdown in
    letm[choice_typeMonad.result_bind_code 'unit] '(countdown,z) := ifb countdown >.? (ret_both (7 : int32))
    then ControlFlow_Continue (letb countdown := countdown .- (ret_both (4 : int32)) in
    prod_b (countdown,ret_both (tt : 'unit)))
    else ifb countdown >.? (ret_both (2 : int32))
    then ControlFlow_Continue (letb countdown := ifb orb (orb (countdown <.? (ret_both (1 : int32))) (countdown >.? (ret_both (5 : int32)))) (countdown <> (ret_both (9 : int32)))
    then letb countdown := ret_both (0 : int32) in
    countdown
    else countdown in
    letb countdown := countdown .- (ret_both (5 : int32)) in
    prod_b (countdown,ret_both (tt : 'unit)))
    else letb should_be_reachable := countdown in
    letb _ := e_print (impl_1__new_const (array_from_list [ret_both (reached
 : chString)])) in
    letb _ := ret_both (tt : 'unit) in
    letm[choice_typeMonad.result_bind_code 'unit] hoist4 := ControlFlow_Break (ret_both (tt : 'unit)) in
    ControlFlow_Continue (prod_b (countdown,never_to_any hoist4)) in
    letm[choice_typeMonad.result_bind_code 'unit] '(countdown,w) := ifb countdown >.? (ret_both (7 : int32))
    then ControlFlow_Continue (letb countdown := countdown .- (ret_both (4 : int32)) in
    prod_b (countdown,ret_both (tt : 'unit)))
    else ifb countdown >.? (ret_both (2 : int32))
    then ControlFlow_Continue (letb countdown := ifb orb (orb (countdown <.? (ret_both (1 : int32))) (countdown >.? (ret_both (5 : int32)))) (countdown <> (ret_both (9 : int32)))
    then letb countdown := ret_both (0 : int32) in
    countdown
    else countdown in
    letb countdown := countdown .- (ret_both (5 : int32)) in
    prod_b (countdown,ret_both (tt : 'unit)))
    else letm[choice_typeMonad.result_bind_code 'unit] hoist5 := ControlFlow_Break (ret_both (tt : 'unit)) in
    ControlFlow_Continue (prod_b (countdown,never_to_any hoist5)) in
    ControlFlow_Continue (ret_both (tt : 'unit))) : both 'unit.
Fail Next Obligation.
