authors:
  franziskus:
    name: Franziskus Kiefer
    description: Creator
    avatar: https://cryspen.com/images/franziskus_hu_bbe22df7ad1ab9d5.jpg
  lucas:
    name: Lucas Franceschino
    description: Creator
    avatar: https://cryspen.com/images/lucas_hu_32c53e525a1b3324.jpg
  clement:
    name: Clement Blaudeau
    description: Engineer
    avatar: https://cryspen.com/images/clement_hu_da447295a2bd189d.jpg
  maxime:
    name: Maxime Buyse
    description: Engineer
    avatar: https://cryspen.com/images/maxime_hu_8da610acc29fd826.png
