use hax_lib_macros_types::{AttrPayload, ItemStatus};

use crate::{ast::HasMetadata, phase::Phase};

/// Drop any item marked with a hax attribute whose payload deserializes to
/// `AttrPayload::ItemStatus(ItemStatus::Included { late_skip: true })`.
///
/// Items with such a "late-skip" attribute are typically generated by hax
/// attributes.
#[derive(Default, Debug)]
pub struct DropSkipLate;

impl Phase for DropSkipLate {
    fn apply(&self, items: &mut Vec<crate::ast::Item>) {
        items.retain_mut(|item| {
            !item.metadata().hax_attributes().any(|attr| {
                matches!(
                    attr,
                    AttrPayload::ItemStatus(ItemStatus::Included { late_skip: true })
                )
            })
        });
    }
}
