(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition inlined_instance (a : bool) (b : bool) : bool :=
  andb (a) (b).

Definition main '(_ : unit) : unit :=
  let _ := inlined_instance ((true : bool)) ((false : bool)) in
  let _ := inlined_instance ((false : bool)) ((true : bool)) in
  let _ := inlined_instance ((true : bool)) ((true : bool)) in
  tt.
