(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Definition t_A : choice_type :=
  'unit.
Equations Build_t_A : both (t_A) :=
  Build_t_A  :=
    ret_both (tt (* Empty tuple *) : (t_A)) : both (t_A).
Fail Next Obligation.

Definition t_B : choice_type :=
  'unit.
Equations Build_t_B : both (t_B) :=
  Build_t_B  :=
    ret_both (tt (* Empty tuple *) : (t_B)) : both (t_B).
Fail Next Obligation.

Equations impl__mkb (self : both t_A) : both t_B :=
  impl__mkb self  :=
    B : both t_B.
Fail Next Obligation.

Equations impl__mka (self : both t_B) : both t_A :=
  impl__mka self  :=
    A : both t_A.
Fail Next Obligation.
