-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sha3]: specs (statements of correctness)
import Aeneas
import CoreModels
import Hax
import Sha3.Extraction.Types
import Sha3.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sha3


/-- [sha3::implementation::theta::post]:
    Source: 'sha3/src/lib.rs', lines 201:4-204:60 -/
@[reducible]
def implementation.theta.post
  (st : implementation.KeccakState Std.U64 1#usize)
  (p : ((implementation.KeccakState Std.U64 1#usize) × (Array Std.U64
  5#usize))) :
  Result Bool
  := do
  let (st_future, d) := p
  let res ←
    implementation.KeccakState.Insts.CoreCloneClone.clone
      core.U64.Insts.CoreCloneClone U64.Insts.Sha3ImplementationKeccakItem1
      st_future
  let res1 ←
    implementation.KeccakState.rho U64.Insts.Sha3ImplementationKeccakItem1 res
      d
  let a ← reference.theta st.st
  let a1 ← reference.rho a
  core.Array.Insts.CoreCmpPartialEqArray.eq core.U64.Insts.CoreCmpPartialEqU64
    res1.st a1

def implementation.theta.spec (st : implementation.KeccakState Std.U64 1#usize)
  : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  implementation.theta st
  ⦃ ⇓ res => ⌜ (implementation.theta.post st res.swap).holds ⌝ ⦄


/-- [sha3::implementation::pi::post]:
    Source: 'sha3/src/lib.rs', lines 213:4-213:66 -/
@[reducible]
def implementation.pi.post
  (st : implementation.KeccakState Std.U64 1#usize)
  (st_future : implementation.KeccakState Std.U64 1#usize) :
  Result Bool
  := do
  let a ← reference.pi st.st
  core.Array.Insts.CoreCmpPartialEqArray.eq core.U64.Insts.CoreCmpPartialEqU64
    st_future.st a

def implementation.pi.spec (st : implementation.KeccakState Std.U64 1#usize)
  : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  implementation.pi st
  ⦃ ⇓ res => ⌜ (implementation.pi.post st res).holds ⌝ ⦄


/-- [sha3::implementation::chi::post]:
    Source: 'sha3/src/lib.rs', lines 222:4-222:67 -/
@[reducible]
def implementation.chi.post
  (st : implementation.KeccakState Std.U64 1#usize)
  (st_future : implementation.KeccakState Std.U64 1#usize) :
  Result Bool
  := do
  let a ← reference.chi st.st
  core.Array.Insts.CoreCmpPartialEqArray.eq core.U64.Insts.CoreCmpPartialEqU64
    st_future.st a

def implementation.chi.spec (st : implementation.KeccakState Std.U64 1#usize)
  : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  implementation.chi st
  ⦃ ⇓ res => ⌜ (implementation.chi.post st res).holds ⌝ ⦄


/-- [sha3::implementation::iota::pre]:
    Source: 'sha3/src/lib.rs', lines 231:4-231:50 -/
@[reducible]
def implementation.iota.pre
  (st : implementation.KeccakState Std.U64 1#usize) (i : Std.Usize) :
  Result Bool
  := do
  let s ← lift (Array.to_slice implementation.ROUNDCONSTANTS)
  let i1 ← core.slice.Slice.len s
  ok (i < i1)

/-- [sha3::implementation::iota::post]:
    Source: 'sha3/src/lib.rs', lines 232:4-232:71 -/
@[reducible]
def implementation.iota.post
  (st : implementation.KeccakState Std.U64 1#usize) (i : Std.Usize)
  (st_future : implementation.KeccakState Std.U64 1#usize) :
  Result Bool
  := do
  let a ← reference.iota st.st i
  core.Array.Insts.CoreCmpPartialEqArray.eq core.U64.Insts.CoreCmpPartialEqU64
    st_future.st a

def implementation.iota.spec (st : implementation.KeccakState Std.U64 1#usize)
  (i : Std.Usize) : Prop :=
  (implementation.iota.pre st i).holds →
  ⦃ ⌜ True ⌝ ⦄
  implementation.iota st i
  ⦃ ⇓ res => ⌜ (implementation.iota.post st i res).holds ⌝ ⦄


/-- [sha3::implementation::round::pre]:
    Source: 'sha3/src/lib.rs', lines 241:4-241:50 -/
@[reducible]
def implementation.round.pre
  (st : implementation.KeccakState Std.U64 1#usize) (i : Std.Usize) :
  Result Bool
  := do
  let s ← lift (Array.to_slice implementation.ROUNDCONSTANTS)
  let i1 ← core.slice.Slice.len s
  ok (i < i1)

/-- [sha3::implementation::round::post]:
    Source: 'sha3/src/lib.rs', lines 242:4-246:11 -/
@[reducible]
def implementation.round.post
  (st : implementation.KeccakState Std.U64 1#usize) (i : Std.Usize)
  (st_future : implementation.KeccakState Std.U64 1#usize) :
  Result Bool
  := do
  let a ← reference.theta st.st
  let a1 ← reference.rho a
  let a2 ← reference.pi a1
  let a3 ← reference.chi a2
  let a4 ← reference.iota a3 i
  core.Array.Insts.CoreCmpPartialEqArray.eq core.U64.Insts.CoreCmpPartialEqU64
    st_future.st a4

def implementation.round.spec (st : implementation.KeccakState Std.U64 1#usize)
  (i : Std.Usize) : Prop :=
  (implementation.round.pre st i).holds →
  ⦃ ⌜ True ⌝ ⦄
  implementation.round st i
  ⦃ ⇓ res => ⌜ (implementation.round.post st i res).holds ⌝ ⦄

end sha3
