-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sha3]: type definitions
import Aeneas
import CoreModels
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace sha3

/-- Trait declaration: [sha3::implementation::KeccakItem]
    Source: 'sha3/src/lib.rs', lines 132:4-135:5 -/
structure implementation.KeccakItem (Self : Type) (N : Std.Usize) where
  corecloneCloneInst : core.clone.Clone Self
  coremarkerCopyInst : core.marker.Copy Self
  xor_constant : Self → Std.U64 → Result Self

/-- [sha3::implementation::KeccakState]
    Source: 'sha3/src/lib.rs', lines 138:4-140:5 -/
structure implementation.KeccakState (T : Type) (N : Std.Usize) where
  st : Array T 25#usize

end sha3
