(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Definition t_Test {v_N : both uint_size} : choice_type :=
  'unit.
Equations Build_t_Test {v_N : both uint_size} : both (t_Test) :=
  Build_t_Test  :=
    ret_both (tt (* Empty tuple *) : (t_Test)) : both (t_Test).
Fail Next Obligation.

Equations impl__A {v_N : both uint_size} : both (t_Test (both uint_size)) :=
  impl__A  :=
    Test : both (t_Test (both uint_size)).
Fail Next Obligation.

Equations test (_ : both 'unit) : both (t_Test (both uint_size)) :=
  test _  :=
    impl__A (ret_both (1 : uint_size)) : both (t_Test (both uint_size)).
Fail Next Obligation.
