tests:
  attr::impl_:
    - json
    - coq
    - fstar
    - fstar-lax
    - lean
  attr::module:
    - json
    - coq
    - lean
    - fstar
    - fstar-lax
  attr::off_on_sandwich:
    - json
    - coq
    - lean
    - fstar
    - fstar-lax
  attr::trait_impl_inherit:
    - json
    - lean
  auxiliary::discard_all_helper:
    - json
    - coq
    - lean
    - fstar
    - fstar-lax
  auxiliary::used_crate:
    - json
    - coq
    - fstar
    - lean
  auxiliary::used_inline_crate:
    - json
    - coq
    - fstar
    - lean
  condition::conditions:
    - json
    - coq
    - fstar 
    - fstar-lax
    - lean
  mcdc::condition_limit:
    - json
    - lean
  mcdc::if_:
    - json
    - coq
    - fstar 
    - fstar-lax
    - lean
  mcdc::inlined_expressions:
    - json
    - coq
    - fstar 
    - fstar-lax
    - lean
  mcdc::nested_if:
    - json
    - coq
    - fstar 
    - fstar-lax
    - lean
  mcdc::non_control_flow:
    - json
    - coq
    - fstar 
    - fstar-lax
    - lean
  abort:
    - json
    - lean
    - fstar
    - fstar-lax
  assert:
    - json
    - lean
    - fstar
    - fstar-lax
  assert_ne:
    - json
    - coq
    - fstar
    - fstar-lax
  assert_not:
    - json
    - coq
    - lean
    - fstar
    - fstar-lax
  closure_macro:
    - json
    - coq
    - fstar
    - lean
  closure_unit_return:
    - json
    - coq
    - lean
    - fstar
    - fstar-lax
  color:
    - json
    - lean
    - coq
    - fstar
    - fstar-lax
  conditions:
    - json
    - coq
    - fstar
    - lean
  continue_:
    - json
    - fstar
  dead_code:
    - json
    - coq
    - fstar
    - lean
  drop_trait:
    - json
    - coq
    - fstar
    - fstar-lax
    - lean
  fn_sig_into_try:
    - json
    - coq
    - lean
    - fstar
    - fstar-lax
  generics:
    - json
    - coq
    - fstar
  if_:
    - json
    - coq
    - fstar
    - lean
  if_else:
    - json
    - coq
    - fstar
    - lean
  if_not:
    - json
    - lean
    - coq
    - fstar
    - fstar-lax
  ignore_map:
    - json
    - coq
    - lean
    - fstar
    - fstar-lax
  ignore_run:
    - json
    - coq
    - lean
    - fstar
    - fstar-lax
  inline_dead:
    - json
    - coq
    - fstar
  inline:
    - json
    - lean
    - coq
    - fstar
  inner_items:
    - json
    - lean
  issue_83601:
    - json
    - coq
    - fstar
    - fstar-lax
    - lean
  lazy_boolean:
    - json
    - coq
    - fstar
    - lean
  let_else_loop:
    - json
  long_and_wide:
    - json
    - lean
    - fstar
    - fstar-lax
    - coq

  loop_break:
    - json
    - lean

  loop_break_value:
    - json
    - lean

  loops_branches:
    - json
    - fstar
    - lean

  macro_in_closure:
    - json
    - lean
    - fstar
    - fstar-lax
    - coq

  match_or_pattern:
    - json
    - fstar
    - coq

  nested_loops:
    - json
    - fstar
    - lean

  no_cov_crate:
    - json
    - lean
    - fstar
    - coq

  no_spans:
    - json
    - lean
    - fstar
    - coq

  no_spans_if_not:
    - json
    - lean
    - fstar
    - fstar-lax
    - coq

  overflow:
    - json
    - fstar
    - fstar-lax
    - lean

  panic_unwind:
    - json
    - lean
    - fstar
    - fstar-lax

  partial_eq:
    - json
    - fstar
    - coq
    - fstar-lax
    - lean

  simple_loop:
    - json
    - lean

  simple_match:
    - json
    - lean

  sort_groups:
    - json
    - lean
    - fstar
    - coq

  test_harness:
    - json
    - lean
    - fstar
    - fstar-lax
    - coq

  tight_inf_loop:
    - json
    - lean

  trivial:
    - json
    - lean
    - fstar
    - fstar-lax
    - coq

  try_error_result:
    - json
    - lean
    - fstar
    - coq

  unicode:
    - json
    - coq
    - fstar

  unused:
    - json
    - fstar

  unused_mod:
    - json
    - lean
    - fstar
    - fstar-lax
    - coq

  while_:
    - json
    - lean
    - fstar
    - fstar-lax
  
  while_early_ret:
    - json
    - fstar
    - fstar-lax
