(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition let_else (opt : t_Option ((t_u32))) : bool :=
  run (match opt with
  | Option_Some (x) =>
    ControlFlow_Continue ((true : bool))
  | _ =>
    ControlFlow_Break ((false : bool))
  end).

Definition let_else_different_type (opt : t_Option ((t_u32))) : bool :=
  run (let hoist1 := match opt with
  | Option_Some (x) =>
    ControlFlow_Continue (Option_Some (f_add (x) ((1 : t_u32))))
  | _ =>
    ControlFlow_Break ((false : bool))
  end in
  ControlFlow_Continue (let_else (hoist1))).
