mod a {
    use hax_lib_protocol::{state_machine::*, ProtocolError, ProtocolResult};

    use super::Message;

    // ==== A states ====
    pub struct A0 {
        data: u8,
    }

    pub struct A1 {}

    pub struct A2 {
        #[allow(dead_code)]
        received: u8,
    }

    // ==== A initialization ====
    #[hax_lib_protocol_macros::init(A0)]
    fn init_a(prologue: Vec<u8>) -> ProtocolResult<A0> {
        if prologue.len() < 1 {
            Err(ProtocolError::InvalidPrologue)
        } else {
            Ok(A0 { data: prologue[0] })
        }
    }

    // The following generated by macro:
    /* #[hax_lib_macros::exclude]
    impl TryFrom<Vec<u8>> for A0 {
        type Error = ProtocolError;

        fn try_from(value: Vec<u8>) -> Result<Self, Self::Error> {
            init_a(value)
        }
    }

    #[hax_lib_macros::exclude]
    impl InitialState for A0 {
        fn init(prologue: Option<Vec<u8>>) -> ProtocolResult<Self> {
            if let Some(prologue) = prologue {
                prologue.try_into()
            } else {
                Err(ProtocolError::InvalidPrologue)
            }
        }
    } */

    // ==== A state transistion functions ====
    #[hax_lib_protocol_macros::write(A0, A1, Message)]
    fn write_ping(state: A0) -> ProtocolResult<(A1, Message)> {
        Ok((A1 {}, Message::Ping(state.data)))
    }

    // The following generated by macro:
    /*#[hax_lib_macros::exclude]
    impl TryFrom<A0> for (A1, Message) {
        type Error = ProtocolError;

        fn try_from(value: A0) -> Result<Self, Self::Error> {
            write_ping(value)
        }
    }

    #[hax_lib_macros::exclude]
    impl WriteState for A0 {
        type NextState = A1;
        type Message = Message;

        fn write(self) -> ProtocolResult<(Self::NextState, Message)> {
            self.try_into()
        }
    }*/

    #[hax_lib_protocol_macros::read(A1, A2, Message)]
    fn read_pong(_state: A1, msg: Message) -> ProtocolResult<A2> {
        match msg {
            Message::Ping(_) => Err(ProtocolError::InvalidMessage),
            Message::Pong(received) => Ok(A2 { received }),
        }
    }

    // The following generated by macro:
    /*#[hax_lib_macros::exclude]
    impl TryFrom<(A1, Message)> for A2 {
        type Error = ProtocolError;

        fn try_from((state, msg): (A1, Message)) -> Result<Self, Self::Error> {
            read_pong(state, msg)
        }
    }
    #[hax_lib_macros::exclude]
    impl ReadState<A2> for A1 {
        type Message = Message;
        fn read(self, msg: Message) -> ProtocolResult<A2> {
            A2::try_from((self, msg))
        }
    }*/
}
mod b {
    use hax_lib_protocol::{state_machine::*, ProtocolError, ProtocolResult};

    use super::Message;

    // ==== B states ====
    pub struct B0 {}

    pub struct B1 {
        received: u8,
    }

    // An alternative successor of B0 to show read alternatives
    pub struct B1alt {}

    pub struct B2 {}

    // ==== B initialization ====
    #[hax_lib_protocol_macros::init_empty(B0)]
    fn init_b() -> ProtocolResult<B0> {
        Ok(B0 {})
    }

    // The following generated by macro:
    // #[hax_lib_macros::exclude]
    // impl InitialState for B0 {
    //     fn init(prologue: Option<Vec<u8>>) -> ProtocolResult<Self> {
    //         if let Some(_) = prologue {
    //             Err(ProtocolError::InvalidPrologue)
    //         } else {
    //             init_b()
    //         }
    //     }
    // }

    // ==== B state transistion functions ====
    #[hax_lib_protocol_macros::read(B0, B1, Message)]
    fn read_ping(_state: B0, msg: Message) -> ProtocolResult<B1> {
        match msg {
            Message::Ping(received) => Ok(B1 { received }),
            Message::Pong(_) => Err(ProtocolError::InvalidMessage),
        }
    }

    // The following generated by macro:
    /*#[hax_lib_macros::exclude]
    impl TryFrom<(B0, Message)> for B1 {
        type Error = ProtocolError;

        fn try_from((state, msg): (B0, Message)) -> Result<Self, Self::Error> {
            read_ping(state, msg)
        }
    }

    #[hax_lib_macros::exclude]
    impl ReadState<B1> for B0 {
        type Message = Message;
        fn read(self, msg: Message) -> Result<B1, ProtocolError> {
            B1::try_from((self, msg))
        }
    }*/

    #[hax_lib_protocol_macros::read(B0, B1alt, Message)]
    fn read_ping_alt(_state: B0, msg: Message) -> ProtocolResult<B1alt> {
        match msg {
            Message::Ping(received) if received == 42 => Ok(B1alt {}),
            _ => Err(ProtocolError::InvalidMessage),
        }
    }

    // The following generated by macro:
    /*#[hax_lib_macros::exclude]
    impl TryFrom<(B0, Message)> for B1alt {
        type Error = ProtocolError;

        fn try_from((state, msg): (B0, Message)) -> Result<Self, Self::Error> {
            read_ping_alt(state, msg)
        }
    }

    #[hax_lib_macros::exclude]
    impl ReadState<B1alt> for B0 {
        type Message = Message;
        fn read(self, msg: Message) -> Result<B1alt, ProtocolError> {
            B1alt::try_from((self, msg))
        }
    }*/

    #[hax_lib_protocol_macros::write(B1, B2, Message)]
    fn write_pong(state: B1) -> ProtocolResult<(B2, Message)> {
        Ok((B2 {}, Message::Pong(state.received)))
    }

    // The following generated by macro:
    /*#[hax_lib_macros::exclude]
    impl TryFrom<B1> for (B2, Message) {
        type Error = ProtocolError;

        fn try_from(value: B1) -> Result<Self, Self::Error> {
            write_pong(value)
        }
    }

    #[hax_lib_macros::exclude]
    impl WriteState for B1 {
        type Message = Message;
        type NextState = B2;

        fn write(self) -> Result<(Self::NextState, Message), ProtocolError> {
            self.try_into()
        }
    }*/
}

#[hax_lib::protocol_messages]
pub enum Message {
    Ping(u8),
    Pong(u8),
}

#[test]
fn run() {
    use a::A0;
    use b::{B0, B1};
    use hax_lib_protocol::state_machine::{InitialState, ReadState, WriteState};
    let a = A0::init(Some(vec![1])).unwrap();
    let b = B0::init(None).unwrap();

    let (a, msg) = a.write().unwrap();
    let b: B1 = b.read(msg).unwrap();

    let (_b, msg) = b.write().unwrap();
    let _a = a.read(msg).unwrap();
}
