(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Record Test_record (v_N : t_usize) : Type :=
  {
  }.
Arguments Build_Test_record {_}.
#[export]
Notation "'Test_Test_record'" := Build_Test_record.

Definition impl__A `{v_N : t_usize} : t_Test (v_N) :=
  Test.

Definition test '(_ : unit) : t_Test ((1 : t_usize)) :=
  impl__A ((1 : t_usize)).
