(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Record Foo_record : Type :=
  {
    Foo_0 : t_u32;
  }.


#[export] Instance settable_Foo_record : Settable _ :=
  settable! (Build_Foo_record) <Foo_0>.
Notation "'Foo_Foo_record'" := Build_Foo_record.









Definition eq_good '(_ : unit) : unit :=
  let _ := e_print (impl_1__new_const ([("a
"%string : string)])) in
  let _ := tt in
  let _ := match (Foo ((1 : t_u32)),Foo ((1 : t_u32))) with
  | (left_val,right_val) =>
    assert (f_eq (left_val) (right_val))
  end in
  tt.

Definition eq_good_message '(_ : unit) : unit :=
  let _ := e_print (impl_1__new_const ([("b
"%string : string)])) in
  let _ := tt in
  let _ := match (Foo ((1 : t_u32)),Foo ((1 : t_u32))) with
  | (left_val,right_val) =>
    assert (f_eq (left_val) (right_val))
  end in
  tt.

Definition ne_good '(_ : unit) : unit :=
  let _ := e_print (impl_1__new_const ([("c
"%string : string)])) in
  let _ := tt in
  let _ := match (Foo ((1 : t_u32)),Foo ((3 : t_u32))) with
  | (left_val,right_val) =>
    assert (f_not (f_eq (left_val) (right_val)))
  end in
  tt.

Definition ne_good_message '(_ : unit) : unit :=
  let _ := e_print (impl_1__new_const ([("d
"%string : string)])) in
  let _ := tt in
  let _ := match (Foo ((1 : t_u32)),Foo ((3 : t_u32))) with
  | (left_val,right_val) =>
    assert (f_not (f_eq (left_val) (right_val)))
  end in
  tt.

Definition eq_bad '(_ : unit) : unit :=
  let _ := e_print (impl_1__new_const ([("e
"%string : string)])) in
  let _ := tt in
  let _ := match (Foo ((1 : t_u32)),Foo ((3 : t_u32))) with
  | (left_val,right_val) =>
    assert (f_eq (left_val) (right_val))
  end in
  tt.

Definition eq_bad_message '(_ : unit) : unit :=
  let _ := e_print (impl_1__new_const ([("f
"%string : string)])) in
  let _ := tt in
  let _ := match (Foo ((1 : t_u32)),Foo ((3 : t_u32))) with
  | (left_val,right_val) =>
    assert (f_eq (left_val) (right_val))
  end in
  tt.

Definition ne_bad '(_ : unit) : unit :=
  let _ := e_print (impl_1__new_const ([("g
"%string : string)])) in
  let _ := tt in
  let _ := match (Foo ((1 : t_u32)),Foo ((1 : t_u32))) with
  | (left_val,right_val) =>
    assert (f_not (f_eq (left_val) (right_val)))
  end in
  tt.

Definition ne_bad_message '(_ : unit) : unit :=
  let _ := e_print (impl_1__new_const ([("h
"%string : string)])) in
  let _ := tt in
  let _ := match (Foo ((1 : t_u32)),Foo ((1 : t_u32))) with
  | (left_val,right_val) =>
    assert (f_not (f_eq (left_val) (right_val)))
  end in
  tt.

Definition main '(_ : unit) : unit :=
  let _ := eq_good (tt) in
  let _ := eq_good_message (tt) in
  let _ := ne_good (tt) in
  let _ := ne_good_message (tt) in
  let _ := assert (failure (("Explicit rejection by a phase in the Hax engine:
a node of kind [Dyn] have been found in the AST

Note: the error was labeled with context `reject_Dyn`.
"%string : string)) (("core_models::result::impl__is_err::<tuple0,dyn(core_models::any::t_Any + core_models::marker::t_Send)>(std::panic::catch_unwind::<arrow!(tuple0 -> tuple0),tuple0>(new_tests::rustc_coverage__bad_counte..."%string : string))) in
  let _ := assert (failure (("Explicit rejection by a phase in the Hax engine:
a node of kind [Dyn] have been found in the AST

Note: the error was labeled with context `reject_Dyn`.
"%string : string)) (("core_models::result::impl__is_err::<tuple0,dyn(core_models::any::t_Any + core_models::marker::t_Send)>(std::panic::catch_unwind::<arrow!(tuple0 -> tuple0),tuple0>(new_tests::rustc_coverage__bad_counte..."%string : string))) in
  let _ := assert (failure (("Explicit rejection by a phase in the Hax engine:
a node of kind [Dyn] have been found in the AST

Note: the error was labeled with context `reject_Dyn`.
"%string : string)) (("core_models::result::impl__is_err::<tuple0,dyn(core_models::any::t_Any + core_models::marker::t_Send)>(std::panic::catch_unwind::<arrow!(tuple0 -> tuple0),tuple0>(new_tests::rustc_coverage__bad_counte..."%string : string))) in
  let _ := assert (failure (("Explicit rejection by a phase in the Hax engine:
a node of kind [Dyn] have been found in the AST

Note: the error was labeled with context `reject_Dyn`.
"%string : string)) (("core_models::result::impl__is_err::<tuple0,dyn(core_models::any::t_Any + core_models::marker::t_Send)>(std::panic::catch_unwind::<arrow!(tuple0 -> tuple0),tuple0>(new_tests::rustc_coverage__bad_counte..."%string : string))) in
  tt.
