(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

(*Explicit rejection by a phase in the Hax engine:
a node of kind [Trait_item_default] have been found in the AST

Note: the error was labeled with context `reject_TraitItemDefault`.
 todo(item)*)

Definition t_S : choice_type :=
  'unit.
Equations Build_t_S : both (t_S) :=
  Build_t_S  :=
    ret_both (tt (* Empty tuple *) : (t_S)) : both (t_S).
Fail Next Obligation.

#[global] Program Instance t_S_t_T : t_T t_S :=
  let f_f := fun  (self : both t_S) => letb _ := e_print (impl_1__new_const (array_from_list [ret_both (impl S
 : chString)])) in
  letb _ := ret_both (tt : 'unit) in
  ret_both (tt : 'unit) : both 'unit in
  {| f_f := (@f_f)|}.
Fail Next Obligation.
Hint Unfold t_S_t_T.

Equations main (_ : both 'unit) : both 'unit :=
  main _  :=
    letb _ := f_f S in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.
