(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Record StructWithGenericBounds_record (v_T : Type) `{t_Clone (v_T)} : Type :=
  {
    StructWithGenericBounds_0 : v_T;
  }.
Arguments Build_StructWithGenericBounds_record {_} {_}.
Arguments StructWithGenericBounds_0 {_} {_}.
#[export] Instance settable_StructWithGenericBounds_record `{v_T : Type} `{t_Clone (v_T)} : Settable _ :=
  settable! (Build_StructWithGenericBounds_record (v_T := v_T)) <StructWithGenericBounds_0>.
Notation "'StructWithGenericBounds_StructWithGenericBounds_record'" := Build_StructWithGenericBounds_record.
