#!/usr/bin/env bash
# Rebuilds `Snapshots/`: one symlink per Lean snapshot to type-check, named
# after the test module so Lean's diagnostics name the test. The farm exists
# because every snapshot file is called `new_tests.lean` and Lean derives
# module names from paths. Symlinks, not copies, so Lake's content traces
# survive a refresh. `<test>/legacy-lean-xfail/` holds the ones to skip.
set -euo pipefail

here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
root=$(git -C "$here" rev-parse --show-toplevel)

rm -rf -- "$here/Snapshots" "$here/Snapshots.lean"
mkdir -p -- "$here/Snapshots"

{
  echo '-- Generated by refresh.sh; the library root, so that `lake build`'
  echo '-- reaches every snapshot module.'
} > "$here/Snapshots.lean"

count=0
while IFS= read -r source; do
  snapshot=${source#"$root/tests/snapshots/"}
  snapshot=${snapshot%/legacy-lean/new_tests.lean}
  # `legacy/cli/include-flag/lib` -> `legacy__cli__include_flag__lib`.
  name=${snapshot//\//__}
  name=${name//-/_}
  ln -s -- "$source" "$here/Snapshots/$name.lean"
  echo "import Snapshots.$name" >> "$here/Snapshots.lean"
  count=$((count + 1))
done < <(find "$root/tests/snapshots" -path '*/legacy-lean/new_tests.lean' | sort)

if [ "$count" -eq 0 ]; then
  echo "error: found no Lean snapshot to check under $root/tests/snapshots" >&2
  exit 1
fi

echo "refreshed $count Lean snapshot module(s)"
