(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

(* NotImplementedYet *)

Inductive t_Uninhabited : Type :=
.

Definition t_Uninhabited_cast_to_repr (x : t_Uninhabited) : t_Never :=
  match x with
  end.

Inductive t_Trivial : Type :=
| Trivial_Value.


Definition t_Trivial_cast_to_repr (x : t_Trivial) : t_isize :=
  match x with
  | Trivial_Value =>
    (0 : t_isize)
  end.

Definition consume `{v_T : Type} (x : v_T) : unit :=
  let _ := black_box (x) in
  tt.

Definition e_uninhabited (x : t_Uninhabited) : unit :=
  let _ := fold_range ((0 : t_i32)) ((1 : t_i32)) (fun _ _ =>
    (true : bool)) (tt) (fun _ _ =>
    tt) in
  let _ := never_to_any (match x with
  end) in
  never_to_any (consume (("done"%string : string))).

Definition trivial (x : t_Trivial) : unit :=
  let _ := fold_range ((0 : t_i32)) ((1 : t_i32)) (fun _ _ =>
    (true : bool)) (tt) (fun _ _ =>
    tt) in
  let _ := match x with
  | Trivial_Value =>
    consume (("trivial"%string : string))
  end in
  let _ := consume (("done"%string : string)) in
  tt.

Definition main '(_ : unit) : unit :=
  let _ := trivial (Trivial_Value) in
  tt.
