(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Notation "'t_TRec'" := (t_TRec).

Notation "'TRec_T'" := (TRec_T).

Notation "'TRec_Empty'" := (TRec_Empty).

Notation "'t_T'" := (t_T).

Notation "'T_T'" := (T_T).
