(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Class t_T1 (v_Self : Type) : Type :=
  {
    f_Assoc : Type;
  }.
Arguments t_T1 (_).

Class t_T2 (v_Self : Type) : Type :=
  {
  }.
Arguments t_T2 (_).

Instance t_T2_280894245 `{v_U : Type} `{t_T1 (v_U)} `{t_T2 (f_Assoc)} : t_T2 ((v_U)) :=
  {
  }.
