(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Class t_Trait1 (v_Self : Type) : Type :=
  {
    f_T : Type;
    _ :: `{t_Trait1 (f_T)};
  }.
Arguments t_Trait1 (_).

Class t_Trait2 (v_Self : Type) `{t_Trait1 (v_Self)} : Type :=
  {
    f_U : Type;
  }.
Arguments t_Trait2 (_) {_}.
