(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Inductive t_False : Type :=
.

Definition t_False_cast_to_repr (x : t_False) : t_Never :=
  match x with
  end.

Definition never (h : t_False) : t_Never :=
  match h with
  end.

Definition test__panic_cold_explicit '(_ : unit) : t_Never :=
  panic_explicit (tt).

Definition test (b : bool) : t_u8 :=
  let _ := if
    b
  then
    never_to_any (test__panic_cold_explicit (tt))
  else
    tt in
  (3 : t_u8).

Definition any__panic_cold_explicit '(_ : unit) : t_Never :=
  panic_explicit (tt).

Definition any `{v_T : Type} '(_ : unit) : v_T :=
  never_to_any (any__panic_cold_explicit (tt)).
