(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition v_申し訳ございません '(_ : unit) : bool :=
  black_box ((false : bool)).

(* NotImplementedYet *)

Definition v_サビ '(_ : unit) : unit :=
  tt.

Definition main '(_ : unit) : unit :=
  let _ := f_fold (f_into_iter (impl_7__new (("\208"%char : ascii)) (("\208"%char : ascii)))) (tt) (fun _ e_İ =>
    tt) in
  let _ := if
    andb (v_申し訳ございません (tt)) (v_申し訳ございません (tt))
  then
    let _ := e_print (impl_1__new_const ([("true
"%string : string)])) in
    let _ := tt in
    tt
  else
    tt in
  let _ := v_サビ (tt) in
  tt.

Definition v_他 '(_ : unit) : unit :=
  tt.
