(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Equations accept_7_conditions (bool_arr : both (nseq 'bool 7)) : both 'unit :=
  accept_7_conditions bool_arr  :=
    failure (ret_both (something is not implemented yet.
Pat:Array

This is discussed in issue https://github.com/hacspec/hax/issues/804.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `AST import`.
 : chString)) (ret_both ( : chString)) : both 'unit.
Fail Next Obligation.

Equations main (_ : both 'unit) : both 'unit :=
  main _  :=
    letb _ := accept_7_conditions (repeat (ret_both (false : 'bool)) (ret_both (7 : uint_size))) in
    letb _ := accept_7_conditions (repeat (ret_both (true : 'bool)) (ret_both (7 : uint_size))) in
    ret_both (tt : 'unit) : both 'unit.
Fail Next Obligation.
