(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition checked_incr (c : bool) (x : t_u32) : t_u32 :=
  let _ := assert (f_not (c)) in
  f_add (x) ((1 : t_u32)).

Definition nested (c : bool) (d : bool) (x : t_u32) : t_u32 :=
  let _ := assert (f_not (c)) in
  let _ := assert (f_not (d)) in
  x.

Definition bare (c : bool) : unit :=
  assert (f_not (c)).
