name = "Hax"
version = "0.1.0"
defaultTargets = ["Hax"]

[[lean_lib]]
name = "Hax"

[[require]]
name = "rust-core-models"
git = { url = "https://github.com/cryspen/rust-core-models", subDir = "lean" }
rev = "67c9e02"
