(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition main '(_ : unit) : unit :=
  let is_true := f_eq (f_len (args (tt))) ((1 : t_usize)) in
  let x := (0 : t_i32) in
  let x := fold_range ((0 : t_i32)) ((10 : t_i32)) (fun x _ =>
    (true : bool)) (x) (fun x _ =>
    let x := match is_true with
    | true =>
      x
    | _ =>
      let x := (1 : t_i32) in
      x
    end in
    let x := (3 : t_i32) in
    x) in
  let x := fold_range ((0 : t_i32)) ((10 : t_i32)) (fun x _ =>
    (true : bool)) (x) (fun x _ =>
    let x := match is_true with
    | false =>
      let x := (1 : t_i32) in
      x
    | _ =>
      x
    end in
    let x := (3 : t_i32) in
    x) in
  let x := fold_range ((0 : t_i32)) ((10 : t_i32)) (fun x _ =>
    (true : bool)) (x) (fun x _ =>
    let x := match is_true with
    | true =>
      let x := (1 : t_i32) in
      x
    | _ =>
      x
    end in
    let x := (3 : t_i32) in
    x) in
  let x := fold_range ((0 : t_i32)) ((10 : t_i32)) (fun x _ =>
    (true : bool)) (x) (fun x _ =>
    let _ := if
      is_true
    then
      never_to_any (failure (("Explicit rejection by a phase in the Hax engine:
a node of kind [Continue] have been found in the AST

Note: the error was labeled with context `reject_Continue`.
"%string : string)) (("continue;"%string : string)))
    else
      tt in
    let x := (3 : t_i32) in
    x) in
  let x := fold_range ((0 : t_i32)) ((10 : t_i32)) (fun x _ =>
    (true : bool)) (x) (fun x _ =>
    let x := match is_true with
    | false =>
      let x := (1 : t_i32) in
      x
    | _ =>
      let _ := x in
      x
    end in
    let x := (3 : t_i32) in
    x) in
  let x := fold_range ((0 : t_i32)) ((10 : t_i32)) (fun x _ =>
    (true : bool)) (x) (fun x _ =>
    let x := match is_true with
    | false =>
      let x := (1 : t_i32) in
      x
    | _ =>
      let hoist1 := failure (("something is not implemented yet.
TODO: Monad for loop-related control flow

This is discussed in issue https://github.com/hacspec/hax/issues/15.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `CfIntoMonads`.
"%string : string)) (("(break (Tuple0))"%string : string)) in
      x
    end in
    let x := (3 : t_i32) in
    x) in
  let _ := x in
  tt.
