(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Definition t_Foo : choice_type :=
  (int32).
Equations 0 (s : both t_Foo) : both int32 :=
  0 s  :=
    bind_both s (fun x =>
      ret_both (x : int32)) : both int32.
Fail Next Obligation.
Equations Build_t_Foo {0 : both int32} : both (t_Foo) :=
  Build_t_Foo  :=
    bind_both 0 (fun 0 =>
      ret_both ((0) : (t_Foo))) : both (t_Foo).
Fail Next Obligation.
Notation "'Build_t_Foo' '[' x ']' '(' '0' ':=' y ')'" := (Build_t_Foo (0 := y)).

#[global] Program Instance t_Foo_t_Debug : t_Debug t_Foo :=
  _.
Fail Next Obligation.
Hint Unfold t_Foo_t_Debug.

#[global] Program Instance t_Foo_t_StructuralPartialEq : t_StructuralPartialEq t_Foo :=
  _.
Fail Next Obligation.
Hint Unfold t_Foo_t_StructuralPartialEq.

#[global] Program Instance t_Foo_t_PartialEq : t_PartialEq t_Foo t_Foo :=
  _.
Fail Next Obligation.
Hint Unfold t_Foo_t_PartialEq.

#[global] Program Instance t_Foo_t_Eq : t_Eq t_Foo :=
  _.
Fail Next Obligation.
Hint Unfold t_Foo_t_Eq.

(*item error backend*)
