(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Class t_MyFrom (v_Self : Type) (v_T : Type) : Type :=
  {
    f_my_from : v_T -> v_Self;
  }.
Arguments t_MyFrom (_) (_).

Instance t_MyFrom_1060379843 : t_MyFrom ((t_u16)) ((t_u8)) :=
  {
    implaabbcc_t_MyFrom_f_my_from := fun  (x : t_u8)=>
      cast (x);
  }.

Definition f (x : t_u8) : t_Result ((t_u16)) ((t_u16)) :=
  run (let _ := match f_branch (Result_Err ((1 : t_u8))) with
  | ControlFlow_Break (residual) =>
    ControlFlow_Break (f_from_residual (residual))
  | ControlFlow_Continue (val) =>
    ControlFlow_Continue (val)
  end in
  ControlFlow_Continue (Result_Ok (f_my_from (x)))).
