(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition might_abort (should_abort : bool) : unit :=
  if
    should_abort
  then
    let _ := e_print (impl_1__new_const ([("aborting...
"%string : string)])) in
    let _ := tt in
    never_to_any (panic_fmt (impl_1__new_const ([("panics and aborts"%string : string)])))
  else
    let _ := e_print (impl_1__new_const ([("Don't Panic
"%string : string)])) in
    let _ := tt in
    tt.

Definition main '(_ : unit) : t_Result ((unit)) ((t_u8)) :=
  let countdown := (10 : t_i32) in
  let countdown := failure (("something is not implemented yet.
Unhandled loop kind

This is discussed in issue https://github.com/hacspec/hax/issues/933.
Please upvote or comment this issue if you see this error message.
Note: the error was labeled with context `FunctionalizeLoops`.
"%string : string)) (("{
 (loop {
 |countdown| {
 (if core_models::cmp::f_gt(countdown, 0) {
 {
 let _: tuple0 = {
 (if core_models::cmp::f_lt(countdown, 5) {
 {
 let _: tuple0 = {
 new_tests::rustc_coverage__abort::might_a..."%string : string)) in
  Result_Ok (tt).
