(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Class t_Printable (v_Self : Type) (v_S : Type) : Type :=
  {
    f_stringify : v_Self -> v_S;
  }.
Arguments t_Printable (_) (_).

Instance t_Printable_476386987 : t_Printable ((t_i32)) ((t_String)) :=
  {
    implaabbcc_t_Printable_f_stringify := fun  (self : t_i32)=>
      (* f_to_string *) (self);
  }.

TODO: please implement the method `item'_HaxError`
