(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition clean_add (a : t_u8) (b : t_u8) : t_u8 :=
  f_add (a) (b).

TODO: please implement the method `item'_HaxError`

Class t_Speak (v_Self : Type) : Type :=
  {
    f_hello : v_Self -> t_u8;
  }.
Arguments t_Speak (_).

Record Cat_record : Type :=
  {
  }.

#[export]
Notation "'Cat_Cat_record'" := Build_Cat_record.

Instance t_Speak_824460209 : t_Speak ((t_Cat)) :=
  {
    implaabbcc_t_Speak_f_hello := fun  (self : t_Cat)=>
      (1 : t_u8);
  }.

TODO: please implement the method `item'_HaxError`

Definition dyn_in_body '(_ : unit) : t_u8 :=
  let c := Cat in
  failure (("[hax::opaque] Explicit rejection by a phase in the Hax engine: a node of kind [Dyn] have been found in the AST"%string : string)) ((""%string : string)).

Definition mut_ref_return (x : t_u8) : t_Failure ((""%string : bool)) :=
  failure (("[hax::opaque] The mutation of this &mut is not allowed here."%string : string)) ((""%string : string)).

Definition body_split (buf : t_Slice t_u8) : t_u8 :=
  failure (("[hax::opaque] The mutation of this &mut is not allowed here."%string : string)) ((""%string : string)).
