(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Equations f (x : both t_Prop) (y : both 'bool) : both t_Prop :=
  f x y  :=
    letb (xprop : t_Prop) := f_into y in
    letb p := (((f_lift y) .& xprop) .& y) .& (f_to_prop y) in
    f_not (impl_Prop__implies (p .| y) ((forall (fun x =>
      x <=.? impl_u8__MAX)) .& (exists (fun x =>
      x >.? (ret_both (300 : int16)))))) : both t_Prop.
Fail Next Obligation.
