(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

From RecordUpdate Require Import RecordUpdate.

Import RecordSetNotations.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Class t_Super (Self : choice_type) (v_Self : v_Self) := {
  f_B : choice_type ;
}.

Definition t_S : choice_type :=
  'unit.
Equations Build_t_S : both (t_S) :=
  Build_t_S  :=
    ret_both (tt (* Empty tuple *) : (t_S)) : both (t_S).
Fail Next Obligation.

#[global] Program Instance t_S_t_Super : t_Super t_S :=
  let f_B := int8 : choice_type in
  {| f_B := (@f_B)|}.
Fail Next Obligation.
Hint Unfold t_S_t_Super.

Class t_T (Self : choice_type) (v_Self : v_Self) {v_X : v_X} `{ t_Super v_Self} := {
  f_A : choice_type ;
  f_C : (both int8) ;
  f_f : (both f_A -> both int8) ;
  f_g : (both v_Self -> both f_A -> both f_A) ;
  f_h : (both f_B -> both v_Y -> both v_X -> both f_A) ;
}.

#[global] Program Instance t_S_t_T : t_T t_S int16 :=
  let f_A := int32 : choice_type in
  let f_C := ret_both (1 : int8) : both int8 in
  let f_f := fun  (x : both int32) => ret_both (0 : int8) : both int8 in
  let f_g := fun  (self : both t_S) (x : both int32) => x : both int32 in
  let f_h := fun  (x : both int8) (y : both v_Y) (z : both int16) => f_into y : both int32 in
  {| f_A := (@f_A);
  f_C := (@f_C);
  f_f := (@f_f);
  f_g := (@f_g);
  f_h := (@f_h)|}.
Fail Next Obligation.
Hint Unfold t_S_t_T.
