(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Record Counter_record : Type :=
  {
    Counter_f_n : t_usize;
  }.


#[export] Instance settable_Counter_record : Settable _ :=
  settable! (Build_Counter_record) <Counter_f_n>.

Definition impl_Counter__get_fstar_only (self : t_Counter) : t_usize :=
  f_n self.

Definition impl_Counter__get (self : t_Counter) `{f_lt (f_n self_) ((5 : t_usize)) = true} : t_usize :=
  f_n self.

Definition impl_Counter__get_ensures (self : t_Counter) : t_usize :=
  f_n self.
Lemma impl_Counter__get_ensures_ensures (self : t_Counter) :
  let result := @impl_Counter__get_ensures (self : t_Counter) in
  f_eq (result) (f_n self_) = true.
Proof. Admitted.

Definition impl_Counter__get_inline (self : t_Counter) `{f_lt (f_n self_) ((5 : t_usize)) = true} : t_usize :=
  f_n self.

Record Refined_record (v_LEN : t_usize) : Type :=
  {
    Refined_f_indices : t_Array (t_u8) (v_LEN);
    Refined_f_x : t_u8;
  }.
Arguments Build_Refined_record {_}.
Arguments Refined_f_indices {_}.
Arguments Refined_f_x {_}.
#[export] Instance settable_Refined_record `{v_LEN : t_usize} : Settable _ :=
  settable! (Build_Refined_record (v_LEN := v_LEN)) <Refined_f_indices; Refined_f_x>.

Record Reordered_record : Type :=
  {
    Reordered_f_y : t_u8;
    Reordered_f_x : t_u8;
  }.



#[export] Instance settable_Reordered_record : Settable _ :=
  settable! (Build_Reordered_record) <Reordered_f_y; Reordered_f_x>.

Class t_Double (v_Self : Type) : Type :=
  {
    f_double : v_Self -> t_u8 -> t_u8;
    f_double_fstar_only : v_Self -> t_u8 -> t_u8;
  }.
Arguments t_Double (_).

Instance t_Double_715653907 : t_Double ((t_Counter)) :=
  {
    implaabbcc_t_Double_f_double := fun  (self : t_Counter) (x : t_u8)=>
      f_add (x) (x);
    implaabbcc_t_Double_f_double_fstar_only := fun  (self : t_Counter) (x : t_u8)=>
      f_add (x) (x);
  }.
