(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)







Definition impl__len `{v_T : Type} `{Core_Marker.t_Sized (v_T)} `{Core_Clone.t_Clone (v_T)} (self : Core_Primitive_Primitive_definitions.t_Slice ((v_T))) : t_usize :=
  Core_Convert.From__f_from (Core_Base_Seq.len (Core_Clone.Clone__f_clone (Core_Primitive_Primitive_definitions.f_Slice_v self))).

Definition impl__is_empty `{v_T : Type} `{Core_Marker.t_Sized (v_T)} `{Core_Clone.t_Clone (v_T)} (self : Core_Primitive_Primitive_definitions.t_Slice ((v_T))) : bool :=
  Rust_primitives_U128.eq (impl__len (self)) ((0 : t_usize)).

Definition impl__iter `{v_T : Type} `{Core_Marker.t_Sized (v_T)} `{Core_Clone.t_Clone (v_T)} (self : Core_Primitive_Primitive_definitions.t_Slice ((v_T))) : Core_Slice_Iter.t_Iter ((v_T)) :=
  Core_Slice_Iter.impl__new (self).
