(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Class t_Into (v_Self : Type) (v_T : Type) `{Core_Marker.t_Sized (v_Self)} `{Core_Marker.t_Sized (v_T)} : Type :=
  {
    Into__f_into : v_Self -> v_T;
  }.
Arguments t_Into (_) (_) {_} {_}.

Class t_From (v_Self : Type) (v_T : Type) `{Core_Marker.t_Sized (v_Self)} `{Core_Marker.t_Sized (v_T)} : Type :=
  {
    From__f_from : v_T -> v_Self;
  }.
Arguments t_From (_) (_) {_} {_}.

Instance t_Into_352590089 `{v_T : Type} `{v_U : Type} `{Core_Marker.t_Sized (v_T)} `{Core_Marker.t_Sized (v_U)} `{t_From (v_U) (v_T)} : t_Into ((v_T)) ((v_U)) :=
  {
    implaabbcc_t_Into_impl__f_into := fun  (self : v_T)=>
      From__f_from (self);
  }.

Instance t_From_581002014 `{v_T : Type} `{Core_Marker.t_Sized (v_T)} : t_From ((v_T)) ((v_T)) :=
  {
    implaabbcc_t_From_impl_1__f_from := fun  (t : v_T)=>
      t;
  }.
