(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core_Marker.

(* NotImplementedYet *)



Class t_FnOnce (v_Self : Type) (v_Args : Type) `{Core_Marker.t_Sized (v_Args)} `{Core_Marker.t_Tuple (v_Args)} : Type :=
  {
    FnOnce__f_Output : Type;
    _ :: `{Core_Marker.t_Sized (FnOnce__f_Output)};
    FnOnce__f_call_once : v_Self -> v_Args -> FnOnce__f_Output;
  }.
Arguments t_FnOnce (_) (_) {_} {_}.

Class t_FnMut (v_Self : Type) (v_Args : Type) `{t_FnOnce (v_Self) (v_Args)} `{Core_Marker.t_Sized (v_Args)} `{Core_Marker.t_Tuple (v_Args)} : Type :=
  {
    FnMut__f_call_mut : v_Self -> v_Args -> (v_Self*FnOnce__f_Output);
  }.
Arguments t_FnMut (_) (_) {_} {_} {_}.

Class t_Fn (v_Self : Type) (v_Args : Type) `{t_FnMut (v_Self) (v_Args)} `{Core_Marker.t_Sized (v_Args)} `{Core_Marker.t_Tuple (v_Args)} : Type :=
  {
    Fn__f_call : v_Self -> v_Args -> FnOnce__f_Output;
  }.
Arguments t_Fn (_) (_) {_} {_} {_}.

#[global] Instance t_FnOnceAny {A B} `{Core_Marker.t_Sized A} `{Core_Marker.t_Tuple A} : t_FnOnce (A -> B) A.
Proof.
  econstructor.
  easy.
  refine (fun f x => f x).
Defined.
