(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)















Notation "'t_TryFromSliceError'" := (Core_Bundle.t_TryFromSliceError).

Notation "'TryFromSliceError_TryFromSliceError'" := (Core_Bundle.TryFromSliceError_TryFromSliceError).

Notation "'impl_6'" := (Core_Bundle.impl_6).

Notation "'impl_7'" := (Core_Bundle.impl_7).

Notation "'impl_8'" := (Core_Bundle.impl_8).

Notation "'impl'" := (Core_Bundle.impl).

Notation "'impl_1'" := (Core_Bundle.impl_1).

Notation "'impl_2'" := (Core_Bundle.impl_2).

Notation "'impl_3'" := (Core_Bundle.impl_3).

Notation "'impl_4'" := (Core_Bundle.impl_4).
