(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)







(* NotImplementedYet *)

(* NotImplementedYet *)

Notation "'impl'" := (Core_Bundle.impl).

Notation "'impl_1'" := (Core_Bundle.impl_1).

Notation "'impl_2'" := (Core_Bundle.impl_2).

Notation "'impl_3'" := (Core_Bundle.impl_3).

Notation "'impl_4'" := (Core_Bundle.impl_4).

Notation "'impl_5'" := (Core_Bundle.impl_5).

Notation "'impl_6'" := (Core_Bundle.impl_6).

Notation "'impl_7'" := (Core_Bundle.impl_7).

Notation "'impl_8'" := (Core_Bundle.impl_8).

Notation "'impl_9'" := (Core_Bundle.impl_9).

Notation "'impl_10'" := (Core_Bundle.impl_10).

Notation "'impl_11'" := (Core_Bundle.impl_11).

Notation "'impl_12'" := (Core_Bundle.impl_12).

Notation "'impl_13'" := (Core_Bundle.impl_13).

Notation "'impl_14'" := (Core_Bundle.impl_14).

Notation "'impl_15'" := (Core_Bundle.impl_15).

Notation "'impl_16'" := (Core_Bundle.impl_16).

Notation "'impl_17'" := (Core_Bundle.impl_17).

Notation "'impl_18'" := (Core_Bundle.impl_18).

Notation "'impl_19'" := (Core_Bundle.impl_19).

Notation "'impl_20'" := (Core_Bundle.impl_20).

Notation "'impl_21'" := (Core_Bundle.impl_21).

Notation "'impl_22'" := (Core_Bundle.impl_22).

Notation "'impl_23'" := (Core_Bundle.impl_23).

Notation "'impl_24'" := (Core_Bundle.impl_24).

Notation "'impl_25'" := (Core_Bundle.impl_25).

Notation "'impl_26'" := (Core_Bundle.impl_26).

Notation "'impl_27'" := (Core_Bundle.impl_27).

Notation "'impl_28'" := (Core_Bundle.impl_28).

Notation "'impl_29'" := (Core_Bundle.impl_29).
