(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)





Inductive t_POS : Type :=
| POS_ZERO
| POS_POS : Core_Base_Spec_Binary_Positive.t_Positive -> _.



Definition match_pos (s : Core_Base_Spec_Haxint.t_HaxInt) : t_POS :=
  if
    Core_Base_Spec_Haxint.is_zero (Core_Clone.Clone__f_clone (s))
  then
    POS_ZERO
  else
    POS_POS (Core_Base_Spec_Binary_Positive.positive_from_int (s)).
