(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)







(* NotImplementedYet *)

Instance core.convert.t_From_1922528 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u8)) ((t_u8)) :=
  {
    implaabbcc_t_From_impl__f_from := fun  (x : t_u8)=>
      hax_core.primitive.primitive_definitions.Build_t__u8_u8 (hax_core.base_interface.int.U8_U8 (core.convert.Into__f_into (x)));
  }.

Instance core.convert.t_From_319135907 : core.convert.t_From ((t_u8)) ((hax_core.primitive.primitive_definitions.t_u8)) :=
  {
    implaabbcc_t_From_impl_1__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u8)=>
      core.convert.Into__f_into (hax_core.base_interface.int.f_U8_v hax_core.primitive.primitive_definitions.0 x);
  }.

Instance core.convert.t_From_1073567323 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u16)) ((t_u16)) :=
  {
    implaabbcc_t_From_impl_2__f_from := fun  (x : t_u16)=>
      hax_core.primitive.primitive_definitions.Build_t__u16_u16 (hax_core.base_interface.int.U16_U16 (core.convert.Into__f_into (x)));
  }.

Instance core.convert.t_From_1066015086 : core.convert.t_From ((t_u16)) ((hax_core.primitive.primitive_definitions.t_u16)) :=
  {
    implaabbcc_t_From_impl_3__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u16)=>
      core.convert.Into__f_into (hax_core.base_interface.int.f_U16_v hax_core.primitive.primitive_definitions.0 x);
  }.

Instance core.convert.t_From_392212457 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u32)) ((t_u32)) :=
  {
    implaabbcc_t_From_impl_4__f_from := fun  (x : t_u32)=>
      hax_core.primitive.primitive_definitions.Build_t__u32_u32 (hax_core.base_interface.int.U32_U32 (core.convert.Into__f_into (x)));
  }.

Instance core.convert.t_From_392075498 : core.convert.t_From ((t_u32)) ((hax_core.primitive.primitive_definitions.t_u32)) :=
  {
    implaabbcc_t_From_impl_5__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u32)=>
      core.convert.Into__f_into (hax_core.base_interface.int.f_U32_v hax_core.primitive.primitive_definitions.0 x);
  }.

Instance core.convert.t_From_851181056 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u64)) ((t_u64)) :=
  {
    implaabbcc_t_From_impl_6__f_from := fun  (x : t_u64)=>
      hax_core.primitive.primitive_definitions.Build_t__u64_u64 (hax_core.base_interface.int.U64_U64 (core.convert.Into__f_into (x)));
  }.

Instance core.convert.t_From_1016580315 : core.convert.t_From ((t_u64)) ((hax_core.primitive.primitive_definitions.t_u64)) :=
  {
    implaabbcc_t_From_impl_7__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u64)=>
      core.convert.Into__f_into (hax_core.base_interface.int.f_U64_v hax_core.primitive.primitive_definitions.0 x);
  }.

Instance core.convert.t_From_874597554 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u128)) ((t_u128)) :=
  {
    implaabbcc_t_From_impl_8__f_from := fun  (x : t_u128)=>
      hax_core.primitive.primitive_definitions.Build_t__u128_u128 (hax_core.base_interface.int.U128_U128 (core.convert.Into__f_into (x)));
  }.

Instance core.convert.t_From_283355592 : core.convert.t_From ((t_u128)) ((hax_core.primitive.primitive_definitions.t_u128)) :=
  {
    implaabbcc_t_From_impl_9__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u128)=>
      core.convert.Into__f_into (hax_core.base_interface.int.f_U128_v hax_core.primitive.primitive_definitions.0 x);
  }.

Instance core.convert.t_From_363215569 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_usize)) ((t_usize)) :=
  {
    implaabbcc_t_From_impl_10__f_from := fun  (x : t_usize)=>
      hax_core.primitive.primitive_definitions.Build_t__usize_usize (hax_core.base_interface.int.U64_U64 (core.convert.Into__f_into (x)));
  }.

Instance core.convert.t_From_223165943 : core.convert.t_From ((t_usize)) ((hax_core.primitive.primitive_definitions.t_usize)) :=
  {
    implaabbcc_t_From_impl_11__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_usize)=>
      core.convert.Into__f_into (hax_core.base_interface.int.f_U64_v hax_core.primitive.primitive_definitions.0 x);
  }.

(* NotImplementedYet *)

Instance core.convert.t_From_505762453 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u8)) ((hax_core.primitive.primitive_definitions.t_u16)) :=
  {
    implaabbcc_t_From_impl_12__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u16)=>
      hax_core.primitive.primitive_definitions.Build_t__u8_u8 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_387238974 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u8)) ((hax_core.primitive.primitive_definitions.t_u32)) :=
  {
    implaabbcc_t_From_impl_13__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u32)=>
      hax_core.primitive.primitive_definitions.Build_t__u8_u8 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_45132112 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u16)) ((hax_core.primitive.primitive_definitions.t_u32)) :=
  {
    implaabbcc_t_From_impl_14__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u32)=>
      hax_core.primitive.primitive_definitions.Build_t__u16_u16 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_156774117 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_usize)) ((hax_core.primitive.primitive_definitions.t_u32)) :=
  {
    implaabbcc_t_From_impl_15__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u32)=>
      hax_core.primitive.primitive_definitions.Build_t__usize_usize (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_1042382188 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u8)) ((hax_core.primitive.primitive_definitions.t_u64)) :=
  {
    implaabbcc_t_From_impl_16__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u64)=>
      hax_core.primitive.primitive_definitions.Build_t__u8_u8 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_252199154 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u16)) ((hax_core.primitive.primitive_definitions.t_u64)) :=
  {
    implaabbcc_t_From_impl_17__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u64)=>
      hax_core.primitive.primitive_definitions.Build_t__u16_u16 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_807806916 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u32)) ((hax_core.primitive.primitive_definitions.t_u64)) :=
  {
    implaabbcc_t_From_impl_18__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u64)=>
      hax_core.primitive.primitive_definitions.Build_t__u32_u32 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_125715948 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_usize)) ((hax_core.primitive.primitive_definitions.t_u64)) :=
  {
    implaabbcc_t_From_impl_19__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u64)=>
      hax_core.primitive.primitive_definitions.Build_t__usize_usize (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_13070623 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u8)) ((hax_core.primitive.primitive_definitions.t_u128)) :=
  {
    implaabbcc_t_From_impl_20__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u128)=>
      hax_core.primitive.primitive_definitions.Build_t__u8_u8 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_148436908 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u16)) ((hax_core.primitive.primitive_definitions.t_u128)) :=
  {
    implaabbcc_t_From_impl_21__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u128)=>
      hax_core.primitive.primitive_definitions.Build_t__u16_u16 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_1062656916 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u32)) ((hax_core.primitive.primitive_definitions.t_u128)) :=
  {
    implaabbcc_t_From_impl_22__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u128)=>
      hax_core.primitive.primitive_definitions.Build_t__u32_u32 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_95217252 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u64)) ((hax_core.primitive.primitive_definitions.t_u128)) :=
  {
    implaabbcc_t_From_impl_23__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u128)=>
      hax_core.primitive.primitive_definitions.Build_t__u64_u64 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_128312184 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_usize)) ((hax_core.primitive.primitive_definitions.t_u128)) :=
  {
    implaabbcc_t_From_impl_24__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_u128)=>
      hax_core.primitive.primitive_definitions.Build_t__usize_usize (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_1004896593 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u8)) ((hax_core.primitive.primitive_definitions.t_usize)) :=
  {
    implaabbcc_t_From_impl_25__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_usize)=>
      hax_core.primitive.primitive_definitions.Build_t__u8_u8 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_899377130 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u16)) ((hax_core.primitive.primitive_definitions.t_usize)) :=
  {
    implaabbcc_t_From_impl_26__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_usize)=>
      hax_core.primitive.primitive_definitions.Build_t__u16_u16 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_355559373 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u32)) ((hax_core.primitive.primitive_definitions.t_usize)) :=
  {
    implaabbcc_t_From_impl_27__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_usize)=>
      hax_core.primitive.primitive_definitions.Build_t__u32_u32 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_251377016 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u64)) ((hax_core.primitive.primitive_definitions.t_usize)) :=
  {
    implaabbcc_t_From_impl_28__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_usize)=>
      hax_core.primitive.primitive_definitions.Build_t__u64_u64 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.

Instance core.convert.t_From_229291286 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u128)) ((hax_core.primitive.primitive_definitions.t_usize)) :=
  {
    implaabbcc_t_From_impl_29__f_from := fun  (x : hax_core.primitive.primitive_definitions.t_usize)=>
      hax_core.primitive.primitive_definitions.Build_t__u128_u128 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 x));
  }.
