(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)













(* NotImplementedYet *)

(* NotImplementedYet *)

Notation "'wrapping_add_u8'" := (hax_core.bundle.wrapping_add_u8).

Notation "'wrapping_sub_u8'" := (hax_core.bundle.wrapping_sub_u8).

Notation "'wrapping_mul_u8'" := (hax_core.bundle.wrapping_mul_u8).

Notation "'three_way_compare_u8'" := (hax_core.bundle.three_way_compare_u8).

Notation "'add_with_overflow_u8'" := (hax_core.bundle.add_with_overflow_u8).

Notation "'unchecked_div_u8'" := (hax_core.bundle.unchecked_div_u8).

Notation "'unchecked_add_u8'" := (hax_core.bundle.unchecked_add_u8).

Notation "'ctpop_u8'" := (hax_core.bundle.ctpop_u8).

Notation "'cttz_u8'" := (hax_core.bundle.cttz_u8).

Notation "'ctlz_u8'" := (hax_core.bundle.ctlz_u8).

Notation "'rotate_left_u8'" := (hax_core.bundle.rotate_left_u8).

Notation "'rotate_right_u8'" := (hax_core.bundle.rotate_right_u8).

Notation "'bswap_u8'" := (hax_core.bundle.bswap_u8).

Notation "'wrapping_add_u16'" := (hax_core.bundle.wrapping_add_u16).

Notation "'wrapping_sub_u16'" := (hax_core.bundle.wrapping_sub_u16).

Notation "'wrapping_mul_u16'" := (hax_core.bundle.wrapping_mul_u16).

Notation "'three_way_compare_u16'" := (hax_core.bundle.three_way_compare_u16).

Notation "'add_with_overflow_u16'" := (hax_core.bundle.add_with_overflow_u16).

Notation "'unchecked_div_u16'" := (hax_core.bundle.unchecked_div_u16).

Notation "'unchecked_add_u16'" := (hax_core.bundle.unchecked_add_u16).

Notation "'ctpop_u16'" := (hax_core.bundle.ctpop_u16).

Notation "'cttz_u16'" := (hax_core.bundle.cttz_u16).

Notation "'ctlz_u16'" := (hax_core.bundle.ctlz_u16).

Notation "'rotate_left_u16'" := (hax_core.bundle.rotate_left_u16).

Notation "'rotate_right_u16'" := (hax_core.bundle.rotate_right_u16).

Notation "'bswap_u16'" := (hax_core.bundle.bswap_u16).

Notation "'wrapping_add_u32'" := (hax_core.bundle.wrapping_add_u32).

Notation "'wrapping_sub_u32'" := (hax_core.bundle.wrapping_sub_u32).

Notation "'wrapping_mul_u32'" := (hax_core.bundle.wrapping_mul_u32).

Notation "'three_way_compare_u32'" := (hax_core.bundle.three_way_compare_u32).

Notation "'add_with_overflow_u32'" := (hax_core.bundle.add_with_overflow_u32).

Notation "'unchecked_div_u32'" := (hax_core.bundle.unchecked_div_u32).

Notation "'unchecked_add_u32'" := (hax_core.bundle.unchecked_add_u32).

Notation "'ctpop_u32'" := (hax_core.bundle.ctpop_u32).

Notation "'cttz_u32'" := (hax_core.bundle.cttz_u32).

Notation "'ctlz_u32'" := (hax_core.bundle.ctlz_u32).

Notation "'rotate_left_u32'" := (hax_core.bundle.rotate_left_u32).

Notation "'rotate_right_u32'" := (hax_core.bundle.rotate_right_u32).

Notation "'bswap_u32'" := (hax_core.bundle.bswap_u32).

Notation "'wrapping_add_u64'" := (hax_core.bundle.wrapping_add_u64).

Notation "'wrapping_sub_u64'" := (hax_core.bundle.wrapping_sub_u64).

Notation "'wrapping_mul_u64'" := (hax_core.bundle.wrapping_mul_u64).

Notation "'three_way_compare_u64'" := (hax_core.bundle.three_way_compare_u64).

Notation "'add_with_overflow_u64'" := (hax_core.bundle.add_with_overflow_u64).

Notation "'unchecked_div_u64'" := (hax_core.bundle.unchecked_div_u64).

Notation "'unchecked_add_u64'" := (hax_core.bundle.unchecked_add_u64).

Notation "'ctpop_u64'" := (hax_core.bundle.ctpop_u64).

Notation "'cttz_u64'" := (hax_core.bundle.cttz_u64).

Notation "'ctlz_u64'" := (hax_core.bundle.ctlz_u64).

Notation "'rotate_left_u64'" := (hax_core.bundle.rotate_left_u64).

Notation "'rotate_right_u64'" := (hax_core.bundle.rotate_right_u64).

Notation "'bswap_u64'" := (hax_core.bundle.bswap_u64).

Notation "'wrapping_add_u128'" := (hax_core.bundle.wrapping_add_u128).

Notation "'wrapping_sub_u128'" := (hax_core.bundle.wrapping_sub_u128).

Notation "'wrapping_mul_u128'" := (hax_core.bundle.wrapping_mul_u128).

Notation "'three_way_compare_u128'" := (hax_core.bundle.three_way_compare_u128).

Notation "'add_with_overflow_u128'" := (hax_core.bundle.add_with_overflow_u128).

Notation "'unchecked_div_u128'" := (hax_core.bundle.unchecked_div_u128).

Notation "'unchecked_add_u128'" := (hax_core.bundle.unchecked_add_u128).

Notation "'ctpop_u128'" := (hax_core.bundle.ctpop_u128).

Notation "'cttz_u128'" := (hax_core.bundle.cttz_u128).

Notation "'ctlz_u128'" := (hax_core.bundle.ctlz_u128).

Notation "'rotate_left_u128'" := (hax_core.bundle.rotate_left_u128).

Notation "'rotate_right_u128'" := (hax_core.bundle.rotate_right_u128).

Notation "'bswap_u128'" := (hax_core.bundle.bswap_u128).

Notation "'wrapping_add_usize'" := (hax_core.bundle.wrapping_add_usize).

Notation "'wrapping_sub_usize'" := (hax_core.bundle.wrapping_sub_usize).

Notation "'wrapping_mul_usize'" := (hax_core.bundle.wrapping_mul_usize).

Notation "'three_way_compare_usize'" := (hax_core.bundle.three_way_compare_usize).

Notation "'add_with_overflow_usize'" := (hax_core.bundle.add_with_overflow_usize).

Notation "'unchecked_div_usize'" := (hax_core.bundle.unchecked_div_usize).

Notation "'unchecked_add_usize'" := (hax_core.bundle.unchecked_add_usize).

Notation "'ctpop_usize'" := (hax_core.bundle.ctpop_usize).

Notation "'cttz_usize'" := (hax_core.bundle.cttz_usize).

Notation "'ctlz_usize'" := (hax_core.bundle.ctlz_usize).

Notation "'rotate_left_usize'" := (hax_core.bundle.rotate_left_usize).

Notation "'rotate_right_usize'" := (hax_core.bundle.rotate_right_usize).

Notation "'bswap_usize'" := (hax_core.bundle.bswap_usize).

Notation "'wrapping_add_i8'" := (hax_core.bundle.wrapping_add_i8).

Notation "'wrapping_sub_i8'" := (hax_core.bundle.wrapping_sub_i8).

Notation "'wrapping_mul_i8'" := (hax_core.bundle.wrapping_mul_i8).

Notation "'add_with_overflow_i8'" := (hax_core.bundle.add_with_overflow_i8).

Notation "'unchecked_div_i8'" := (hax_core.bundle.unchecked_div_i8).

Notation "'unchecked_add_i8'" := (hax_core.bundle.unchecked_add_i8).

Notation "'wrapping_add_i16'" := (hax_core.bundle.wrapping_add_i16).

Notation "'wrapping_sub_i16'" := (hax_core.bundle.wrapping_sub_i16).

Notation "'wrapping_mul_i16'" := (hax_core.bundle.wrapping_mul_i16).

Notation "'add_with_overflow_i16'" := (hax_core.bundle.add_with_overflow_i16).

Notation "'unchecked_div_i16'" := (hax_core.bundle.unchecked_div_i16).

Notation "'unchecked_add_i16'" := (hax_core.bundle.unchecked_add_i16).

Notation "'wrapping_add_i32'" := (hax_core.bundle.wrapping_add_i32).

Notation "'wrapping_sub_i32'" := (hax_core.bundle.wrapping_sub_i32).

Notation "'wrapping_mul_i32'" := (hax_core.bundle.wrapping_mul_i32).

Notation "'add_with_overflow_i32'" := (hax_core.bundle.add_with_overflow_i32).

Notation "'unchecked_div_i32'" := (hax_core.bundle.unchecked_div_i32).

Notation "'unchecked_add_i32'" := (hax_core.bundle.unchecked_add_i32).

Notation "'wrapping_add_i64'" := (hax_core.bundle.wrapping_add_i64).

Notation "'wrapping_sub_i64'" := (hax_core.bundle.wrapping_sub_i64).

Notation "'wrapping_mul_i64'" := (hax_core.bundle.wrapping_mul_i64).

Notation "'add_with_overflow_i64'" := (hax_core.bundle.add_with_overflow_i64).

Notation "'unchecked_div_i64'" := (hax_core.bundle.unchecked_div_i64).

Notation "'unchecked_add_i64'" := (hax_core.bundle.unchecked_add_i64).

Notation "'wrapping_add_i128'" := (hax_core.bundle.wrapping_add_i128).

Notation "'wrapping_sub_i128'" := (hax_core.bundle.wrapping_sub_i128).

Notation "'wrapping_mul_i128'" := (hax_core.bundle.wrapping_mul_i128).

Notation "'add_with_overflow_i128'" := (hax_core.bundle.add_with_overflow_i128).

Notation "'unchecked_div_i128'" := (hax_core.bundle.unchecked_div_i128).

Notation "'unchecked_add_i128'" := (hax_core.bundle.unchecked_add_i128).

Notation "'wrapping_add_isize'" := (hax_core.bundle.wrapping_add_isize).

Notation "'wrapping_sub_isize'" := (hax_core.bundle.wrapping_sub_isize).

Notation "'wrapping_mul_isize'" := (hax_core.bundle.wrapping_mul_isize).

Notation "'add_with_overflow_isize'" := (hax_core.bundle.add_with_overflow_isize).

Notation "'unchecked_div_isize'" := (hax_core.bundle.unchecked_div_isize).

Notation "'unchecked_add_isize'" := (hax_core.bundle.unchecked_add_isize).
