(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)







Inductive t_Mask : Type :=
| Mask_IsPos : hax_core.base.spec.binary.positive.t_Positive -> _
| Mask_IsNul
| Mask_IsNeg.




Definition haxint_cmp (lhs : hax_core.base.spec.haxint.t_HaxInt) (rhs : hax_core.base.spec.haxint.t_HaxInt) : core.cmp.t_Ordering :=
  match hax_core.base.spec.binary.pos.match_pos (lhs) with
  | hax_core.base.spec.binary.pos.POS_ZERO =>
    match hax_core.base.spec.binary.pos.match_pos (rhs) with
    | hax_core.base.spec.binary.pos.POS_ZERO =>
      core.cmp.Ordering_Equal
    | hax_core.base.spec.binary.pos.POS_POS (q) =>
      core.cmp.Ordering_Less
    end
  | hax_core.base.spec.binary.pos.POS_POS (p) =>
    match hax_core.base.spec.binary.pos.match_pos (rhs) with
    | hax_core.base.spec.binary.pos.POS_ZERO =>
      core.cmp.Ordering_Greater
    | hax_core.base.spec.binary.pos.POS_POS (q) =>
      hax_core.base.binary.positive_cmp (p) (q)
    end
  end.

Definition haxint_lt (lhs : hax_core.base.spec.haxint.t_HaxInt) (rhs : hax_core.base.spec.haxint.t_HaxInt) : bool :=
  match core.option.Option_Some (haxint_cmp (lhs) (rhs)) with
  | core.option.Option_Some (core.cmp.Ordering_Less) =>
    (true : bool)
  | _ =>
    (false : bool)
  end.

Definition haxint_le (lhs : hax_core.base.spec.haxint.t_HaxInt) (rhs : hax_core.base.spec.haxint.t_HaxInt) : bool :=
  match core.option.Option_Some (haxint_cmp (lhs) (rhs)) with
  | core.option.Option_Some (core.cmp.Ordering_Less
  | core.cmp.Ordering_Equal) =>
    (true : bool)
  | _ =>
    (false : bool)
  end.

Definition haxint_add (lhs : hax_core.base.spec.haxint.t_HaxInt) (rhs : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  match hax_core.base.spec.binary.pos.match_pos (lhs) with
  | hax_core.base.spec.binary.pos.POS_ZERO =>
    rhs
  | hax_core.base.spec.binary.pos.POS_POS (p) =>
    match hax_core.base.spec.binary.pos.match_pos (rhs) with
    | hax_core.base.spec.binary.pos.POS_ZERO =>
      hax_core.base.spec.binary.positive.positive_to_int (p)
    | hax_core.base.spec.binary.pos.POS_POS (q) =>
      hax_core.base.spec.binary.positive.positive_to_int (hax_core.base.binary.positive_add (p) (q))
    end
  end.

Definition haxint_sub__double_pred_mask (lhs : hax_core.base.spec.binary.positive.t_Positive) : t_Mask :=
  match hax_core.base.spec.binary.positive.match_positive (lhs) with
  | hax_core.base.spec.binary.positive.POSITIVE_XH =>
    Mask_IsNul
  | hax_core.base.spec.binary.positive.POSITIVE_XO (p) =>
    Mask_IsPos (hax_core.base.spec.binary.positive.xO (hax_core.base.binary.positive_pred_double (p)))
  | hax_core.base.spec.binary.positive.POSITIVE_XI (p) =>
    Mask_IsPos (hax_core.base.spec.binary.positive.xO (hax_core.base.spec.binary.positive.xO (p)))
  end.

Definition haxint_sub__succ_double_mask (lhs : t_Mask) : t_Mask :=
  match lhs with
  | Mask_IsNeg =>
    Mask_IsNeg
  | Mask_IsNul =>
    Mask_IsPos (hax_core.base.spec.binary.positive.xH)
  | Mask_IsPos (p) =>
    Mask_IsPos (hax_core.base.spec.binary.positive.xI (p))
  end.

Definition haxint_sub__double_mask (lhs : t_Mask) : t_Mask :=
  match lhs with
  | Mask_IsNeg =>
    Mask_IsNeg
  | Mask_IsNul =>
    Mask_IsNul
  | Mask_IsPos (p) =>
    Mask_IsPos (hax_core.base.spec.binary.positive.xO (p))
  end.

Definition haxint_double (s : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  match hax_core.base.spec.binary.pos.match_pos (s) with
  | hax_core.base.spec.binary.pos.POS_ZERO =>
    hax_core.base.spec.haxint.v_HaxInt_ZERO
  | hax_core.base.spec.binary.pos.POS_POS (p) =>
    hax_core.base.spec.binary.positive.positive_to_int (hax_core.base.spec.binary.positive.xO (p))
  end.

Definition haxint_succ_double (s : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.binary.positive.t_Positive :=
  match hax_core.base.spec.binary.pos.match_pos (s) with
  | hax_core.base.spec.binary.pos.POS_ZERO =>
    hax_core.base.spec.binary.positive.xH
  | hax_core.base.spec.binary.pos.POS_POS (p) =>
    hax_core.base.spec.binary.positive.xI (p)
  end.

Definition haxint_mul (lhs : hax_core.base.spec.haxint.t_HaxInt) (rhs : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  match hax_core.base.spec.binary.pos.match_pos (lhs) with
  | hax_core.base.spec.binary.pos.POS_ZERO =>
    hax_core.base.spec.haxint.v_HaxInt_ZERO
  | hax_core.base.spec.binary.pos.POS_POS (p) =>
    match hax_core.base.spec.binary.pos.match_pos (rhs) with
    | hax_core.base.spec.binary.pos.POS_ZERO =>
      hax_core.base.spec.haxint.v_HaxInt_ZERO
    | hax_core.base.spec.binary.pos.POS_POS (q) =>
      hax_core.base.spec.binary.positive.positive_to_int (hax_core.base.binary.positive_mul (p) (q))
    end
  end.

Definition haxint_shr__half (s : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  match hax_core.base.spec.binary.pos.match_pos (s) with
  | hax_core.base.spec.binary.pos.POS_ZERO =>
    hax_core.base.spec.haxint.v_HaxInt_ZERO
  | hax_core.base.spec.binary.pos.POS_POS (n) =>
    match hax_core.base.spec.binary.positive.match_positive (n) with
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      hax_core.base.spec.haxint.v_HaxInt_ZERO
    | hax_core.base.spec.binary.positive.POSITIVE_XO (p) =>
      hax_core.base.spec.binary.positive.positive_to_int (p)
    | hax_core.base.spec.binary.positive.POSITIVE_XI (p) =>
      hax_core.base.spec.binary.positive.positive_to_int (p)
    end
  end.

Definition haxint_sub (lhs : hax_core.base.spec.haxint.t_HaxInt) (rhs : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  match hax_core.base.spec.binary.pos.match_pos (lhs) with
  | hax_core.base.spec.binary.pos.POS_ZERO =>
    hax_core.base.spec.haxint.v_HaxInt_ZERO
  | hax_core.base.spec.binary.pos.POS_POS (p) =>
    match hax_core.base.spec.binary.pos.match_pos (rhs) with
    | hax_core.base.spec.binary.pos.POS_ZERO =>
      hax_core.base.spec.binary.positive.positive_to_int (p)
    | hax_core.base.spec.binary.pos.POS_POS (q) =>
      match haxint_sub__sub_binary (p) (q) with
      | Mask_IsPos (v) =>
        hax_core.base.spec.binary.positive.positive_to_int (v)
      | _ =>
        hax_core.base.spec.haxint.v_HaxInt_ZERO
      end
    end
  end.

Fixpoint power_of_two (s : hax_core.base.spec.unary.t_Unary) : hax_core.base.spec.binary.positive.t_Positive :=
  match hax_core.base.spec.unary.match_unary (s) with
  | hax_core.base.spec.unary.UNARY_ZERO =>
    hax_core.base.spec.binary.positive.xH
  | hax_core.base.spec.unary.UNARY_SUCC (x) =>
    hax_core.base.spec.binary.positive.xO (power_of_two (x))
  end.

Fixpoint haxint_shl__shl_helper (rhs : hax_core.base.spec.unary.t_Unary) (lhs : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  if
    hax_core.base.spec.haxint.is_zero (core.clone.Clone__f_clone (lhs))
  then
    lhs
  else
    match hax_core.base.spec.unary.match_unary (rhs) with
    | hax_core.base.spec.unary.UNARY_ZERO =>
      lhs
    | hax_core.base.spec.unary.UNARY_SUCC (n) =>
      haxint_shl__shl_helper (n) (haxint_double (lhs))
    end.

Fixpoint haxint_shr__shr_helper (rhs : hax_core.base.spec.unary.t_Unary) (lhs : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  if
    hax_core.base.spec.haxint.is_zero (core.clone.Clone__f_clone (lhs))
  then
    lhs
  else
    match hax_core.base.spec.unary.match_unary (rhs) with
    | hax_core.base.spec.unary.UNARY_ZERO =>
      lhs
    | hax_core.base.spec.unary.UNARY_SUCC (n) =>
      haxint_shr__shr_helper (n) (haxint_shr__half (lhs))
    end.

Fixpoint bitxor_binary (lhs : hax_core.base.spec.binary.positive.t_Positive) (rhs : hax_core.base.spec.binary.positive.t_Positive) : hax_core.base.spec.haxint.t_HaxInt :=
  match hax_core.base.spec.binary.positive.match_positive (lhs) with
  | hax_core.base.spec.binary.positive.POSITIVE_XH =>
    match hax_core.base.spec.binary.positive.match_positive (rhs) with
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      hax_core.base.spec.haxint.v_HaxInt_ZERO
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q) =>
      hax_core.base.spec.binary.positive.positive_to_int (hax_core.base.spec.binary.positive.xI (q))
    | hax_core.base.spec.binary.positive.POSITIVE_XI (q) =>
      hax_core.base.spec.binary.positive.positive_to_int (hax_core.base.spec.binary.positive.xO (q))
    end
  | hax_core.base.spec.binary.positive.POSITIVE_XO (p) =>
    match hax_core.base.spec.binary.positive.match_positive (rhs) with
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      hax_core.base.spec.binary.positive.positive_to_int (hax_core.base.spec.binary.positive.xI (p))
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q) =>
      haxint_double (bitxor_binary (p) (q))
    | hax_core.base.spec.binary.positive.POSITIVE_XI (q) =>
      hax_core.base.spec.binary.positive.positive_to_int (haxint_succ_double (bitxor_binary (p) (q)))
    end
  | hax_core.base.spec.binary.positive.POSITIVE_XI (p) =>
    match hax_core.base.spec.binary.positive.match_positive (rhs) with
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      hax_core.base.spec.binary.positive.positive_to_int (hax_core.base.spec.binary.positive.xO (p))
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q) =>
      hax_core.base.spec.binary.positive.positive_to_int (haxint_succ_double (bitxor_binary (p) (q)))
    | hax_core.base.spec.binary.positive.POSITIVE_XI (q) =>
      haxint_double (bitxor_binary (p) (q))
    end
  end.

Fixpoint bitand_binary (lhs : hax_core.base.spec.binary.positive.t_Positive) (rhs : hax_core.base.spec.binary.positive.t_Positive) : hax_core.base.spec.haxint.t_HaxInt :=
  match hax_core.base.spec.binary.positive.match_positive (lhs) with
  | hax_core.base.spec.binary.positive.POSITIVE_XH =>
    match hax_core.base.spec.binary.positive.match_positive (rhs) with
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q) =>
      hax_core.base.spec.haxint.v_HaxInt_ZERO
    | hax_core.base.spec.binary.positive.POSITIVE_XI (_)
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      hax_core.base.spec.haxint.v_HaxInt_ONE
    end
  | hax_core.base.spec.binary.positive.POSITIVE_XO (p) =>
    match hax_core.base.spec.binary.positive.match_positive (rhs) with
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      hax_core.base.spec.haxint.v_HaxInt_ZERO
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q)
    | hax_core.base.spec.binary.positive.POSITIVE_XI (q) =>
      haxint_double (bitand_binary (p) (q))
    end
  | hax_core.base.spec.binary.positive.POSITIVE_XI (p) =>
    match hax_core.base.spec.binary.positive.match_positive (rhs) with
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      hax_core.base.spec.haxint.v_HaxInt_ONE
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q) =>
      haxint_double (bitand_binary (p) (q))
    | hax_core.base.spec.binary.positive.POSITIVE_XI (q) =>
      hax_core.base.spec.binary.positive.positive_to_int (haxint_succ_double (bitand_binary (p) (q)))
    end
  end.

Fixpoint bitor_binary (lhs : hax_core.base.spec.binary.positive.t_Positive) (rhs : hax_core.base.spec.binary.positive.t_Positive) : hax_core.base.spec.binary.positive.t_Positive :=
  match hax_core.base.spec.binary.positive.match_positive (lhs) with
  | hax_core.base.spec.binary.positive.POSITIVE_XH =>
    match hax_core.base.spec.binary.positive.match_positive (rhs) with
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q) =>
      hax_core.base.spec.binary.positive.xI (q)
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      hax_core.base.spec.binary.positive.xH
    | hax_core.base.spec.binary.positive.POSITIVE_XI (q) =>
      hax_core.base.spec.binary.positive.xI (q)
    end
  | hax_core.base.spec.binary.positive.POSITIVE_XO (p) =>
    match hax_core.base.spec.binary.positive.match_positive (rhs) with
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      hax_core.base.spec.binary.positive.xI (p)
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q) =>
      hax_core.base.spec.binary.positive.xO (bitor_binary (p) (q))
    | hax_core.base.spec.binary.positive.POSITIVE_XI (q) =>
      hax_core.base.spec.binary.positive.xI (bitor_binary (p) (q))
    end
  | hax_core.base.spec.binary.positive.POSITIVE_XI (p) =>
    match hax_core.base.spec.binary.positive.match_positive (rhs) with
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      hax_core.base.spec.binary.positive.xI (p)
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q)
    | hax_core.base.spec.binary.positive.POSITIVE_XI (q) =>
      hax_core.base.spec.binary.positive.xI (bitor_binary (p) (q))
    end
  end.

Definition haxint_shl (lhs : hax_core.base.spec.haxint.t_HaxInt) (rhs : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  haxint_shl__shl_helper (hax_core.base.spec.unary.unary_from_int (rhs)) (lhs).

Definition haxint_shr (lhs : hax_core.base.spec.haxint.t_HaxInt) (rhs : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  haxint_shr__shr_helper (hax_core.base.spec.unary.unary_from_int (rhs)) (lhs).

Definition haxint_bitxor (lhs : hax_core.base.spec.haxint.t_HaxInt) (rhs : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  match hax_core.base.spec.binary.pos.match_pos (lhs) with
  | hax_core.base.spec.binary.pos.POS_ZERO =>
    rhs
  | hax_core.base.spec.binary.pos.POS_POS (p) =>
    match hax_core.base.spec.binary.pos.match_pos (rhs) with
    | hax_core.base.spec.binary.pos.POS_ZERO =>
      hax_core.base.spec.binary.positive.positive_to_int (p)
    | hax_core.base.spec.binary.pos.POS_POS (q) =>
      bitxor_binary (p) (q)
    end
  end.

Definition haxint_bitand (lhs : hax_core.base.spec.haxint.t_HaxInt) (rhs : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  match hax_core.base.spec.binary.pos.match_pos (lhs) with
  | hax_core.base.spec.binary.pos.POS_ZERO =>
    hax_core.base.spec.haxint.v_HaxInt_ZERO
  | hax_core.base.spec.binary.pos.POS_POS (p) =>
    match hax_core.base.spec.binary.pos.match_pos (rhs) with
    | hax_core.base.spec.binary.pos.POS_ZERO =>
      hax_core.base.spec.haxint.v_HaxInt_ZERO
    | hax_core.base.spec.binary.pos.POS_POS (q) =>
      bitand_binary (p) (q)
    end
  end.

Definition haxint_bitor (lhs : hax_core.base.spec.haxint.t_HaxInt) (rhs : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  match hax_core.base.spec.binary.pos.match_pos (lhs) with
  | hax_core.base.spec.binary.pos.POS_ZERO =>
    rhs
  | hax_core.base.spec.binary.pos.POS_POS (p) =>
    match hax_core.base.spec.binary.pos.match_pos (rhs) with
    | hax_core.base.spec.binary.pos.POS_ZERO =>
      hax_core.base.spec.binary.positive.positive_to_int (p)
    | hax_core.base.spec.binary.pos.POS_POS (q) =>
      hax_core.base.spec.binary.positive.positive_to_int (bitor_binary (p) (q))
    end
  end.

Fixpoint haxint_divmod__divmod_binary (a : hax_core.base.spec.binary.positive.t_Positive) (b : hax_core.base.spec.binary.positive.t_Positive) : (hax_core.base.spec.haxint.t_HaxInt*hax_core.base.spec.haxint.t_HaxInt) :=
  match hax_core.base.spec.binary.positive.match_positive (a) with
  | hax_core.base.spec.binary.positive.POSITIVE_XH =>
    match hax_core.base.spec.binary.positive.match_positive (b) with
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      (hax_core.base.spec.haxint.v_HaxInt_ONE,hax_core.base.spec.haxint.v_HaxInt_ZERO)
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q)
    | hax_core.base.spec.binary.positive.POSITIVE_XI (q) =>
      (hax_core.base.spec.haxint.v_HaxInt_ZERO,hax_core.base.spec.haxint.v_HaxInt_ONE)
    end
  | hax_core.base.spec.binary.positive.POSITIVE_XO (a_) =>
    let (q,r) := haxint_divmod__divmod_binary (a_) (core.clone.Clone__f_clone (b)) in
    let r_ := haxint_double (r) in
    if
      haxint_le (hax_core.base.spec.binary.positive.positive_to_int (core.clone.Clone__f_clone (b))) (core.clone.Clone__f_clone (r_))
    then
      (hax_core.base.spec.binary.positive.positive_to_int (haxint_succ_double (q)),haxint_sub (r_) (hax_core.base.spec.binary.positive.positive_to_int (b)))
    else
      (haxint_double (q),r_)
  | hax_core.base.spec.binary.positive.POSITIVE_XI (a_) =>
    let (q,r) := haxint_divmod__divmod_binary (a_) (core.clone.Clone__f_clone (b)) in
    let r_ := hax_core.base.spec.binary.positive.positive_to_int (haxint_succ_double (r)) in
    if
      haxint_le (hax_core.base.spec.binary.positive.positive_to_int (core.clone.Clone__f_clone (b))) (core.clone.Clone__f_clone (r_))
    then
      (hax_core.base.spec.binary.positive.positive_to_int (haxint_succ_double (q)),haxint_sub (r_) (hax_core.base.spec.binary.positive.positive_to_int (b)))
    else
      (haxint_double (q),r_)
  end.

Definition haxint_divmod (a : hax_core.base.spec.haxint.t_HaxInt) (b : hax_core.base.spec.haxint.t_HaxInt) : (hax_core.base.spec.haxint.t_HaxInt*hax_core.base.spec.haxint.t_HaxInt) :=
  match hax_core.base.spec.binary.pos.match_pos (a) with
  | hax_core.base.spec.binary.pos.POS_ZERO =>
    (hax_core.base.spec.haxint.v_HaxInt_ZERO,hax_core.base.spec.haxint.v_HaxInt_ZERO)
  | hax_core.base.spec.binary.pos.POS_POS (p) =>
    match hax_core.base.spec.binary.pos.match_pos (b) with
    | hax_core.base.spec.binary.pos.POS_ZERO =>
      (hax_core.base.spec.haxint.v_HaxInt_ZERO,hax_core.base.spec.binary.positive.positive_to_int (p))
    | hax_core.base.spec.binary.pos.POS_POS (q) =>
      haxint_divmod__divmod_binary (p) (q)
    end
  end.

Definition haxint_div (lhs : hax_core.base.spec.haxint.t_HaxInt) (rhs : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  let (q,_) := haxint_divmod (lhs) (rhs) in
  q.

Definition haxint_rem (lhs : hax_core.base.spec.haxint.t_HaxInt) (rhs : hax_core.base.spec.haxint.t_HaxInt) : hax_core.base.spec.haxint.t_HaxInt :=
  let (_,r) := haxint_divmod (lhs) (rhs) in
  r.

Fixpoint haxint_sub__sub_carry (lhs : hax_core.base.spec.binary.positive.t_Positive) (rhs : hax_core.base.spec.binary.positive.t_Positive) : t_Mask :=
  match hax_core.base.spec.binary.positive.match_positive (lhs) with
  | hax_core.base.spec.binary.positive.POSITIVE_XH =>
    Mask_IsNeg
  | hax_core.base.spec.binary.positive.POSITIVE_XO (p) =>
    match hax_core.base.spec.binary.positive.match_positive (rhs) with
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      haxint_sub__double_pred_mask (p)
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q) =>
      haxint_sub__succ_double_mask (haxint_sub__sub_carry (p) (q))
    | hax_core.base.spec.binary.positive.POSITIVE_XI (q) =>
      haxint_sub__double_mask (haxint_sub__sub_carry (p) (q))
    end
  | hax_core.base.spec.binary.positive.POSITIVE_XI (p) =>
    match hax_core.base.spec.binary.positive.match_positive (rhs) with
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      Mask_IsPos (hax_core.base.binary.positive_pred_double (p))
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q) =>
      haxint_sub__double_mask (haxint_sub__sub_binary (p) (q))
    | hax_core.base.spec.binary.positive.POSITIVE_XI (q) =>
      haxint_sub__succ_double_mask (haxint_sub__sub_carry (p) (q))
    end
  end.

Fixpoint haxint_sub__sub_binary (lhs : hax_core.base.spec.binary.positive.t_Positive) (rhs : hax_core.base.spec.binary.positive.t_Positive) : t_Mask :=
  match hax_core.base.spec.binary.positive.match_positive (lhs) with
  | hax_core.base.spec.binary.positive.POSITIVE_XH =>
    Mask_IsNeg
  | hax_core.base.spec.binary.positive.POSITIVE_XO (p) =>
    match hax_core.base.spec.binary.positive.match_positive (rhs) with
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      Mask_IsPos (hax_core.base.binary.positive_pred_double (p))
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q) =>
      haxint_sub__double_mask (haxint_sub__sub_binary (p) (q))
    | hax_core.base.spec.binary.positive.POSITIVE_XI (q) =>
      haxint_sub__succ_double_mask (haxint_sub__sub_carry (p) (q))
    end
  | hax_core.base.spec.binary.positive.POSITIVE_XI (p) =>
    match hax_core.base.spec.binary.positive.match_positive (rhs) with
    | hax_core.base.spec.binary.positive.POSITIVE_XH =>
      Mask_IsPos (hax_core.base.spec.binary.positive.xO (p))
    | hax_core.base.spec.binary.positive.POSITIVE_XO (q) =>
      haxint_sub__succ_double_mask (haxint_sub__sub_binary (p) (q))
    | hax_core.base.spec.binary.positive.POSITIVE_XI (q) =>
      haxint_sub__double_mask (haxint_sub__sub_binary (p) (q))
    end
  end.
