(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)























(* NotImplementedYet *)

Instance core.cmp.t_PartialEq_170461617 : core.cmp.t_PartialEq ((hax_core.primitive.primitive_definitions.t_usize)) ((hax_core.primitive.primitive_definitions.t_usize)) :=
  {
    implaabbcc_t_PartialEq_impl__f_eq := fun  (self : hax_core.primitive.primitive_definitions.t_usize) (other : hax_core.primitive.primitive_definitions.t_usize)=>
      core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialEq_impl__f_ne := fun  (self : hax_core.primitive.primitive_definitions.t_usize) (other : hax_core.primitive.primitive_definitions.t_usize)=>
      core.ops.bit.Not__f_not (core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialEq_563312396 : core.cmp.t_PartialEq ((hax_core.primitive.primitive_definitions.t_u8)) ((hax_core.primitive.primitive_definitions.t_u8)) :=
  {
    implaabbcc_t_PartialEq_impl_1__f_eq := fun  (self : hax_core.primitive.primitive_definitions.t_u8) (other : hax_core.primitive.primitive_definitions.t_u8)=>
      core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialEq_impl_1__f_ne := fun  (self : hax_core.primitive.primitive_definitions.t_u8) (other : hax_core.primitive.primitive_definitions.t_u8)=>
      core.ops.bit.Not__f_not (core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialEq_350887635 : core.cmp.t_PartialEq ((hax_core.primitive.primitive_definitions.t_u16)) ((hax_core.primitive.primitive_definitions.t_u16)) :=
  {
    implaabbcc_t_PartialEq_impl_2__f_eq := fun  (self : hax_core.primitive.primitive_definitions.t_u16) (other : hax_core.primitive.primitive_definitions.t_u16)=>
      core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialEq_impl_2__f_ne := fun  (self : hax_core.primitive.primitive_definitions.t_u16) (other : hax_core.primitive.primitive_definitions.t_u16)=>
      core.ops.bit.Not__f_not (core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialEq_768861092 : core.cmp.t_PartialEq ((hax_core.primitive.primitive_definitions.t_u32)) ((hax_core.primitive.primitive_definitions.t_u32)) :=
  {
    implaabbcc_t_PartialEq_impl_3__f_eq := fun  (self : hax_core.primitive.primitive_definitions.t_u32) (other : hax_core.primitive.primitive_definitions.t_u32)=>
      core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialEq_impl_3__f_ne := fun  (self : hax_core.primitive.primitive_definitions.t_u32) (other : hax_core.primitive.primitive_definitions.t_u32)=>
      core.ops.bit.Not__f_not (core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialEq_1033586576 : core.cmp.t_PartialEq ((hax_core.primitive.primitive_definitions.t_u64)) ((hax_core.primitive.primitive_definitions.t_u64)) :=
  {
    implaabbcc_t_PartialEq_impl_4__f_eq := fun  (self : hax_core.primitive.primitive_definitions.t_u64) (other : hax_core.primitive.primitive_definitions.t_u64)=>
      core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialEq_impl_4__f_ne := fun  (self : hax_core.primitive.primitive_definitions.t_u64) (other : hax_core.primitive.primitive_definitions.t_u64)=>
      core.ops.bit.Not__f_not (core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialEq_627171709 : core.cmp.t_PartialEq ((hax_core.primitive.primitive_definitions.t_u128)) ((hax_core.primitive.primitive_definitions.t_u128)) :=
  {
    implaabbcc_t_PartialEq_impl_5__f_eq := fun  (self : hax_core.primitive.primitive_definitions.t_u128) (other : hax_core.primitive.primitive_definitions.t_u128)=>
      core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialEq_impl_5__f_ne := fun  (self : hax_core.primitive.primitive_definitions.t_u128) (other : hax_core.primitive.primitive_definitions.t_u128)=>
      core.ops.bit.Not__f_not (core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialEq_1052554830 : core.cmp.t_PartialEq ((hax_core.primitive.primitive_definitions.t_isize)) ((hax_core.primitive.primitive_definitions.t_isize)) :=
  {
    implaabbcc_t_PartialEq_impl_6__f_eq := fun  (self : hax_core.primitive.primitive_definitions.t_isize) (other : hax_core.primitive.primitive_definitions.t_isize)=>
      core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialEq_impl_6__f_ne := fun  (self : hax_core.primitive.primitive_definitions.t_isize) (other : hax_core.primitive.primitive_definitions.t_isize)=>
      core.ops.bit.Not__f_not (core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialEq_661265779 : core.cmp.t_PartialEq ((hax_core.primitive.primitive_definitions.t_i8)) ((hax_core.primitive.primitive_definitions.t_i8)) :=
  {
    implaabbcc_t_PartialEq_impl_7__f_eq := fun  (self : hax_core.primitive.primitive_definitions.t_i8) (other : hax_core.primitive.primitive_definitions.t_i8)=>
      core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialEq_impl_7__f_ne := fun  (self : hax_core.primitive.primitive_definitions.t_i8) (other : hax_core.primitive.primitive_definitions.t_i8)=>
      core.ops.bit.Not__f_not (core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialEq_7864195 : core.cmp.t_PartialEq ((hax_core.primitive.primitive_definitions.t_i16)) ((hax_core.primitive.primitive_definitions.t_i16)) :=
  {
    implaabbcc_t_PartialEq_impl_8__f_eq := fun  (self : hax_core.primitive.primitive_definitions.t_i16) (other : hax_core.primitive.primitive_definitions.t_i16)=>
      core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialEq_impl_8__f_ne := fun  (self : hax_core.primitive.primitive_definitions.t_i16) (other : hax_core.primitive.primitive_definitions.t_i16)=>
      core.ops.bit.Not__f_not (core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialEq_1072156464 : core.cmp.t_PartialEq ((hax_core.primitive.primitive_definitions.t_i32)) ((hax_core.primitive.primitive_definitions.t_i32)) :=
  {
    implaabbcc_t_PartialEq_impl_9__f_eq := fun  (self : hax_core.primitive.primitive_definitions.t_i32) (other : hax_core.primitive.primitive_definitions.t_i32)=>
      core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialEq_impl_9__f_ne := fun  (self : hax_core.primitive.primitive_definitions.t_i32) (other : hax_core.primitive.primitive_definitions.t_i32)=>
      core.ops.bit.Not__f_not (core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialEq_539376648 : core.cmp.t_PartialEq ((hax_core.primitive.primitive_definitions.t_i64)) ((hax_core.primitive.primitive_definitions.t_i64)) :=
  {
    implaabbcc_t_PartialEq_impl_10__f_eq := fun  (self : hax_core.primitive.primitive_definitions.t_i64) (other : hax_core.primitive.primitive_definitions.t_i64)=>
      core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialEq_impl_10__f_ne := fun  (self : hax_core.primitive.primitive_definitions.t_i64) (other : hax_core.primitive.primitive_definitions.t_i64)=>
      core.ops.bit.Not__f_not (core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialEq_566532619 : core.cmp.t_PartialEq ((hax_core.primitive.primitive_definitions.t_i128)) ((hax_core.primitive.primitive_definitions.t_i128)) :=
  {
    implaabbcc_t_PartialEq_impl_11__f_eq := fun  (self : hax_core.primitive.primitive_definitions.t_i128) (other : hax_core.primitive.primitive_definitions.t_i128)=>
      core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialEq_impl_11__f_ne := fun  (self : hax_core.primitive.primitive_definitions.t_i128) (other : hax_core.primitive.primitive_definitions.t_i128)=>
      core.ops.bit.Not__f_not (core.cmp.PartialEq__f_eq (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

(* NotImplementedYet *)

Instance core.cmp.t_Eq_64984964 : core.cmp.t_Eq ((hax_core.primitive.primitive_definitions.t_usize)) :=
  {
  }.

Instance core.cmp.t_Eq_366520571 : core.cmp.t_Eq ((hax_core.primitive.primitive_definitions.t_u8)) :=
  {
  }.

Instance core.cmp.t_Eq_948065623 : core.cmp.t_Eq ((hax_core.primitive.primitive_definitions.t_u16)) :=
  {
  }.

Instance core.cmp.t_Eq_924576131 : core.cmp.t_Eq ((hax_core.primitive.primitive_definitions.t_u32)) :=
  {
  }.

Instance core.cmp.t_Eq_347466977 : core.cmp.t_Eq ((hax_core.primitive.primitive_definitions.t_u64)) :=
  {
  }.

Instance core.cmp.t_Eq_633137998 : core.cmp.t_Eq ((hax_core.primitive.primitive_definitions.t_u128)) :=
  {
  }.

Instance core.cmp.t_Eq_59152760 : core.cmp.t_Eq ((hax_core.primitive.primitive_definitions.t_isize)) :=
  {
  }.

Instance core.cmp.t_Eq_725589069 : core.cmp.t_Eq ((hax_core.primitive.primitive_definitions.t_i8)) :=
  {
  }.

Instance core.cmp.t_Eq_929546301 : core.cmp.t_Eq ((hax_core.primitive.primitive_definitions.t_i16)) :=
  {
  }.

Instance core.cmp.t_Eq_516268670 : core.cmp.t_Eq ((hax_core.primitive.primitive_definitions.t_i32)) :=
  {
  }.

Instance core.cmp.t_Eq_289011312 : core.cmp.t_Eq ((hax_core.primitive.primitive_definitions.t_i64)) :=
  {
  }.

Instance core.cmp.t_Eq_265905003 : core.cmp.t_Eq ((hax_core.primitive.primitive_definitions.t_i128)) :=
  {
  }.

(* NotImplementedYet *)

Instance core.cmp.t_PartialOrd_841107692 : core.cmp.t_PartialOrd ((hax_core.primitive.primitive_definitions.t_usize)) ((hax_core.primitive.primitive_definitions.t_usize)) :=
  {
    implaabbcc_t_PartialOrd_impl_24__f_partial_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_usize) (other : hax_core.primitive.primitive_definitions.t_usize)=>
      core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialOrd_impl_24__f_lt := fun  (self : hax_core.primitive.primitive_definitions.t_usize) (other : hax_core.primitive.primitive_definitions.t_usize)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_24__f_le := fun  (self : hax_core.primitive.primitive_definitions.t_usize) (other : hax_core.primitive.primitive_definitions.t_usize)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_24__f_ge := fun  (self : hax_core.primitive.primitive_definitions.t_usize) (other : hax_core.primitive.primitive_definitions.t_usize)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_24__f_gt := fun  (self : hax_core.primitive.primitive_definitions.t_usize) (other : hax_core.primitive.primitive_definitions.t_usize)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
  }.

Instance core.cmp.t_Ord_1004835655 : core.cmp.t_Ord ((hax_core.primitive.primitive_definitions.t_usize)) :=
  {
    implaabbcc_t_Ord_impl_25__f_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_usize) (other : hax_core.primitive.primitive_definitions.t_usize)=>
      core.option.impl__unwrap (core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialOrd_739041138 : core.cmp.t_PartialOrd ((hax_core.primitive.primitive_definitions.t_u8)) ((hax_core.primitive.primitive_definitions.t_u8)) :=
  {
    implaabbcc_t_PartialOrd_impl_26__f_partial_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_u8) (other : hax_core.primitive.primitive_definitions.t_u8)=>
      core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialOrd_impl_26__f_lt := fun  (self : hax_core.primitive.primitive_definitions.t_u8) (other : hax_core.primitive.primitive_definitions.t_u8)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_26__f_le := fun  (self : hax_core.primitive.primitive_definitions.t_u8) (other : hax_core.primitive.primitive_definitions.t_u8)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_26__f_ge := fun  (self : hax_core.primitive.primitive_definitions.t_u8) (other : hax_core.primitive.primitive_definitions.t_u8)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_26__f_gt := fun  (self : hax_core.primitive.primitive_definitions.t_u8) (other : hax_core.primitive.primitive_definitions.t_u8)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
  }.

Instance core.cmp.t_Ord_7528255 : core.cmp.t_Ord ((hax_core.primitive.primitive_definitions.t_u8)) :=
  {
    implaabbcc_t_Ord_impl_27__f_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_u8) (other : hax_core.primitive.primitive_definitions.t_u8)=>
      core.option.impl__unwrap (core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialOrd_967435844 : core.cmp.t_PartialOrd ((hax_core.primitive.primitive_definitions.t_u16)) ((hax_core.primitive.primitive_definitions.t_u16)) :=
  {
    implaabbcc_t_PartialOrd_impl_28__f_partial_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_u16) (other : hax_core.primitive.primitive_definitions.t_u16)=>
      core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialOrd_impl_28__f_lt := fun  (self : hax_core.primitive.primitive_definitions.t_u16) (other : hax_core.primitive.primitive_definitions.t_u16)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_28__f_le := fun  (self : hax_core.primitive.primitive_definitions.t_u16) (other : hax_core.primitive.primitive_definitions.t_u16)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_28__f_ge := fun  (self : hax_core.primitive.primitive_definitions.t_u16) (other : hax_core.primitive.primitive_definitions.t_u16)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_28__f_gt := fun  (self : hax_core.primitive.primitive_definitions.t_u16) (other : hax_core.primitive.primitive_definitions.t_u16)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
  }.

Instance core.cmp.t_Ord_887641043 : core.cmp.t_Ord ((hax_core.primitive.primitive_definitions.t_u16)) :=
  {
    implaabbcc_t_Ord_impl_29__f_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_u16) (other : hax_core.primitive.primitive_definitions.t_u16)=>
      core.option.impl__unwrap (core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialOrd_346822307 : core.cmp.t_PartialOrd ((hax_core.primitive.primitive_definitions.t_u32)) ((hax_core.primitive.primitive_definitions.t_u32)) :=
  {
    implaabbcc_t_PartialOrd_impl_30__f_partial_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_u32) (other : hax_core.primitive.primitive_definitions.t_u32)=>
      core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialOrd_impl_30__f_lt := fun  (self : hax_core.primitive.primitive_definitions.t_u32) (other : hax_core.primitive.primitive_definitions.t_u32)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_30__f_le := fun  (self : hax_core.primitive.primitive_definitions.t_u32) (other : hax_core.primitive.primitive_definitions.t_u32)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_30__f_ge := fun  (self : hax_core.primitive.primitive_definitions.t_u32) (other : hax_core.primitive.primitive_definitions.t_u32)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_30__f_gt := fun  (self : hax_core.primitive.primitive_definitions.t_u32) (other : hax_core.primitive.primitive_definitions.t_u32)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
  }.

Instance core.cmp.t_Ord_49988746 : core.cmp.t_Ord ((hax_core.primitive.primitive_definitions.t_u32)) :=
  {
    implaabbcc_t_Ord_impl_31__f_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_u32) (other : hax_core.primitive.primitive_definitions.t_u32)=>
      core.option.impl__unwrap (core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialOrd_326274661 : core.cmp.t_PartialOrd ((hax_core.primitive.primitive_definitions.t_u64)) ((hax_core.primitive.primitive_definitions.t_u64)) :=
  {
    implaabbcc_t_PartialOrd_impl_32__f_partial_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_u64) (other : hax_core.primitive.primitive_definitions.t_u64)=>
      core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialOrd_impl_32__f_lt := fun  (self : hax_core.primitive.primitive_definitions.t_u64) (other : hax_core.primitive.primitive_definitions.t_u64)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_32__f_le := fun  (self : hax_core.primitive.primitive_definitions.t_u64) (other : hax_core.primitive.primitive_definitions.t_u64)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_32__f_ge := fun  (self : hax_core.primitive.primitive_definitions.t_u64) (other : hax_core.primitive.primitive_definitions.t_u64)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_32__f_gt := fun  (self : hax_core.primitive.primitive_definitions.t_u64) (other : hax_core.primitive.primitive_definitions.t_u64)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
  }.

Instance core.cmp.t_Ord_740797107 : core.cmp.t_Ord ((hax_core.primitive.primitive_definitions.t_u64)) :=
  {
    implaabbcc_t_Ord_impl_33__f_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_u64) (other : hax_core.primitive.primitive_definitions.t_u64)=>
      core.option.impl__unwrap (core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialOrd_947511895 : core.cmp.t_PartialOrd ((hax_core.primitive.primitive_definitions.t_u128)) ((hax_core.primitive.primitive_definitions.t_u128)) :=
  {
    implaabbcc_t_PartialOrd_impl_34__f_partial_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_u128) (other : hax_core.primitive.primitive_definitions.t_u128)=>
      core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialOrd_impl_34__f_lt := fun  (self : hax_core.primitive.primitive_definitions.t_u128) (other : hax_core.primitive.primitive_definitions.t_u128)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_34__f_le := fun  (self : hax_core.primitive.primitive_definitions.t_u128) (other : hax_core.primitive.primitive_definitions.t_u128)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_34__f_ge := fun  (self : hax_core.primitive.primitive_definitions.t_u128) (other : hax_core.primitive.primitive_definitions.t_u128)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_34__f_gt := fun  (self : hax_core.primitive.primitive_definitions.t_u128) (other : hax_core.primitive.primitive_definitions.t_u128)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
  }.

Instance core.cmp.t_Ord_288411767 : core.cmp.t_Ord ((hax_core.primitive.primitive_definitions.t_u128)) :=
  {
    implaabbcc_t_Ord_impl_35__f_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_u128) (other : hax_core.primitive.primitive_definitions.t_u128)=>
      core.option.impl__unwrap (core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialOrd_797290082 : core.cmp.t_PartialOrd ((hax_core.primitive.primitive_definitions.t_isize)) ((hax_core.primitive.primitive_definitions.t_isize)) :=
  {
    implaabbcc_t_PartialOrd_impl_36__f_partial_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_isize) (other : hax_core.primitive.primitive_definitions.t_isize)=>
      core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialOrd_impl_36__f_lt := fun  (self : hax_core.primitive.primitive_definitions.t_isize) (other : hax_core.primitive.primitive_definitions.t_isize)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_36__f_le := fun  (self : hax_core.primitive.primitive_definitions.t_isize) (other : hax_core.primitive.primitive_definitions.t_isize)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_36__f_ge := fun  (self : hax_core.primitive.primitive_definitions.t_isize) (other : hax_core.primitive.primitive_definitions.t_isize)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_36__f_gt := fun  (self : hax_core.primitive.primitive_definitions.t_isize) (other : hax_core.primitive.primitive_definitions.t_isize)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
  }.

Instance core.cmp.t_Ord_390807072 : core.cmp.t_Ord ((hax_core.primitive.primitive_definitions.t_isize)) :=
  {
    implaabbcc_t_Ord_impl_37__f_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_isize) (other : hax_core.primitive.primitive_definitions.t_isize)=>
      core.option.impl__unwrap (core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialOrd_666983941 : core.cmp.t_PartialOrd ((hax_core.primitive.primitive_definitions.t_i8)) ((hax_core.primitive.primitive_definitions.t_i8)) :=
  {
    implaabbcc_t_PartialOrd_impl_38__f_partial_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_i8) (other : hax_core.primitive.primitive_definitions.t_i8)=>
      core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialOrd_impl_38__f_lt := fun  (self : hax_core.primitive.primitive_definitions.t_i8) (other : hax_core.primitive.primitive_definitions.t_i8)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_38__f_le := fun  (self : hax_core.primitive.primitive_definitions.t_i8) (other : hax_core.primitive.primitive_definitions.t_i8)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_38__f_ge := fun  (self : hax_core.primitive.primitive_definitions.t_i8) (other : hax_core.primitive.primitive_definitions.t_i8)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_38__f_gt := fun  (self : hax_core.primitive.primitive_definitions.t_i8) (other : hax_core.primitive.primitive_definitions.t_i8)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
  }.

Instance core.cmp.t_Ord_401919007 : core.cmp.t_Ord ((hax_core.primitive.primitive_definitions.t_i8)) :=
  {
    implaabbcc_t_Ord_impl_39__f_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_i8) (other : hax_core.primitive.primitive_definitions.t_i8)=>
      core.option.impl__unwrap (core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialOrd_747295183 : core.cmp.t_PartialOrd ((hax_core.primitive.primitive_definitions.t_i16)) ((hax_core.primitive.primitive_definitions.t_i16)) :=
  {
    implaabbcc_t_PartialOrd_impl_40__f_partial_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_i16) (other : hax_core.primitive.primitive_definitions.t_i16)=>
      core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialOrd_impl_40__f_lt := fun  (self : hax_core.primitive.primitive_definitions.t_i16) (other : hax_core.primitive.primitive_definitions.t_i16)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_40__f_le := fun  (self : hax_core.primitive.primitive_definitions.t_i16) (other : hax_core.primitive.primitive_definitions.t_i16)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_40__f_ge := fun  (self : hax_core.primitive.primitive_definitions.t_i16) (other : hax_core.primitive.primitive_definitions.t_i16)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_40__f_gt := fun  (self : hax_core.primitive.primitive_definitions.t_i16) (other : hax_core.primitive.primitive_definitions.t_i16)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
  }.

Instance core.cmp.t_Ord_853778731 : core.cmp.t_Ord ((hax_core.primitive.primitive_definitions.t_i16)) :=
  {
    implaabbcc_t_Ord_impl_41__f_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_i16) (other : hax_core.primitive.primitive_definitions.t_i16)=>
      core.option.impl__unwrap (core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialOrd_31665165 : core.cmp.t_PartialOrd ((hax_core.primitive.primitive_definitions.t_i32)) ((hax_core.primitive.primitive_definitions.t_i32)) :=
  {
    implaabbcc_t_PartialOrd_impl_42__f_partial_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_i32) (other : hax_core.primitive.primitive_definitions.t_i32)=>
      core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialOrd_impl_42__f_lt := fun  (self : hax_core.primitive.primitive_definitions.t_i32) (other : hax_core.primitive.primitive_definitions.t_i32)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_42__f_le := fun  (self : hax_core.primitive.primitive_definitions.t_i32) (other : hax_core.primitive.primitive_definitions.t_i32)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_42__f_ge := fun  (self : hax_core.primitive.primitive_definitions.t_i32) (other : hax_core.primitive.primitive_definitions.t_i32)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_42__f_gt := fun  (self : hax_core.primitive.primitive_definitions.t_i32) (other : hax_core.primitive.primitive_definitions.t_i32)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
  }.

Instance core.cmp.t_Ord_126291967 : core.cmp.t_Ord ((hax_core.primitive.primitive_definitions.t_i32)) :=
  {
    implaabbcc_t_Ord_impl_43__f_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_i32) (other : hax_core.primitive.primitive_definitions.t_i32)=>
      core.option.impl__unwrap (core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialOrd_844564106 : core.cmp.t_PartialOrd ((hax_core.primitive.primitive_definitions.t_i64)) ((hax_core.primitive.primitive_definitions.t_i64)) :=
  {
    implaabbcc_t_PartialOrd_impl_44__f_partial_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_i64) (other : hax_core.primitive.primitive_definitions.t_i64)=>
      core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialOrd_impl_44__f_lt := fun  (self : hax_core.primitive.primitive_definitions.t_i64) (other : hax_core.primitive.primitive_definitions.t_i64)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_44__f_le := fun  (self : hax_core.primitive.primitive_definitions.t_i64) (other : hax_core.primitive.primitive_definitions.t_i64)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_44__f_ge := fun  (self : hax_core.primitive.primitive_definitions.t_i64) (other : hax_core.primitive.primitive_definitions.t_i64)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_44__f_gt := fun  (self : hax_core.primitive.primitive_definitions.t_i64) (other : hax_core.primitive.primitive_definitions.t_i64)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
  }.

Instance core.cmp.t_Ord_799628634 : core.cmp.t_Ord ((hax_core.primitive.primitive_definitions.t_i64)) :=
  {
    implaabbcc_t_Ord_impl_45__f_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_i64) (other : hax_core.primitive.primitive_definitions.t_i64)=>
      core.option.impl__unwrap (core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.

Instance core.cmp.t_PartialOrd_16153573 : core.cmp.t_PartialOrd ((hax_core.primitive.primitive_definitions.t_i128)) ((hax_core.primitive.primitive_definitions.t_i128)) :=
  {
    implaabbcc_t_PartialOrd_impl_46__f_partial_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_i128) (other : hax_core.primitive.primitive_definitions.t_i128)=>
      core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other);
    implaabbcc_t_PartialOrd_impl_46__f_lt := fun  (self : hax_core.primitive.primitive_definitions.t_i128) (other : hax_core.primitive.primitive_definitions.t_i128)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_46__f_le := fun  (self : hax_core.primitive.primitive_definitions.t_i128) (other : hax_core.primitive.primitive_definitions.t_i128)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Less
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_46__f_ge := fun  (self : hax_core.primitive.primitive_definitions.t_i128) (other : hax_core.primitive.primitive_definitions.t_i128)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater
      | core.cmp.Ordering_Equal) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
    implaabbcc_t_PartialOrd_impl_46__f_gt := fun  (self : hax_core.primitive.primitive_definitions.t_i128) (other : hax_core.primitive.primitive_definitions.t_i128)=>
      match core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other) with
      | core.option.Option_Some (core.cmp.Ordering_Greater) =>
        (true : bool)
      | _ =>
        (false : bool)
      end;
  }.

Instance core.cmp.t_Ord_952024608 : core.cmp.t_Ord ((hax_core.primitive.primitive_definitions.t_i128)) :=
  {
    implaabbcc_t_Ord_impl_47__f_cmp := fun  (self : hax_core.primitive.primitive_definitions.t_i128) (other : hax_core.primitive.primitive_definitions.t_i128)=>
      core.option.impl__unwrap (core.cmp.PartialOrd__f_partial_cmp (hax_core.primitive.primitive_definitions.0 self) (hax_core.primitive.primitive_definitions.0 other));
  }.
