(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

(* NotImplementedYet *)



Instance core.convert.t_From_590932605 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u16)) ((hax_core.primitive.primitive_definitions.t_u8)) :=
  {
    implaabbcc_t_From_impl__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_u8)=>
      hax_core.primitive.primitive_definitions.Build_t__u16_u16 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_416512678 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u32)) ((hax_core.primitive.primitive_definitions.t_u8)) :=
  {
    implaabbcc_t_From_impl_1__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_u8)=>
      hax_core.primitive.primitive_definitions.Build_t__u32_u32 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_600464988 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u64)) ((hax_core.primitive.primitive_definitions.t_u8)) :=
  {
    implaabbcc_t_From_impl_2__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_u8)=>
      hax_core.primitive.primitive_definitions.Build_t__u64_u64 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_294704224 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u128)) ((hax_core.primitive.primitive_definitions.t_u8)) :=
  {
    implaabbcc_t_From_impl_3__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_u8)=>
      hax_core.primitive.primitive_definitions.Build_t__u128_u128 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_34029306 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_usize)) ((hax_core.primitive.primitive_definitions.t_u8)) :=
  {
    implaabbcc_t_From_impl_4__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_u8)=>
      hax_core.primitive.primitive_definitions.Build_t__usize_usize (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_932282715 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u32)) ((hax_core.primitive.primitive_definitions.t_u16)) :=
  {
    implaabbcc_t_From_impl_5__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_u16)=>
      hax_core.primitive.primitive_definitions.Build_t__u32_u32 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_886967324 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u64)) ((hax_core.primitive.primitive_definitions.t_u16)) :=
  {
    implaabbcc_t_From_impl_6__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_u16)=>
      hax_core.primitive.primitive_definitions.Build_t__u64_u64 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_474255626 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u128)) ((hax_core.primitive.primitive_definitions.t_u16)) :=
  {
    implaabbcc_t_From_impl_7__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_u16)=>
      hax_core.primitive.primitive_definitions.Build_t__u128_u128 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_1039917283 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u64)) ((hax_core.primitive.primitive_definitions.t_u32)) :=
  {
    implaabbcc_t_From_impl_8__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_u32)=>
      hax_core.primitive.primitive_definitions.Build_t__u64_u64 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_1036524566 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u128)) ((hax_core.primitive.primitive_definitions.t_u32)) :=
  {
    implaabbcc_t_From_impl_9__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_u32)=>
      hax_core.primitive.primitive_definitions.Build_t__u128_u128 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_243138733 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_u128)) ((hax_core.primitive.primitive_definitions.t_u64)) :=
  {
    implaabbcc_t_From_impl_10__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_u64)=>
      hax_core.primitive.primitive_definitions.Build_t__u128_u128 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_225219218 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_i16)) ((hax_core.primitive.primitive_definitions.t_i8)) :=
  {
    implaabbcc_t_From_impl_11__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_i8)=>
      hax_core.primitive.primitive_definitions.Build_t__i16_i16 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_496892395 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_i32)) ((hax_core.primitive.primitive_definitions.t_i8)) :=
  {
    implaabbcc_t_From_impl_12__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_i8)=>
      hax_core.primitive.primitive_definitions.Build_t__i32_i32 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_981593525 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_i64)) ((hax_core.primitive.primitive_definitions.t_i8)) :=
  {
    implaabbcc_t_From_impl_13__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_i8)=>
      hax_core.primitive.primitive_definitions.Build_t__i64_i64 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_663187281 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_i128)) ((hax_core.primitive.primitive_definitions.t_i8)) :=
  {
    implaabbcc_t_From_impl_14__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_i8)=>
      hax_core.primitive.primitive_definitions.Build_t__i128_i128 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_982532916 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_isize)) ((hax_core.primitive.primitive_definitions.t_i8)) :=
  {
    implaabbcc_t_From_impl_15__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_i8)=>
      hax_core.primitive.primitive_definitions.Build_t__isize_isize (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_390512590 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_i32)) ((hax_core.primitive.primitive_definitions.t_i16)) :=
  {
    implaabbcc_t_From_impl_16__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_i16)=>
      hax_core.primitive.primitive_definitions.Build_t__i32_i32 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_319200562 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_i64)) ((hax_core.primitive.primitive_definitions.t_i16)) :=
  {
    implaabbcc_t_From_impl_17__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_i16)=>
      hax_core.primitive.primitive_definitions.Build_t__i64_i64 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_474512890 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_i128)) ((hax_core.primitive.primitive_definitions.t_i16)) :=
  {
    implaabbcc_t_From_impl_18__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_i16)=>
      hax_core.primitive.primitive_definitions.Build_t__i128_i128 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_850837943 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_i64)) ((hax_core.primitive.primitive_definitions.t_i32)) :=
  {
    implaabbcc_t_From_impl_19__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_i32)=>
      hax_core.primitive.primitive_definitions.Build_t__i64_i64 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_423865957 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_i128)) ((hax_core.primitive.primitive_definitions.t_i32)) :=
  {
    implaabbcc_t_From_impl_20__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_i32)=>
      hax_core.primitive.primitive_definitions.Build_t__i128_i128 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_562533374 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_i128)) ((hax_core.primitive.primitive_definitions.t_i64)) :=
  {
    implaabbcc_t_From_impl_21__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_i64)=>
      hax_core.primitive.primitive_definitions.Build_t__i128_i128 (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_532624598 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_usize)) ((hax_core.primitive.primitive_definitions.t_u16)) :=
  {
    implaabbcc_t_From_impl_22__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_u16)=>
      hax_core.primitive.primitive_definitions.Build_t__usize_usize (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.

Instance core.convert.t_From_1036696118 : core.convert.t_From ((hax_core.primitive.primitive_definitions.t_isize)) ((hax_core.primitive.primitive_definitions.t_i16)) :=
  {
    implaabbcc_t_From_impl_23__f_from := fun  (small : hax_core.primitive.primitive_definitions.t_i16)=>
      hax_core.primitive.primitive_definitions.Build_t__isize_isize (core.convert.Into__f_into (hax_core.primitive.primitive_definitions.0 small));
  }.
