(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)



Class t_ExactSizeIterator (v_Self : Type) `{core.iter.traits.iterator.t_Iterator (v_Self)} : Type :=
  {
    ExactSizeIterator__f_len : v_Self -> t_usize;
    ExactSizeIterator__f_is_empty : v_Self -> bool;
  }.
Arguments t_ExactSizeIterator (_) {_}.
