name: Release binaries for hax-engine

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release-js:
    if: github.repository == 'cryspen/hax'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Build JS
      run: nix build .#hax-engine.passthru.js -L -o hax-engine.js

    - run: |
        tar --dereference -czf hacspec_js.tar.gz hax-engine.js

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: hacspec_js.tar.gz

  release:
    if: github.repository == 'cryspen/hax'
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler: [5.4.1]
        
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - uses: dtolnay/rust-toolchain@1.70
          
      - run: cargo install --path cli/driver && cargo install --path cli/cargo-hax && cargo install --path engine/names/extract

      - run: opam install . --deps-only
        working-directory: engine
        
      - run: opam exec -- dune build
        working-directory: engine

      - run: |
          cp engine/_build/default/bin/native_driver.exe  hax-engine
          tar -czf hacspec_${{ matrix.os }}.tar.gz hax-engine
        
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: hacspec_${{ matrix.os }}.tar.gz

          
