(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Definition inline_me '(_ : unit) : unit :=
  tt.

Definition no_inlining_please '(_ : unit) : unit :=
  tt.

Definition generic `{v_T : Type} '(_ : unit) : unit :=
  tt.
